chromeos-base/ec-utils: Extend the lifetime of the result string
With llvm-r547379-1, the following warning is issued:

    util/ectool.cc:1911:16: error: object backing the pointer error_str will be destroyed
          at the end of the full-expression [-Werror,-Wdangling-assignment-gsl]
     1911 |                         error_str = frame_cmd->ResultString().c_str();
          |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

To ensure error_str doesn't point to invalid memory outside of the
if block, retrieve ResultString into a std::string with lifetime
long enough to still exist when the string is actually used.

BUG=b:368393962
TEST=emerge-jacuzzi ec-utils

Change-Id: Ib9ee399e581a6461c5ac2dcc1465675a9e37bce6