Update patch set 4
Patch Set 4:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8824405986094795041
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'zephyr/app/ec/ec_app_main.c' cleanly.
        Applied patch to 'zephyr/shim/src/watchdog.c' cleanly.
        Applied patch to 'zephyr/test/drivers/include/stubs.h' cleanly.
        Applied patch to 'zephyr/test/drivers/overlay.dts' cleanly.
        Applied patch to 'zephyr/test/drivers/prj.conf' with conflicts.
        Applied patch to 'zephyr/test/drivers/src/main.c' with conflicts.
        Applied patch to 'zephyr/test/drivers/src/stubs.c' with conflicts.
        error: zephyr/test/drivers/src/watchdog.c: does not exist in index
        error: cannot read the current contents of 'zephyr/test/drivers/src/watchdog.c'
        Falling back to direct application...
        U zephyr/test/drivers/prj.conf
        U zephyr/test/drivers/src/main.c
        U zephyr/test/drivers/src/stubs.c

Patch-set: 4
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1530058 \u003c1530058@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: CQ dry run failed."}