Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8822664224578346049
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to '.gitlab-ci.yml' with conflicts.
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        Applied patch to 'zephyr/projects/herobrine/BUILD.py' cleanly.
        Applied patch to 'zephyr/projects/herobrine/CMakeLists.txt' cleanly.
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        U .gitlab-ci.yml

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1112825 \u003c1112825@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ full run failed."}