Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8872698511441565248
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: baseboard/dedede/baseboard.h:1
        Falling back to three-way merge...
        Applied patch to 'baseboard/dedede/baseboard.h' with conflicts.
        U baseboard/dedede/baseboard.h

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1302633 \u003c1302633@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}