Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8830904518030490113
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'zephyr/Kconfig.init_priority' cleanly.
        Applied patch to 'zephyr/boards/arm/brya/brya_defconfig' cleanly.
        Applied patch to 'zephyr/boards/arm/herobrine_npcx9/herobrine_npcx9_defconfig' cleanly.
        error: zephyr/boards/arm/kohaku/kohaku_defconfig: does not exist in index
        Applied patch to 'zephyr/boards/arm/npcx9/npcx9_defconfig' cleanly.
        Applied patch to 'zephyr/boards/arm/npcx_evb/npcx7_evb_defconfig' cleanly.
        Applied patch to 'zephyr/boards/arm/npcx_evb/npcx9_evb_defconfig' cleanly.
        Applied patch to 'zephyr/boards/arm/trogdor/trogdor_defconfig' cleanly.
        Applied patch to 'zephyr/boards/arm/volteer/volteer_defconfig' cleanly.
        Applied patch to 'zephyr/drivers/cros_flash/Kconfig' cleanly.
        Applied patch to 'zephyr/drivers/cros_flash/cros_flash_npcx.c' cleanly.
        Applied patch to 'zephyr/dts/bindings/cros_flash/nuvoton,npcx-cros-flash.yaml' cleanly.
        Applied patch to 'zephyr/include/cros/nuvoton/npcx.dtsi' cleanly.
        Applied patch to 'zephyr/include/soc/nuvoton_npcx/reg_def_cros.h' cleanly.
        Applied patch to 'zephyr/shim/src/flash.c' cleanly.

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1308749 \u003c1308749@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ full run failed."}