include/power: Fix header guard typo
When building with clang:

In file included from board/ambassador/board.c:30:
include/power/cometlake-discrete.h:11:9: error:
'__CROS_EC_COMETLAKE_DISCRETE_H' is used as a header guard here,
followed by

include/power/cometlake-discrete.h:12:9: note:
'__CROS_EC_COMETLATE_DISCRETE_H'
is defined here; did you mean '__CROS_EC_COMETLAKE_DISCRETE_H'?

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=ambassador
TEST=./util/compare_build.sh -b all -j 70
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I4cda48bc44720ee7ee59e558bf00f26059e58345