Update patch set 27
Patch Set 27:

The following build(s) failed:

peppy-paladin: The Archive stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
Copying file:///b/cbuild/internal_master/buildbot_archive/peppy-paladin/R39-6216.0.0-rc2/au-generator.zip [Content-Type=application/zip]...
Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  0 B/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  65.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  137.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  209.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  281.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  353.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  425.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  497.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  569.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  641.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  713.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  785.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  921.17 KB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.03 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.17 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.3 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.43 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.56 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.7 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.83 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.96 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.09 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.23 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.49 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.74 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  3 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.26 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.52 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.77 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.03 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.29 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.55 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.81 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  5.06 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  5.57 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  6.08 MB/6.24 MB    Uploading   ...peppy-paladin/R39-6216.0.0-rc2/au-generator.zip:  6.24 MB/6.24 MB    
ResumableUploadAbortException: 410 Backend Error
CommandException: 1 files/objects could not be transferred.

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.5.tar.gz/gsutil/gsutil -o 'GSUtil:parallel_composite_upload_threshold=0' -o 'Boto:num_retries=10' -m cp -- /b/cbuild/internal_master/buildbot_archive/peppy-paladin/R39-6216.0.0-rc2/au-generator.zip gs://chromeos-image-archive/peppy-paladin/R39-6216.0.0-rc2/au-generator.zip", cwd=None, extra env={'BOTO_CONFIG': '/b/build/site_config/.boto'} in https://uberchromegw.corp.google.com/i/chromeos/builders/peppy%20paladin/builds/4741

monroe-paladin: The Archive stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
Copying file:///b/cbuild/internal_master/buildbot_archive/monroe-paladin/R39-6216.0.0-rc2/au-generator.zip [Content-Type=application/zip]...
Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  0 B/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  65.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  137.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  209.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  281.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  353.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  425.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  497.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  569.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  641.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  713.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  785.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  921.17 KB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.03 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.17 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.3 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.43 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.56 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.7 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.83 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  1.96 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.09 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.23 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.49 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  2.74 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  3 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.26 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.52 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  3.77 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.03 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.29 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.55 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  4.81 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  5.06 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  5.57 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  6.08 MB/6.24 MB    Uploading   ...onroe-paladin/R39-6216.0.0-rc2/au-generator.zip:  6.24 MB/6.24 MB    
ResumableUploadAbortException: 410 Backend Error
CommandException: 1 files/objects could not be transferred.

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.5.tar.gz/gsutil/gsutil -o 'GSUtil:parallel_composite_upload_threshold=0' -o 'Boto:num_retries=10' -m cp -- /b/cbuild/internal_master/buildbot_archive/monroe-paladin/R39-6216.0.0-rc2/au-generator.zip gs://chromeos-image-archive/monroe-paladin/R39-6216.0.0-rc2/au-generator.zip", cwd=None, extra env={'BOTO_CONFIG': '/b/build/site_config/.boto'} in https://uberchromegw.corp.google.com/i/chromeos/builders/monroe%20paladin/builds/2796

Your change may have caused this failure. There are also other changes that may be at fault: 28 other changes. See the blamelist for more details.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 27