Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8858716251576734928
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/cr50/board.h:1
        Falling back to three-way merge...
        Applied patch to 'board/cr50/board.h' cleanly.
        error: patch failed: chip/g/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'chip/g/build.mk' cleanly.
        error: patch failed: include/config.h:1
        Falling back to three-way merge...
        Applied patch to 'include/config.h' with conflicts.
        U include/config.h

Patch-set: 1
Tag: autogenerated:cq:full-run