Update patch set 6
Patch Set 6:

The following build(s) failed:

daisy paladin: The BuildTarget stage failed: Packages failed in ./build_packages: sys-power/powertop in http://uberchromegw.corp.google.com/i/chromeos/builders/daisy%20paladin/builds/9807

link paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/parallel.py", line 176, in _RunSteps
    step()
  File "/b/cbuild/link-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1899, in ArchivePayloads
    buildroot, target_image_path, update_payloads_dir)
  File "/b/cbuild/link-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1446, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/cros_build_lib.py", line 777, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/cros_build_lib.py", line 457, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 21, in <module>

2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log:     import autoupdate

2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/autoupdate.py", line 25, in <module>

2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log:     import update_payload

2013/03/07 20:56:36 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named update_payload

Traceback (most recent call last):
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    results = ProcessOutput(log_files)
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 308, in ProcessOutput
    raise InvalidDevserverOutput('Could not parse devserver log')
__main__.InvalidDevserverOutput: Could not parse devserver log

2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Generating an unsigned full payload to /b/cbuild/link-paladin-bin-master/src/build/images/link/latest-cbuildbot/chromiumos_test_image.bin

Failed command "['/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py', '--target=/b/cbuild/link-paladin-bin-master/src/build/images/link/latest-cbuildbot/chromiumos_test_image.bin', '--full_payload', '--nplus1_archive_dir=/tmp/cbuildbot-tmpndCtAm/cbuildbotr7H68o']", cwd=None, extra env=None
 in http://uberchromegw.corp.google.com/i/chromeos/builders/link%20paladin/builds/12115

amd64 generic paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in http://build.chromium.org/p/chromiumos/builders/amd64%20generic%20paladin/builds/13208

lumpy paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/parallel.py", line 176, in _RunSteps
    step()
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1899, in ArchivePayloads
    buildroot, target_image_path, update_payloads_dir)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1446, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 777, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 457, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 21, in <module>

2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log:     import autoupdate

2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/autoupdate.py", line 25, in <module>

2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log:     import update_payload

2013/03/07 20:56:38 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named update_payload

Traceback (most recent call last):
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    results = ProcessOutput(log_files)
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 308, in ProcessOutput
    raise InvalidDevserverOutput('Could not parse devserver log')
__main__.InvalidDevserverOutput: Could not parse devserver log

2013/03/07 20:56:35 - cros_generate_test_payloads.py - INFO    : Generating an unsigned full payload to /b/cbuild/lumpy-paladin-bin-master/src/build/images/lumpy/latest-cbuildbot/chromiumos_test_image.bin

Failed command "['/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py', '--target=/b/cbuild/lumpy-paladin-bin-master/src/build/images/lumpy/latest-cbuildbot/chromiumos_test_image.bin', '--full_payload', '--nplus1_archive_dir=/tmp/cbuildbot-tmpClr5oV/cbuildbotWjutyX']", cwd=None, extra env=None
 in http://uberchromegw.corp.google.com/i/chromeos/builders/lumpy%20paladin/builds/12074

mario paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in http://uberchromegw.corp.google.com/i/chromeos/builders/mario%20paladin/builds/10009

alex paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/parallel.py", line 176, in _RunSteps
    step()
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1899, in ArchivePayloads
    buildroot, target_image_path, update_payloads_dir)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1446, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 777, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 457, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/03/07 20:55:48 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/03/07 20:55:48 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 21, in <module>

2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log:     import autoupdate

2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/autoupdate.py", line 25, in <module>

2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log:     import update_payload

2013/03/07 20:55:50 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named update_payload

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    results = ProcessOutput(log_files)
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 308, in ProcessOutput
    raise InvalidDevserverOutput('Could not parse devserver log')
__main__.InvalidDevserverOutput: Could not parse devserver log

2013/03/07 20:55:48 - cros_generate_test_payloads.py - INFO    : Generating an unsigned full payload to /b/cbuild/x86-alex-paladin-bin-master/src/build/images/x86-alex/latest-cbuildbot/chromiumos_test_image.bin

Failed command "['/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py', '--target=/b/cbuild/x86-alex-paladin-bin-master/src/build/images/x86-alex/latest-cbuildbot/chromiumos_test_image.bin', '--full_payload', '--nplus1_archive_dir=/tmp/cbuildbot-tmpGQsB7j/cbuildbotsR92qs']", cwd=None, extra env=None
 in http://uberchromegw.corp.google.com/i/chromeos/builders/alex%20paladin/builds/12117

stumpy paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/parallel.py", line 176, in _RunSteps
    step()
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1899, in ArchivePayloads
    buildroot, target_image_path, update_payloads_dir)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1446, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 777, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 457, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/03/07 20:55:47 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/03/07 20:55:47 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 21, in <module>

2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log:     import autoupdate

2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/autoupdate.py", line 25, in <module>

2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log:     import update_payload

2013/03/07 20:55:51 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named update_payload

Traceback (most recent call last):
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    results = ProcessOutput(log_files)
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 308, in ProcessOutput
    raise InvalidDevserverOutput('Could not parse devserver log')
__main__.InvalidDevserverOutput: Could not parse devserver log

2013/03/07 20:55:47 - cros_generate_test_payloads.py - INFO    : Generating an unsigned full payload to /b/cbuild/stumpy-paladin-bin-master/src/build/images/stumpy/latest-cbuildbot/chromiumos_test_image.bin

Failed command "['/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py', '--target=/b/cbuild/stumpy-paladin-bin-master/src/build/images/stumpy/latest-cbuildbot/chromiumos_test_image.bin', '--full_payload', '--nplus1_archive_dir=/tmp/cbuildbot-tmpAl51ix/cbuildbotQ3tSLm']", cwd=None, extra env=None
 in http://uberchromegw.corp.google.com/i/chromeos/builders/stumpy%20paladin/builds/12116

x86 generic paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in http://build.chromium.org/p/chromiumos/builders/x86%20generic%20paladin/builds/13403

Your change may have caused this failure. There are also other changes that may be at fault: *Ib4c2eef9d0b23c41c4df41f4e468bb289211df2c, I0832a5408ce6a4d64e3be6a71ce9c34efb060865, I5b045ab7ccfef99f425b50d96438b44d0f1277c2, I6dc2e86be6ef64ca0384c407c9e90ad3c8b0f9e1, I7258d81a66a5c763cc62f6800965fe1a57a0008e, I77123a1fffbb2059c239b7145c6922968fdffb6a, I9ccf011bbc275a039875d23b5ab01266587bff60, Ib3ff57e17afab9ba8fc78fdb037e65aae844f38b, Ib4ca1475da553b9d2bd2493a9945670d0decffc4, Ibb3430548a7cb4192213fbe539aada66f35e9966, If082e612da9445c9798e1b6aeb5053b9b293f4cd, Iff89a1e00d05d86431399a142f9ec2c6837ba9e6

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 6