Update patch set 2
Patch Set 2: Commit-Queue+1

Unrelated failure:

buffet-0.0.1-r1253: FAILED: i686-pc-linux-gnu-g++ -MMD -MF obj/buffet/buffet_common.webserv_client.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DBUFFET_USE_WIFI_BOOTSTRAPPING -I../../../../../../../../../mnt/host/source/src/platform2/buffet -Iobj/buffet/buffet_common.gen/include -Igen/include -I/mnt/host/source/src/platform2 -I/mnt/host/source/src/platform -I/build/x86-generic/usr/include -Wall -Wno-psabi -ggdb3 -fstack-protector-strong -Wformat=2 -fvisibility=internal -Wa,--noexecstack -Werror --sysroot=/build/x86-generic -DUSE_RTTI_FOR_TYPE_TAGS -Wno-c++11-extensions -Wno-unused-local-typedefs -DBASE_VER=334380 -pthread -I/build/x86-generic/usr/include/shill-client -I/build/x86-generic/usr/include/apmanager-client -I/build/x86-generic/usr/include/peerd-client -I/build/x86-generic/usr/include/chromeos -I/build/x86-generic/usr/include/base-334380 -I/build/x86-generic/usr/include/glib-2.0 -I/build/x86-generic/usr/lib/glib-2.0/include -I/build/x86-generic/usr/include/dbus-1.0 -I/build/x86-generic/usr/lib/dbus-1.0/include -I/build/x86-generic/usr/include/nss -I/build/x86-generic/usr/include/nspr -fPIE -std=gnu++11 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -O2 -march=i686 -pipe -O2 -march=i686 -pipe -O2 -pipe -march=i686 -mfpmath=sse -mmmx -msse -msse2 -msse3 -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -clang-syntax -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables  -c ../../../../../../../../../mnt/host/source/src/platform2/buffet/webserv_client.cc -o obj/buffet/buffet_common.webserv_client.o
buffet-0.0.1-r1253: ../../../../../../../../../mnt/host/source/src/platform2/buffet/webserv_client.cc:86:25: error: allocating an object of abstract class type 'libwebserv::Server'
buffet-0.0.1-r1253:   web_server_.reset(new libwebserv::Server);

Patch-set: 2
Label: Commit-Queue=+1