Update patch set 1
Patch Set 1: -Code-Review

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1: Code-Review-1
> > > 
> > > Code under IS_ENABLED gets optimized away during link time. So as long as you don't have ifdefs on the definitions or prototypes, there is no reason to do this.
> > 
> > Maybe I didn't express the problem clearly, let me use fifo_disable in line 585 as the example. The fifo_disable function is defined when CONFIG_ACCEL_INTERRUPTS is defined. When using polling mode, the CONFIG_ACCEL_INTERRUPTS is undefined, so fifo_disable function is not defined. But the fifo_disable in line 585 is still compiled by the compiler and generate the function undefined error. This is what happens when I use polling mode for tgl rvp in another patch. Due to this coding problem, the currently driver misses the support for polling mode which must be fixed.
> 
> Remove the #ifdef on line 94...

I tried remove #ifdef CONFIG_ACCEL_INTERRUPTS on line 94 but it doesn't work. There are many errors during compilation, see below. For example, in line 144, the "current" member of lsm6dsm_data only defined when CONFIG_ACCEL_FIFO is defined while the CONFIG_ACCEL_INTERRUPTS and CONFIG_ACCEL_FIFO are undefined in the polling mode. So I think my current fix may be the appropriate one. 





driver/accelgyro_lsm6dsm.c: In function 'reset_load_fifo_sensor_state':
driver/accelgyro_lsm6dsm.c:44:7: error: 'struct lsm6dsm_data' has no member named 'load_fifo_sensor_state'
   data->load_fifo_sensor_state[i].int_timestamp = ts;
       ^~
driver/accelgyro_lsm6dsm.c:45:7: error: 'struct lsm6dsm_data' has no member named 'load_fifo_sensor_state'
   data->load_fifo_sensor_state[i].sample_count = 0;
       ^~
driver/accelgyro_lsm6dsm.c: In function 'fifo_reset_pattern':
driver/accelgyro_lsm6dsm.c:144:17: error: 'struct lsm6dsm_data' has no member named 'current'
  memcpy(&private->current, &private->config,
                 ^~
driver/accelgyro_lsm6dsm.c:144:36: error: 'struct lsm6dsm_data' has no member named 'config'
  memcpy(&private->current, &private->config,
                                    ^~
driver/accelgyro_lsm6dsm.c:146:9: error: 'struct lsm6dsm_data' has no member named 'next_in_patten'
  private->next_in_patten = FIFO_DEV_INVALID;
         ^~
driver/accelgyro_lsm6dsm.c: In function 'fifo_enable':
driver/accelgyro_lsm6dsm.c:198:9: error: 'struct lsm6dsm_data' has no member named 'config'
  private->config.total_samples_in_pattern = 0;
         ^~
driver/accelgyro_lsm6dsm.c:201:11: error: 'struct lsm6dsm_data' has no member named 'config'
    private->config.samples_in_pattern[i] =
           ^~
driver/accelgyro_lsm6dsm.c:205:11: error: 'struct lsm6dsm_data' has no member named 'config'
    private->config.total_samples_in_pattern +=
           ^~
driver/accelgyro_lsm6dsm.c:206:12: error: 'struct lsm6dsm_data' has no member named 'config'
     private->config.samples_in_pattern[i];
            ^~
driver/accelgyro_lsm6dsm.c:209:11: error: 'struct lsm6dsm_data' has no member named 'config'
    private->config.samples_in_pattern[i] = 0;
           ^~
driver/accelgyro_lsm6dsm.c: In function 'fifo_next':
driver/accelgyro_lsm6dsm.c:279:13: error: 'struct lsm6dsm_data' has no member named 'current'
  if (private->current.total_samples_in_pattern == 0)
             ^~
driver/accelgyro_lsm6dsm.c:282:13: error: 'struct lsm6dsm_data' has no member named 'current'
  if (private->current.total_samples_in_pattern == 0) {
             ^~
driver/accelgyro_lsm6dsm.c:291:24: error: 'struct lsm6dsm_data' has no member named 'next_in_patten'
  for (next_id = private->next_in_patten + 1; 1; next_id++) {
                        ^~
driver/accelgyro_lsm6dsm.c:294:14: error: 'struct lsm6dsm_data' has no member named 'current'
   if (private->current.samples_in_pattern[next_id] != 0) {
              ^~
driver/accelgyro_lsm6dsm.c:295:11: error: 'struct lsm6dsm_data' has no member named 'current'
    private->current.samples_in_pattern[next_id]--;
           ^~
driver/accelgyro_lsm6dsm.c:296:11: error: 'struct lsm6dsm_data' has no member named 'current'
    private->current.total_samples_in_pattern--;
           ^~
driver/accelgyro_lsm6dsm.c:297:11: error: 'struct lsm6dsm_data' has no member named 'next_in_patten'
    private->next_in_patten = next_id;
           ^~
driver/accelgyro_lsm6dsm.c: In function 'push_fifo_data':
driver/accelgyro_lsm6dsm.c:330:14: error: 'struct lsm6dsm_data' has no member named 'samples_to_discard'
   if (private->samples_to_discard[id] > 0) {
              ^~
driver/accelgyro_lsm6dsm.c:331:11: error: 'struct lsm6dsm_data' has no member named 'samples_to_discard'
    private->samples_to_discard[id]--;
           ^~
driver/accelgyro_lsm6dsm.c: In function 'load_fifo':
driver/accelgyro_lsm6dsm.c:367:15: error: 'FIFO_READ_LEN' undeclared (first use in this function); did you mean 'FIFO_DEV_NUM'?
  uint8_t fifo[FIFO_READ_LEN];
               ^~~~~~~~~~~~~
               FIFO_DEV_NUM
driver/accelgyro_lsm6dsm.c:367:15: note: each undeclared identifier is reported only once for each function it appears in
driver/accelgyro_lsm6dsm.c:367:10: error: unused variable 'fifo' [-Werror=unused-variable]
  uint8_t fifo[FIFO_READ_LEN];
          ^~~~
driver/accelgyro_lsm6dsm.c: In function 'handle_interrupt_for_fifo':
driver/accelgyro_lsm6dsm.c:441:10: error: 'CONFIG_ACCEL_LSM6DSM_INT_EVENT' undeclared (first use in this function)
          CONFIG_ACCEL_LSM6DSM_INT_EVENT, 0);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
driver/accelgyro_lsm6dsm.c: In function 'irq_handler':
driver/accelgyro_lsm6dsm.c:460:18: error: 'CONFIG_ACCEL_LSM6DSM_INT_EVENT' undeclared (first use in this function)
      (!(*event & CONFIG_ACCEL_LSM6DSM_INT_EVENT)))
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
driver/accelgyro_lsm6dsm.c: In function 'lsm6dsm_set_data_rate':
driver/accelgyro_lsm6dsm.c:631:11: error: 'struct lsm6dsm_data' has no member named 'samples_to_discard'
    private->samples_to_discard[s->type] =
           ^~
driver/accelgyro_lsm6dsm.c:633:11: error: 'struct lsm6dsm_data' has no member named 'load_fifo_sensor_state'
    private->load_fifo_sensor_state[get_fifo_type(s)]
           ^~
At top level:
driver/accelgyro_lsm6dsm.c:455:12: error: 'irq_handler' defined but not used [-Werror=unused-function]
 static int irq_handler(struct motion_sensor_t *s, uint32_t *event)
            ^~~~~~~~~~~
driver/accelgyro_lsm6dsm.c:101:12: error: 'config_interrupt' defined but not used [-Werror=unused-function]
 static int config_interrupt(const struct motion_sensor_t *accel)
            ^~~~~~~~~~~~~~~~
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile.rules:519: build/tglrvp_ish/RW/driver/accelgyro_lsm6dsm.o] Error 1

Patch-set: 1
Reviewer: Gerrit User 1333246 <1333246@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0