board/burnet: Fix enum type
"enum ec_led_colors" was used here instead of "enum led_color".

Fixes the following clang warning:

board/burnet/led.c:85:28: error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]
                rv = led_set_color_power(color);
                     ~~~~~~~~~~~~~~~~~~~ ^~~~~
board/burnet/led.c:112:23: error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]
                led_set_color_power(LED_WHITE);
                ~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~
board/burnet/led.c:115:25: error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]
                        (power_tick & 0x2) ? LED_WHITE : LED_OFF);
                                             ^~~~~~~~~
board/burnet/led.c:115:37: error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]
                        (power_tick & 0x2) ? LED_WHITE : LED_OFF);
                                                         ^~~~~~~
board/burnet/led.c:117:23: error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]
                led_set_color_power(LED_OFF);
                ~~~~~~~~~~~~~~~~~~~ ^~~~~~~

BRANCH=none
BUG=b:172020503
TEST=CC=arm-none-eabi-clang BOARD=burnet -j
TEST=./util/compare_build.sh -b all
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ie530c1cd3603652748349a65f80242694884f6b1