cr50: Disabling TPM or Locking TPM enabled.
New vendor commands are introduced to control TPM mode:
VENDOR_CC_ENABLE_TPM_MODE, and VENDOR_CC_DISABLE_TPM_MODE.
TPM mode is initially enabled, and can be locked as enabled or
disabled by either of those commands, and the value cannot be changed
until next TPM reset event.
The use case could be that Chrome OS might want to lock the TPM mode
as enabled. If Alt OS is to be booted, TPM should be disabled ahead.

For debugging purpose, VENDOR_CC_GET_TPM_MODE is defined as well.

BUG=b:77543596
BRANCH=cr50
TEST=manual

(chroot) ./extra/usb_updater/gsctool -h
Usage: gsctool [options] [<binary image>]
Options:
  -m,--tpm_mode [enable|disable]
                             Query or control tpm mode

(chroot) ./extra/usb_updater/gsctool -m
TPM_is enabled (0).

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(chroot) ./extra/usb_updater/gsctool -m enable

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(chroot) gsctool -m enable
Error 7 in enabling TPM.

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(dut) reboot

(chroot) ./extra/usb_updater/gsctool -m disable

(chroot) ./extra/usb_updater/gsctool -m
TPM_is disabled (2).

(dut) gsctool -a -i
Problems reading from TPM, got 10 bytes
Error: Failed to send vendor command 25

(dut) tpm-manager
[INFO:tpm_manager_v2.cc(51)]Initializing TPM.
[tpm_manager.TakeOwnershipReply] {
  status:STATUS_NOT_AVAILABLE
}

Change-Id: I1453d1a8d03f13cc7fc203863cbc50bf84c9dd8c
Signed-off-by: Namyoon Woo <namyoon@google.com>