Update patch set 8
Patch Set 8:

> Patch Set 8: Verified-1
> 
> most likely this caused the build breakage in cheza.  or one of the other related EC CLs.  please check.
> 
> chromeos-ec-0.0.1-r5389: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.2.0/../../../../arm-eabi/bin/ld: build/cheza/utils/RO/common/motion_sense.o: in function `motion_sense_task':
> chromeos-ec-0.0.1-r5389: /build/cheza/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5389/work/chromeos-ec-0.0.1/platform/ec/common/motion_sense.c:1029: undefined reference to `motion_als_sensors'

You're right, I can repro locally with emerge-cheza chromeos-ec [but not make BOARD=cheza].
I think the issue has been introduced by  https://chromium-review.googlesource.com/1460092, digging.

Patch-set: 8
Reviewer: Gerrit User 1104704 <1104704@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0