zephyr: console: add missing include for shell_uart.h
Fixes few compiler warnings:

/mnt/host/source/src/platform/ec/zephyr/shim/src/console.c:40:13: warning: implicit declaration of function 'shell_backend_uart_get_ptr'; did you mean 'log_backend_count_get'? [-Wimplicit-function-declaration]
(and others)

BUG=none
BRANCH=none
TEST=zmake -lDEBUG configure... no warnings

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Change-Id: I1bb9b9a691559f93ea8530d530f00e5348e92cec