ectool_keyscan: add missing null terminator to kbd_plain_xlate
strchr relies on the source string to be null terminated. This fixes a
compiler warning when building outside of the chroot:

util/ectool_keyscan.c: In function ‘cmd_keyscan’:
util/ectool_keyscan.c:208:9: error: ‘strchr’ argument missing terminating nul [-Werror=stringop-overflow=]
  208 |   pos = strchr(kbd_plain_xlate, key);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUG=none
TEST=build only, warning is gone
BRANCH=servo

Signed-off-by: Jeremy Bettis <jbettis@google.com>
Change-Id: I068779820876167a31076c69dfedb24f0f5e7ed6