oak: Fix a build error for boards other than rev5
There is a build error after commit 6877eee247250cb0e962ef8ddf1544aba4b75e6b

build/oak/RO/common/lid_angle.o: In function `enable_peripherals':
/build/oak/tmp/portage/chromeos-base/chromeos-ec-9999/work/
platform/ec/common/lid_angle.c:164:
undefined reference to `lid_angle_peripheral_enable'

Add BOARD_REV check for those configs added only for rev5.

BUG=chrome-os-partner:50720
BRANCH=none
TEST=build pass for oak from rev2

Change-Id: I663c509751c87174c1e4371961e281abc61ee4d8
Signed-off-by: Koro Chen <koro.chen@mediatek.com>