driver/charger: Remove unused functions
When building with clang it warns:

driver/charger/isl923x.c:116:34: error: unused function 'raw_read8'
[-Werror,-Wunused-function]
static inline enum ec_error_list raw_read8(int chgnum, int offset,
int *value)

driver/charger/isl923x.c:137:34: error: unused function 'raw_update16'
[-Werror,-Wunused-function]
static inline enum ec_error_list raw_update16(int chgnum, int offset,
int mask,

raw_update16 is only used in some configurations; remove ifdefs from
callers. raw_read8 is not used at all, so it is removed.

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=elm -j
TEST=make buildall -j

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Iaabdc5f4dfe8d6ad8a8ee5d157f284fff1ed676d