Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8871610074649282512
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: include/config.h:1
        Falling back to three-way merge...
        Applied patch to 'include/config.h' cleanly.
        error: patch failed: power/common.c:1
        Falling back to three-way merge...
        Applied patch to 'power/common.c' with conflicts.
        U power/common.c

Patch-set: 1
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1106949 \u003c1106949@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}