Update patch set 16
Patch Set 16:

> Patch Set 15: Verified-1
> 
> This patch cannot merge as is because it actively breaks juniper and jacuzzi's compilation. There might be other boards that have the IT8801 defined.
> 
> Even since patchset 15(i guess because it actually tries changing the gpio), you'll get a compilation error on juniper:
> /home/amstan/cros/src/platform/ec/driver/ioexpander/it8801.c:296: undefined reference to `ioex_config'
> 
> Probably because CONFIG_IO_EXPANDER is not defined. So the IO expander portion now needs to be added to every board that uses the keyboard controller. Ideally in the same patch or another CQ-Depended patch so the change is atomic and it doesn't break anyone's bisect (well, i guess it still would, but it would at least be well labeled).
> 
> Please make sure you run make build_all to check for cases like this in the future.

The board of kappa is also needed to define. 
After adding the define, run make build_all is completed successfully.
https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1677977/40

Patch-set: 16
Reviewer: Gerrit User 1273969 <1273969@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>