ocelotrvp: Configure an LED policy
Use the caps lock LED to show battery/charging information. Use this
because the EC AICs cannot access the normal charging status LED on the
RVP. The LED is visible left of the top of the 2x14 0.1" header on the
right side of the board.

LED codes:

Charging, <15%: slow blink LED (1500ms on / 500ms off)
Charging, >=15%: steady LED
Discharge, <15%: medium blink LED (1s on / 1s off)
Discharge, >=15%: LED off
Idle: LED pulse (900ms on / 100ms off)
Forced idle: LED pulse (100ms on / 900ms off)
Error: rapid flash LED at 250ms

BUG=b:399727242
TEST=zmake build ocelotrvo-ite, -npcx. Test on boards.

Change-Id: Iaef8954b2d99c7780553407fdf39e192616c9159