chip/stm32: remove unused variable
clang warns:

ip/stm32/usb_hid_keyboard.c:378:21: error: unused variable 'hid_current_buf'
[-Werror,-Wunused-variable]
static volatile int hid_current_buf;
                    ^

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I88b424cbc8930bf2d7d6c0856d81104cbd4d3561