include/ec_commands.h: Fix unaligned access warnings
When building with clang, it now warns if there is an unpacked struct
nested in a packed struct:

include/ec_commands.h:3053:4: error: field  within 'struct
ec_params_motion_sense::(unnamed at include/ec_commands.h:3044:3)' is
less aligned than 'union ec_params_motion_sense::(anonymous at
include/ec_commands.h:3053:4)' and is usually due to 'struct
ec_params_motion_sense::(unnamed at include/ec_commands.h:3044:3)' being
packed, which can lead to unaligned accesses
[-Werror,-Wunaligned-access]
                        union {
                        ^

See https://github.com/llvm/llvm-project/issues/55520.

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I5c89746d7e2e93183f4706376e6cda0be4589c01