zephyr: require ADC support for the charge manager
charge_manager.c includes adc.h, which depends on there existing a
definition of adc_t; when CONFIG_ADC is disabled (the default), there is
none and the charge manager fails to compile with a somewhat confusing
error:

> adc.h:25:27: error: array type has incomplete element type ‘struct adc_t’
> 25 | extern const struct adc_t adc_channels[];
>    |                           ^~~~~~~~~~~~

Because the charge manager can't build without ADC support, make it
select CONFIG_ADC so the required support is always enabled.

BUG=b:267959470
TEST=zmake compare-builds -a
BRANCH=none

Change-Id: I9cbc5b14a5e5a7f3307925c5bcd0da6e84b79758
Signed-off-by: Peter Marheine <pmarheine@chromium.org>