Update patch set 6
Patch Set 6:

Fixes undefined reference due to CONFIG_LPC:

common/acpi.c:277: error: undefined reference to 'lpc_query_host_event_state'
common/acpi.c:293: error: undefined reference to 'lpc_set_acpi_status_mask'

Patch-set: 6
Reviewer: Gerrit User 1127214 <1127214@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>