baseboard/zork: Unify enum types
enum ec_ssfc_base_gyro_sensor and enum ec_cfg_base_gyro_sensor_type have
the same values. clang warns that we're trying to convert between these
two types:

board/morphius/board.c:257:10: error: implicit conversion from
enumeration type 'enum ec_ssfc_base_gyro_sensor' to different
enumeration type 'enum ec_cfg_base_gyro_sensor_type'
[-Werror,-Wenum-conversion]
                return get_cbi_ssfc_base_sensor();

Rather than duplicate the type (and it accidentally getting out of
sync), just use the canonical base type.

BRANCH=none
BUG=b:172020503
TEST=./util/compare_builds.sh -b all -j 120
     => All match, except ezkinil due to the change of the
     base_gyro_config variable from "int" to "enum"

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I8168518a87469004c33adebed89879225c470ace