Update patch set 19
Patch Set 19:

does this patch depend on another patch?  i'm getting build errors:

chromeos-ec-9999: In file included from include/system.h:11,
chromeos-ec-9999:                  from chip/ish/gpio.c:12:
chromeos-ec-9999: core/minute-ia/atomic.h:31:17: error: inline function 'atomic_read_clear' declared but never defined [-Werror]
chromeos-ec-9999:  inline uint32_t atomic_read_clear(uint32_t volatile *addr);

Patch-set: 19