Update patch set 1
Patch Set 1:

The following build(s) failed:

peppy paladin: The UploadPrebuilts stage failed: ./upload_prebuilts failed (code=1) The Archive stage failed: 
Traceback (most recent call last):
  File "/b/cbuild/peppy-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/peppy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 2165, in BuildAndArchiveChromeSysroot
    cros_build_lib.RunCommand(cmd, cwd=self._build_root, enter_chroot=True)
  File "/b/cbuild/peppy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
Failed command "'cros_sdk' '--' 'cros_generate_sysroot' '--out-dir' '/home/chrome-bot/trunk/buildbot_archive/peppy-paladin/R29-4263.0.0-rc1' '--board' 'peppy' '--package' 'chromeos-base/chromeos-chrome'", cwd=/b/cbuild/peppy-paladin-bin-master, extra env=None
 in https://uberchromegw.corp.google.com/i/chromeos/builders/peppy%20paladin/builds/375

falco paladin: The UploadPrebuilts stage failed: ./upload_prebuilts failed (code=1) The Archive stage failed: 
Traceback (most recent call last):
  File "/b/cbuild/falco-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/falco-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 2165, in BuildAndArchiveChromeSysroot
    cros_build_lib.RunCommand(cmd, cwd=self._build_root, enter_chroot=True)
  File "/b/cbuild/falco-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
Failed command "'cros_sdk' '--' 'cros_generate_sysroot' '--out-dir' '/home/chrome-bot/trunk/buildbot_archive/falco-paladin/R29-4263.0.0-rc1' '--board' 'falco' '--package' 'chromeos-base/chromeos-chrome'", cwd=/b/cbuild/falco-paladin-bin-master, extra env=None
 in https://uberchromegw.corp.google.com/i/chromeos/builders/falco%20paladin/builds/382

slippy paladin: The UploadPrebuilts stage failed: ./upload_prebuilts failed (code=1) The Archive stage failed: 
Traceback (most recent call last):
  File "/b/cbuild/slippy-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/slippy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 2165, in BuildAndArchiveChromeSysroot
    cros_build_lib.RunCommand(cmd, cwd=self._build_root, enter_chroot=True)
  File "/b/cbuild/slippy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
Failed command "'cros_sdk' '--' 'cros_generate_sysroot' '--out-dir' '/home/chrome-bot/trunk/buildbot_archive/slippy-paladin/R29-4263.0.0-rc1' '--board' 'slippy' '--package' 'chromeos-base/chromeos-chrome'", cwd=/b/cbuild/slippy-paladin-bin-master, extra env=None
 in https://uberchromegw.corp.google.com/i/chromeos/builders/slippy%20paladin/builds/377

Your change may have caused this failure. There are also other changes that may be at fault: 33 other changes. See the blamelist for more details.

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1