Update patch set 1
Patch Set 1:

A trybot failed to apply your change in https://uberchromegw.corp.google.com/i/chromiumos.tryserver/builders/mixed-c-pre-cq/builds/8990 . CL:264763 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128
fatal: unable to access 'https://chromium-review.googlesource.com/chromiumos/platform/ec/': Failed to connect to chromium-review.googlesource.com port 443: Connection timed out

Failed command "git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/64/264764/1", cwd=/b/cbuild/internal_master/src/platform/ec, extra env=None
Traceback (most recent call last):
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/parallel.py", line 601, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/parallel.py", line 799, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/cbuildbot/validation_pool.py", line 747, in FetchChangesForRepo
    change.Fetch(repo)
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/patch.py", line 766, in Fetch
    print_cmd=True)
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/git.py", line 816, in RunGit
    ['git'] + cmd, **kwargs)
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/retry_util.py", line 71, in GenericRetry
    return functor(*args, **kwargs)
  File "/b/build/slave/mixed-c-pre-cq/build/chromite/lib/cros_build_lib.py", line 608, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128
fatal: unable to access 'https://chromium-review.googlesource.com/chromiumos/platform/ec/': Failed to connect to chromium-review.googlesource.com port 443: Connection timed out

Failed command "git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/64/264764/1", cwd=/b/cbuild/internal_master/src/platform/ec, extra env=None


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1
Reviewer: Gerrit User 1118934 <1118934@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0