Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8813338279874958465
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'zephyr/projects/skyrim/BUILD.py' cleanly.
        Falling back to direct application...
        Falling back to direct application...
        Falling back to direct application...
        Applied patch to 'zephyr/projects/skyrim/prj_skyrim.conf' cleanly.
        Falling back to direct application...
        error: patch failed: zephyr/projects/skyrim/pwm_leds.dts:1
        error: zephyr/projects/skyrim/pwm_leds.dts: patch does not apply

Patch-set: 4
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1513493 \u003c1513493@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: CQ full run failed."}