Update patch set 5
Patch Set 5:

does this patch require changes in some other repos?

I see this error when I try building Cr50 with this patch:

board/cr50/fips.c:372:2: error: implicit declaration of function 'u2f_zeroize' [-Werror=implicit-function-declaration]
  u2f_zeroize();

Patch-set: 5
Reviewer: Gerrit User 1000039 <1000039@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>