Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8865155015363712832
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: common/usb_pd_host_cmd.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usb_pd_host_cmd.c' with conflicts.
        U common/usb_pd_host_cmd.c

Patch-set: 1
Tag: autogenerated:cq:full-run