board/dirinboz,board/gumboz: Fix variable type
When building with clang, it warns:

board/dirinboz/led.c:47:6: error: implicit conversion from enumeration
type 'enum ioex_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                                 IOEX_C1_CHARGER_LED_AMBER_DB);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
board/dirinboz/led.c:49:6: error: implicit conversion from enumeration
type 'enum ioex_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                                 IOEX_C1_CHARGER_LED_WHITE_DB);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

The led variables are used as parameters to gpio_or_ioex_set_level,
which takes an int, so just use int so we don't have to cast between
types.

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I16428fbc5ef49f497a3514ac56049e8bd0e40d53