Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8877838825971289504
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: common/usbc/usb_pe_drp_sm.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usbc/usb_pe_drp_sm.c' with conflicts.
        error: patch failed: common/usbc/usb_tc_drp_acc_trysrc_sm.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usbc/usb_tc_drp_acc_trysrc_sm.c' cleanly.
        U common/usbc/usb_pe_drp_sm.c

Patch-set: 2
Tag: autogenerated:cq:full-run