Update patch set 6
Patch Set 6:

my guess is this broke the unittests

chromeos-ec-0.0.1-r5268: In file included from chip/host/system.c:17:
chromeos-ec-0.0.1-r5268: [1minclude/util.h:102:26: [0m[0;1;31merror: [0m[1mconflicting types for 'strtoul'[0m
chromeos-ec-0.0.1-r5268: __stdlib_compat uint64_t strtoul(const char *nptr, char **endptr, int base);
chromeos-ec-0.0.1-r5268: [0;1;32m                         ^
chromeos-ec-0.0.1-r5268: [0m[1m../../../../../../../../usr/include/stdlib.h:180:26: [0m[0;1;30mnote: [0mprevious declaration is here[0m
chromeos-ec-0.0.1-r5268: extern unsigned long int strtoul (const char *__restrict __nptr,
chromeos-ec-0.0.1-r5268: make[1]: *** [Makefile.rules:279: host-host_command_fuzz] Error 2

Patch-set: 6
CC: Gerrit User 1000768 <1000768@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>