Update patch set 2
Patch Set 2: Verified+1 Commit-Queue+1

The error in build is due to biod:

AssertionError: File dir-ROOT-A/opt/fpc/lib/libfpsensor.so.0 contains unsatisfied symbols: set(['fp_pal_get_timestamp', 'fp_pal_wait_for_sensor_interrupt', 'fp_pal_spi_writeread', 'fp_pal_spi_write', 'fp_pal_logprint'])

Patch-set: 2
Reviewer: Gerrit User 1104704 <1104704@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1
Label: Verified=+1