Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8806251280442216353
    Merge conflict detected! Please rebase and retry.
    
        error: patch fragment without header at line 21: @@ -1,8 +1,8 @@

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1314118 \u003c1314118@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: CQ full run failed."}