board/dratini: Fix LED enum type
"enum ec_led_colors" was used here instead of "enum led_color".

Fixes the following clang warning:

error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]

This is the same fix as commit 036cda45bba9fca0137add1d8693a264ba686d71.

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=dratini

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ide9188bef86b44041cf214405aee9461a3fbd917