Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8872126972918521616
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: driver/charger/sm5803.c:1
        Falling back to three-way merge...
        Applied patch to 'driver/charger/sm5803.c' with conflicts.
        U driver/charger/sm5803.c

Patch-set: 2
Tag: autogenerated:cq:full-run