Revert "ec: Prevent #undef or #define of zephyr Kconfigs"
This reverts commit 47161f4ecaf63221b2513f088ae0bc9cfdfecaad.

Reason for revert: broke CI, blocking a bunch of unrelated CLs with:

ERROR: Modifying CONFIG_RTC outside of #ifndef CONFIG_ZEPHYR not allowed at include/config.h:3841

Original change's description:
> ec: Prevent #undef or #define of zephyr Kconfigs
>
> Block all #undef or #define of Kconfigs in include/config.h. This will
> allow removing the #include <autoconf.h> from
> zephyr/shim/include/config_chip.h, which will in turn allow removing
> all of the #line directives we've sprinkled throughout the headers.
>
> BRANCH=None
> BUG=b:272518464
> TEST=make buildall_only -j$(nproc), fails before crrev/c/4396143
> TEST=CQ, fails before crrev/c/4396143, passes after
>
> Change-Id: I09649cf778e339fb45dc05c6ebdffc9aaa5778d2
> Signed-off-by: Jeremy Bettis <jbettis@google.com>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4396142
> Auto-Submit: Jeremy Bettis <jbettis@chromium.org>
> Reviewed-by: Keith Short <keithshort@chromium.org>
> Commit-Queue: Keith Short <keithshort@chromium.org>
> Tested-by: Jeremy Bettis <jbettis@chromium.org>

Bug: b:272518464
Change-Id: Iff8be5f1c581745401416b5e9e8bd8ceca0073c5