board/lazor: Move enum definition before its use
board/lazor/board.h:121:6:
error: ISO C++ forbids forward references to 'enum' types
enum battery_cell_type board_get_battery_cell_type(void);
     ^

BRANCH=none
BUG=b:144959033
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Id2abde06326a0fe9297b98127aa7ef6768ce1479
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2740564
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
(cherry picked from commit 8e8bc38d03ca4338955cc9478abb1e80358bbcae)