Update patch set 1
Patch Set 1:

The Commit Queue failed to apply your change in https://uberchromegw.corp.google.com/i/chromeos/builders/mario%20paladin/builds/13407 .  Patch victoryang:172380:131e8709:"Return hash status on HAST_START command" failed to apply due to a CQ issue: Unhandled Exception occurred during CQ's Apply: return code: 128
error: The requested URL returned error: 500 while accessing https://chromium.googlesource.com/a/chromiumos/platform/ec/info/refs?service=git-upload-pack
fatal: HTTP request failed

Failed command "'git' 'fetch' u'cros' 'refs/meta/config:refs/meta/config'", cwd=/b/cbuild/mario-paladin-bin-master/src/platform/ec, extra env=None
Failing the entire series to prevent CQ from going into an infinite loop hanging on these CLs.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1