common/util: Add casts
When compiling against the standard library, clang complains:

common/util.c:66:6: error: array subscript is of type 'char'
[-Werror,-Wchar-subscripts]
            tolower(*s) == 'f' || tolower(*s) == 'n') {
            ^~~~~~~~~~~

According to POSIX:

The tolower() and tolower_l() functions have as a domain a type int, the
value of which is representable as an unsigned char or the value of EOF.
If the argument has any other value, the behavior is undefined.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/tolower.html

BRANCH=none
BUG=b:234181908
TEST=make utils-str

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I84f4bfb647f29b24b1c3bd7f5d222275354c4698