board/woomax,board/morphius: Fix return type
clang warns:

board/morphius/board.c:406:8: error: implicit conversion from
enumeration type 'enum ioex_signal' to different enumeration type 'enum
gpio_signal'
[-Werror,-Wenum-conversion]
                                        ? IOEX_USB_C1_HPD_IN_DB
                                          ^~~~~~~~~~~~~~~~~~~~~

board/woomax/board.c:864:6: error: implicit conversion from enumeration
type 'enum ioex_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                        : IOEX_USB_C1_HPD_IN_DB;
                          ^~~~~~~~~~~~~~~~~~~~~

The only caller appears to be svdm_set_hpd_gpio() and
svdm_get_hpd_gpio(), which correctly calls gpio_or_ioex_set_level()
since the signal may be either gpio_signal or ioex_signal. Rename the
board_usbc_port* function to indicate that it can return gpio or ioex.

BRANCH=none
BUG=b:172020503
TEST=make buildall
TEST=CC=clang make BOARD=woomax
TEST=CC=clang make BOARD=morphius

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I7be75c8a714ba103362b293413aadc6a92ab72c3