compare_builds.sh: Add msg for git checkout failure
This is important when you have uncommited changes that
could be clobbered.

EXAMPLE OUTPUT
Failed to checkout c1592fff1:
error: Your local changes to the following files would be overwritten by checkout:
	Makefile.rules
Please commit your changes or stash them before you switch branches.
Aborting

BRANCH=none
BUG=none
TEST=# Modify a line of code near a change in HEAD
     ./util/compare_build.sh
Signed-off-by: Craig Hesling <hesling@chromium.org>
Change-Id: I7a341bd137caa8f77c3e744a177919f7109e2fd4