pdc_rts54xx: Fix compiler warning
When building with clang it warns:

zephyr/drivers/usbc/pdc_rts54xx.c:1581:14: error: result of comparison
of constant 256 with expression of type 'uint8_t' (aka 'unsigned char')
is always true [-Werror,-Wtautological-constant-out-of-range-compare]
 1581 |                 assert(len <= ARRAY_SIZE(data->wr_buf));
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use a compile-time check for bounds checking instead of a runtime check.

BUG=b:390722919
TEST=CQ

Change-Id: I87db5bf39d0e0240755edbe36d70623a44917cc2