Create patch set 6
Change has been successfully rebased and submitted as afc1b2f8795f614bb298b20d05962d1d37f6f820

4 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: util/build_with_clang.py
Insertions: 11, Deletions: 13.

@@ -44,7 +44,6 @@
     # git grep  --name-only 'CHIP:=stm32' | xargs grep -L 'CHIP_FAMILY:=stm32f0' | sed 's#board/\(.*\)/build.mk#"\1",#'
     "bland",
     "c2d2",
-    "chocodile_vpdmcu",
     "coffeecake",
     "dingdong",
     "discovery-stm32f072",
@@ -182,7 +181,6 @@
     "quackingstick",
     "rammus",
     "redrix",
-    "reef",
     "sasuke",
     "scout",
     "shuboz",
@@ -211,12 +209,6 @@
     # git grep --name-only 'CHIP:=mt_scp' | xargs grep -L 'CHIP_VARIANT:=mt818' | sed 's#board/\(.*\)/build.mk#"\1",#'
     "corsola_scp",
     "kukui_scp",
-    # i386
-    "adl_ish_lite",
-    "arcada_ish",
-    "drallion_ish",
-    "tglrvp_ish",
-    "volteer_ish",
 ]
 
 NDS32_BOARDS = [
@@ -268,6 +260,7 @@
     # Boards that use CHIP:=stm32 *and* CHIP_FAMILY:=stm32f0
     "burnet",  # overflows flash
     "cerise",  # overflows flash
+    "chocodile_vpdmcu",  # compilation error: b/254710459
     "damu",  # overflows flash
     "fennel",  # overflows flash
     "jacuzzi",  # overflows flash
@@ -280,6 +273,7 @@
     "kukui",  # overflows flash
     "makomo",  # overflows flash
     "oak",  # overflows flash
+    "reef",  # compilation error
     "servo_v4",  # overflows flash
     "stern",  # overflows flash
     "willow",  # overflows flash
@@ -297,6 +291,12 @@
     "terrador",  # overflows flash
     "volteer",  # overflows flash
     "waddledoo",  # overflows flash
+    # Boards that use CORE:=minute-ia
+    "adl_ish_lite",
+    "arcada_ish",
+    "drallion_ish",
+    "tglrvp_ish",
+    "volteer_ish",
 ]
 
 # TODO(b/201311714): NDS32 is not supported by LLVM.
@@ -333,11 +333,9 @@
 
 def check_boards() -> None:
     all_boards = get_all_boards()
-    diff = set(all_boards) ^ (
-        set(
-            BOARDS_THAT_COMPILE_SUCCESSFULLY_WITH_CLANG
-            + BOARDS_THAT_FAIL_WITH_CLANG
-        )
+    diff = set(all_boards) ^ set(
+        BOARDS_THAT_COMPILE_SUCCESSFULLY_WITH_CLANG
+        + BOARDS_THAT_FAIL_WITH_CLANG
     )
     if len(diff) > 0:
         print(
```


Patch-set: 6
Patch-set-description: Rebase
Subject: util/build_with_clang: Check all boards are accounted for
Status: merged
Commit: afc1b2f8795f614bb298b20d05962d1d37f6f820
Tag: autogenerated:gerrit:merged
Groups: fcf107bec19e4b5fb5a9f3ed07a85ce69a123958
Label: Code-Review=+2, f1f881ec167703cb4c4d2f652b598487e3f9a37b Gerrit User 1305927 <1305927@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, beb38b2ecfa1bfdf60461d73aea6117ae31a1875 Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=+1, beadc31481f1d42c99f99c4b33a8915e0bd27482 Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, 37366243d6d9daf5b51679c221fdc13eada40f9e
Submission-id: 3977108
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Code-Review: Gerrit User 1305927 <1305927@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Verified: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Feels
Submitted-with: MAY: Code-Coverage
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners