Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8795436762858626273) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    Applied patch to 'zephyr/Kconfig.led_dt' cleanly.
    Applied patch to 'zephyr/program/corsola/ite_program.conf' cleanly.
    Applied patch to 'zephyr/program/herobrine/program.conf' cleanly.
    Applied patch to 'zephyr/program/nissa/xivu/project.conf' cleanly.
    error: zephyr/program/rex/prj.conf: does not exist in index
    error: zephyr/program/skyrim/prj_crystaldrift.conf: does not exist in index
    error: zephyr/program/skyrim/prj_frostflow.conf: does not exist in index
    error: zephyr/program/skyrim/prj_morthal.conf: does not exist in index
    error: zephyr/program/skyrim/prj_skyrim.conf: does not exist in index
    error: zephyr/program/skyrim/prj_winterhold.conf: does not exist in index
    Applied patch to 'zephyr/program/trogdor/lazor/prj.conf' cleanly.
    Applied patch to 'zephyr/test/drivers/default/prj.conf' cleanly.
    Applied patch to 'zephyr/test/drivers/led_driver/prj.conf' cleanly.

Patch-set: 2
Tag: autogenerated:cq:full-run:1670414577
Attention: {"person_ident":"Gerrit User 1478788 \u003c1478788@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}