driver: Remove unused function
When compiling with clang it warns that the function is unused:

driver/accelgyro_lsm6dsm.c:45:29: error: unused function 'get_fifo_type'
[-Werror,-Wunused-function]
static inline enum dev_fifo get_fifo_type(const struct motion_sensor_t
*s)

BRANCH=none
BUG=b:172020503
TEST=make CC=clang V=1 BOARD=arcada_ish

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ibc52e25a2f750e8da8335e7835475db7a5d42670