Revert "flash_ec: remove sed or cut call in getting a value from dut-control"
This reverts commit 6a144d98d3d09c2beea3ae5002a371a4f71a23f0.

Reason for revert: Broke some dut-control invocations, see b/129425648. 

Original change's description:
> flash_ec: remove sed or cut call in getting a value from dut-control
> 
> BUG=none
> BRANCH=none
> TEST=manually ran flash_ec on coral, scarlet, and ampton.
> The test log is at gpaste/6202232963858432.
> 
>   $ ./util/flash_ec --board=coral --read ${IMG}
>   $ ./util/flash_ec --board=scarlet --read ${IMG} --bitbang_rate=57600
>   $ ./util/flash_ec --board=ampton --read ${IMG}
> 
> Tested with a EXPECT_TO_FAIL case with a line, dut_control_get xxxx
> 
>   $ ./util/flash_ec --board=scarlet --read ${IMG} --verbose
>   Problem with ['xxxx'] :: No control named "xxxx"
> 
>   ERROR: dut_control_get failed: dut-control --port=9999 xxxx
> 
> Tested with a board name in stm32_dfu, and checked dut_command_get
> is not called.
> 
>   $ ./util/flash_ec --board dingdong --image ${IMG} --verbose
>   INFO: Using a dedicated debug cable
>   INFO: Using toad.
>   INFO: Using ec image : /tmp/ec.read.bin
>   INFO: Flashing chip stm32_dfu.
>   INFO: Using dfu flasher : dfu-util
>   ...
> 
> Change-Id: Ib936cf450c3d12f0784ff1aaf3c33e9d18069606
> Signed-off-by: Namyoon Woo <namyoon@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/1524670
> Reviewed-by: Matthew Blecker <matthewb@chromium.org>

BUG=b:129425648

Change-Id: I6b03ebf5951b21883916ebf4f441a6a56cab4940