chip/npcx: Remove unused GPIO interrupt function
When the interrupt handlers are made static (see followup commits), the
compiler complains that this function is unused (there is no
corresponding DECLARE_IRQ):

chip/npcx/gpio-npcx9.c:182:15: error: '__gpio_wk2fg_interrupt' defined
but not used [-Werror=unused-function]
 GPIO_IRQ_FUNC(__gpio_wk2fg_interrupt, WUI_INT(MIWU_TABLE_2, MIWU_GROUP_6));

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I3f58cdcb9b2e113fb9dd079a3e157bf8336b71d5