Update patch set 1
Patch Set 1: Commit-Queue+1

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > NOTE: The Commit Queue will retry your change automatically.
> > 
> > The Commit Queue timed out while verifying your change in https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8936121721925633312 . This means that a supporting builder did not finish building your change within the specified timeout. The build failure may have been caused by infrastructure issues, so your change will not be blamed for the failure.
> > 
> > Commit queue documentation: https://dev.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview
> 
> Actually, a bunch of the failures were on the UnitTest stage for chromeos-ec. Now, it's surprising that unit tests would pass on PreCQ and fail on the CQ, so this might be a flake/false alarm, but can you double-check https://uberchromegw.corp.google.com/i/chromeos/builders/caroline-paladin/builds/4282/steps/UnitTest if the CQ run that started at 4:04p EST fails again in chromeos-ec unit tests?

It looks like the error is caused the below error, i don't think that error is caused by this patch:

chromeos-ec-0.0.1-r5086: [01m[Kdriver/tcpm/tusb422.c:49:3:[m[K [01;31m[Kerror: [m[K'[01m[Kconst struct tcpm_drv[m[K' has no member named '[01m[Kget_message[m[K'; did you mean '[01m[Kget_message_raw[m[K'?
chromeos-ec-0.0.1-r5086:   .[01;31m[Kget_message[m[K  = &tcpci_tcpm_get_message,
chromeos-ec-0.0.1-r5086:    [01;31m[K^~~~~~~~~~~[m[K
chromeos-ec-0.0.1-r5086:    [32m[Kget_message_raw[m[K
chromeos-ec-0.0.1-r5086: [01m[Kdriver/tcpm/tusb422.c:49:19:[m[K [01;31m[Kerror: [m[K'[01m[Ktcpci_tcpm_get_message[m[K' undeclared here (not in a function); did you mean '[01m[Ktcpci_tcpm_get_message_raw[m[K'?
chromeos-ec-0.0.1-r5086:   .get_message  = &[01;31m[Ktcpci_tcpm_get_message[m[K,
chromeos-ec-0.0.1-r5086:                    [01;31m[K^~~~~~~~~~~~~~~~~~~~~~[m[K
chromeos-ec-0.0.1-r5086:                    [32m[Ktcpci_tcpm_get_message_raw[m[K
chromeos-ec-0.0.1-r5086: make[2]: *** [Makefile.rules:431: build/dragonegg/RO/driver/tcpm/tusb422.o] Error 1
chromeos-ec-0.0.1-r5086: make[1]: *** [Makefile.rules:204: proj-dragonegg] Error 2
chromeos-ec-0.0.1-r5086: make[1]: *** Waiting for unfinished jobs....

Patch-set: 1
Reviewer: Gerrit User 1265046 <1265046@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1