Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> This failed in the CQ see:
> https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8911013729153020608/+/steps/UnitTest/0/stdout
> 
> I couldn't reproduce the failure doing:
> make -j56 BOARD=kindred
> 
> I am in the process of trying:
> ./setup_board --board=fizz
> cros_workon --board=fizz start chromeos-ec
> emerge-fizz chromeos-ec
> FEATURES=test emerge-fizz chromeos-ec
> 
> Here is the error:
> 
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:130:4: error: 'const struct tcpc_config_t' has no member named 'i2c_host_port'
> chromeos-ec-0.0.1-r5607:    .i2c_host_port = I2C_PORT_TCPC0,
> chromeos-ec-0.0.1-r5607:     ^~~~~~~~~~~~~
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:131:4: error: 'const struct tcpc_config_t' has no member named 'i2c_slave_addr'
> chromeos-ec-0.0.1-r5607:    .i2c_slave_addr = AN7447_TCPC0_I2C_ADDR,
> chromeos-ec-0.0.1-r5607:     ^~~~~~~~~~~~~~
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:128:68: error: missing braces around initializer [-Werror=missing-braces]
> chromeos-ec-0.0.1-r5607:  const struct tcpc_config_t tcpc_config[CONFIG_USB_PD_PORT_COUNT] = {
> chromeos-ec-0.0.1-r5607:                                                                     ^
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:136:4: error: 'const struct tcpc_config_t' has no member named 'i2c_host_port'
> chromeos-ec-0.0.1-r5607:    .i2c_host_port = I2C_PORT_TCPC1,
> chromeos-ec-0.0.1-r5607:     ^~~~~~~~~~~~~
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:137:4: error: 'const struct tcpc_config_t' has no member named 'i2c_slave_addr'
> chromeos-ec-0.0.1-r5607:    .i2c_slave_addr = PS8751_I2C_ADDR1,
> chromeos-ec-0.0.1-r5607:     ^~~~~~~~~~~~~~
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:128:68: error: missing braces around initializer [-Werror=missing-braces]
> chromeos-ec-0.0.1-r5607:  const struct tcpc_config_t tcpc_config[CONFIG_USB_PD_PORT_COUNT] = {
> chromeos-ec-0.0.1-r5607:                                                                     ^
> chromeos-ec-0.0.1-r5607: board/kindred/board.c:128:68: error: missing braces around initializer [-Werror=missing-braces]

Those constants are defined in the baseboard, which is set as hatch in board/kindred/build.mk

Patch-set: 1
Reviewer: Gerrit User 1327490 <1327490@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0