Update patch set 5
Patch Set 5:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8879381440347545264
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/hatch_fp/board.c:1
        Falling back to three-way merge...
        Applied patch to 'board/hatch_fp/board.c' cleanly.
        error: patch failed: common/fpsensor/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'common/fpsensor/build.mk' with conflicts.
        error: patch failed: common/fpsensor/fpsensor.c:1
        Falling back to three-way merge...
        Applied patch to 'common/fpsensor/fpsensor.c' cleanly.
        U common/fpsensor/build.mk

Patch-set: 5
Tag: autogenerated:cq:dry-run