audio_codec: fix compile error
Fixes compile error:
error: initialization of 'int (*)(struct host_cmd_handler_args *)'
from incompatible pointer type 'enum ec_status
(*)(struct host_cmd_handler_args *)'
[-Werror=incompatible-pointer-types]

Commit 83d793839 ("host_command: Change host command return value
to enum ec_status") changes return code to enum ec_status for host
commands.  Changes the function pointers accordingly.

BRANCH=none
BUG=chromium:1004831
BUG=b:123268236
TEST=make BOARD=kukui_scp clean && make BOARD=kukui_scp -j

Change-Id: I8d38cbd732746b3fc0098b22d1faa2f04716d275
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>