clang: Fix unused function warning
get_interrupt_context is only called from code inside #ifdef
CONFIG_TASK_PROFILING.

core/cortex-m/task.c:238:19: error: unused function
'get_interrupt_context' [-Werror,-Wunused-function]
static inline int get_interrupt_context(void)

BRANCH=none
BUG=chromium:931797
TEST=make buildall -j

Change-Id: I5ba68d1a58a966eeecb5abdb3cb87fa2684f359b
Signed-off-by: Tom Hughes <tomhughes@chromium.org>