Update patch set 1
Patch Set 1: Commit-Queue+2

> Patch Set 1:
> 
> I don't know why the CQ bot says that this CL passed dry run.
> 
> It looks like this change does indeed create a legitimate include issue for biod and powerd. They both look like the following:
> 
> [2/27] CXX obj/biod/libbiod.cros_fp_firmware.o[K
> biod-0.0.1-r1580: FAILED: obj/biod/libbiod.cros_fp_firmware.o 
> biod-0.0.1-r1580: x86_64-cros-linux-gnu-clang++ -MMD -MF obj/biod/libbiod.cros_fp_firmware.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Igen/include -I../../../biod-0.0.1 -I/build/nami/usr/include -Wall -Wunused -Wno-c99-designator -Wno-unused-parameter -Wunreachable-code -ggdb3 -fstack-protector-strong -Wformat=2 -fvisibility=internal -Wa,--noexecstack -Wimplicit-fallthrough -Werror --sysroot=/build/nami -fPIE -DUSE_RTTI_FOR_TYPE_TAGS -pthread -Wno-unused-local-typedefs -DBASE_VER=462023 -pthread -I/build/nami/usr/include/chromeos -I/build/nami/usr/include/base-462023 -I/build/nami/usr/include/glib-2.0 -I/build/nami/usr/lib64/glib-2.0/include -I/build/nami/usr/include/nss -I/build/nami/usr/include/nspr -I/build/nami/usr/include/dbus-1.0 -I/build/nami/usr/lib64/dbus-1.0/include -I/build/nami/usr/include/power_manager-client -std=gnu++14 -DVCSID=\"0.0.1-r1580-236bfb33057a48e121d676be008baa9644e67567\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -O2 -pipe -march=corei7 -g -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -c ../../../biod-0.0.1/biod/cros_fp_firmware.cc -o obj/biod/libbiod.cros_fp_firmware.o
> biod-0.0.1-r1580: In file included from ../../../biod-0.0.1/biod/cros_fp_firmware.cc:14:
> biod-0.0.1-r1580: /build/nami/usr/include/chromeos/ec/ec_commands.h:14:10: fatal error: 'vb21_struct.h' file not found
> biod-0.0.1-r1580: #include "vb21_struct.h"
> biod-0.0.1-r1580:          ^~~~~~~~~~~~~~~
> biod-0.0.1-r1580: 1 error generated.
> biod-0.0.1-r1580:

That must be from the next CL in the chain (since it added that header). I'll re-run with just this CL.

Patch-set: 1
Reviewer: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2