chip/mt_scp: Declaration needs to come before definition
We are already disabling -Wignored-attributes to work around the
declaration and definition order issue:

error: attribute declaration must precede
definition [-Werror,-Wignored-attributes]

However, although there are no compiler errors, the linker (lld) will
still fail:

ld.lld: error: undefined symbol: clock_control_irq
>>> referenced by clock.c:347
(src/platform/ec/chip/mt_scp/mt8183/clock.c:347)
>>>               lto.tmp:(irq_13_handler)

...

ld.lld: error: undefined symbol: clock_fast_wakeup_irq
>>> referenced by clock.c:355
(src/platform/ec/chip/mt_scp/mt8183/clock.c:355)
>>>               lto.tmp:(irq_44_handler)

Tested with the compare_build.sh script to validate that the resulting
binaries are identical.

BRANCH=none
BUG=b:172020503
TEST=CC=arm-none-eabi-clang make BOARD=kukui_scp -j
TEST=./util/compare_build.sh --boards all -j 50

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ib622fb98784a4c3ad3c199c72ee7604c7f709d6c