zephyr/test/fingerprint: Make sure initializer fits in array
The terminating null adds an extra byte, so the C++ compiler complains:

zephyr/test/fingerprint/task/src/fpsensor_init.cc:36:11: error:
initializer-string for char array is too long, array size is 32 but
initializer has size 33 (including the null terminating character)
   36 |                 .seed = "very_secret_32_bytes_of_tpm_seed",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zephyr/test/fingerprint/task/src/fpsensor_init.cc:66:11: error:
initializer-string for char array is too long, array size is 32 but
initializer has size 33 (including the null terminating character)
   66 |                 .seed = "very_secret_32_bytes_of_tpm_seed",
      |

BUG=b:286119221
TEST=./twister -T zephyr/test/fingerprint -c

Change-Id: I7fdf42ab1acaadf16db2d9801bd6cfbd5f449fd7