ectool: add support for lightbar
Adds lightbar option to ectool led command.

BUG=b:440339256
TEST=ectool led light off
         Bad LED name: light
         Valid LED names: battery power adapter left right recovery_hwreinit sysrq debug lightbar
     ectool lightbar
         EC result 1 (INVALID_COMMAND)
         warning: ectool lightbar is depricated. Use ectool led lightbar instead.
     ectool led lightbar query
         EC result 3 (INVALID_PARAM)
         Brightness range for LED 7:
         Error: Unsupported LED.
The DUT doesn't actually have a lightbar so the last error is expected.

Change-Id: I6117cfe3f2bcbd941d4917a44d8f9f16419a39c9