Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8877102548911733696
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/morphius/board.c:1
        Falling back to three-way merge...
        Applied patch to 'board/morphius/board.c' with conflicts.
        U board/morphius/board.c

Patch-set: 4
Tag: autogenerated:cq:full-run