cr50: Disabling TPM or enabling TPM.
New vendor command, VENDOR_CC_SET_TPM_ODE is introduced, which modifies
TPM mode as enabled or as disabled. Once TPM mode is set, then it cannot
be altered to another value until TPM gets reset. After TPM gets disabled,
any TPM commands shall be disregarded as if TPM didn't exist.

This adds 136 bytes in binary.

BUG=b:77543596
BRANCH=cr50
TEST=manually

(chroot) ./extra/usb_updater/gsctool -h
Usage: gsctool [options] [<binary image>]
Options:
  -m,--tpm_mode [enable|disable]
                               Query or control tpm mode

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(chroot) ./extra/usb_updater/gsctool -m enable

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(chroot) gsctool -m enable
Error 7 in enabling TPM.

(dut) gsctool -a -i
Board ID space: XXXXXXXX:XXXXXXXX:XXXXXXXX

(dut) reboot

(chroot) ./extra/usb_updater/gsctool -m disable

(dut) gsctool -a -i
Problems reading from TPM, got 10 bytes
Error: Failed to send vendor command 25

(dut) tpm-manager
[INFO:tpm_manager_v2.cc(51)]Initializing TPM.
[tpm_manager.TakeOwnershipReply] {
  status:STATUS_NOT_AVAILABLE
}

Change-Id: I1453d1a8d03f13cc7fc203863cbc50bf84c9dd8c
Signed-off-by: Namyoon Woo <namyoon@google.com>