Reland "aleena: Add detect accel/gyro sensor in HOOK_INIT"
This reverts commit e5fa7fc82639d619b7a53db6b8b94117c857014e.

Reason for revert: Add include "adc.h" to fix build error. Need this change when sysjump rw and make sure ec get correct sku_id from adc.

Original change's description:
> Revert "aleena: Add detect accel/gyro sensor in HOOK_INIT"
>
> This reverts commit 103e253e60bb6e37278eb13ac880f172d6941358.
>
> Reason for revert: build fails on firmware-grunt-11031.B branch:
> board/aleena/board.c:163:204: error: 'HOOK_PRIO_INIT_ADC' undeclared here (not in a function)
>
> Original change's description:
> > aleena: Add detect accel/gyro sensor in HOOK_INIT
> >
> > Add detect accel/gyro sensor in HOOK_INIT for sysjump rw.
> > Use "HOOK_PRIO_INIT_ADC + 2" For sku_id checking.
> > And make sure detect sensor when chipset power on.
> >
> > BUG=none
> > BRANCH=grunt
> > TEST=sysjump ro/rw to check motionsense data.
> >
> > Signed-off-by: David Huang <david.huang@quanta.corp-partner.google.com>
> >
> > Change-Id: I143cde2ab3028ec5658acd16fdb6ec6aae710ef6
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2655305
> > Tested-by: David Huang <david.huang@quanta.corp-partner.google.com>
> > Auto-Submit: David Huang <david.huang@quanta.corp-partner.google.com>
> > Reviewed-by: YH Lin <yueherngl@chromium.org>
> > Reviewed-by: Keith Short <keithshort@chromium.org>
> > Commit-Queue: David Huang <david.huang@quanta.corp-partner.google.com>
> > (cherry picked from commit 8801fd7768c8b8436bd0282af71cdd449257c08a)
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2662223
> > Commit-Queue: Keith Short <keithshort@chromium.org>
>
> Bug: none
> Change-Id: I2cf8d24b2a41f715293b4a08ef11833e2320ce73
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2674380
> Reviewed-by: Edward Hill <ecgh@chromium.org>
> Commit-Queue: Edward Hill <ecgh@chromium.org>
> Tested-by: Edward Hill <ecgh@chromium.org>

Bug: none
Change-Id: Ic981032a15ec87ec611fd62ccc7bc9c8996cde66