ish/ish5: fix 64bit/32bit division compile error in function host_command_get_uptime_info
When enabled CONFIG_CMD_AP_RESET_LOG, compile error caused by 64bit/32bit division:
/opt/coreboot-sdk/lib/gcc/i386-elf/8.2.0/../../../../i386-elf/bin/ld: build/arcada_ish/RO/common/chipset.o: in function
`host_command_get_uptime_info':
/home/test/trunk/src/platform/ec/common/chipset.c:94: undefined reference to `__udivdi3'
collect2: error: ld returned 1 exit status
make: *** [Makefile.rules:457: build/arcada_ish/RO/ec.RO.elf] Error 1

Change-Id: I554e4c79f017e098ab83972928376f82fe7b92d1