util: introduce uart stress tester
This script repeats a console command on target UARTs, and collects the
output. It checks whether there are any lost characters or patterns are
corrupted.

Cq-Depend: chromium:1584967, chromium:1586642
BUG=b:131340067
BRANCH=None
TEST=manually ran this script on bob.
$ ./util/uart_stress_tester.sh --help
usage: ./util/uart_stress_tester.sh [flags]
flags:
  --[no]cr50:  Test cr50 console (default: false)
  --[no]ec:  Test ec console (default: false)
  --[no]cpu:  Test cpu (AP) console (default: false)
  --[no]verbose:  Print more messages (default: false)
  --[no]clean:  Delete all log data after test (default: false)
  --cr50_pty:  CR50 UART device, e.g. /dev/ttyUSB0 (default: '')
  --ec_pty:  EC UART device, e.g. /dev/ttyUSB1 (default: '')
  --cpu_pty:  CPU UART device, e.g. /dev/ttyUSB2 (default: '')
  -h,--[no]help:  show this help (default: false)

(with servod)
$ ./util/uart_stress_tester.sh --cr50 --ec --cpu
INFO: ChromeOS UART stress test starts.
INFO:
INFO: servo_type:ccd_cr50
INFO: ec_chip:npcx_spi
INFO: ec_board:bob
INFO: cr50_version:0.4.16/DBG/cr50_v2.0.1303+630592631
INFO: CR50 PTY= /dev/pts/13
INFO:   EC PTY= /dev/pts/19
INFO:  CPU PTY= /dev/pts/21
INFO:
INFO: Stress test on 1 UART(s), CR50 starts
...

(without servod)
$ ./util/uart_stress_tester.sh --cr50 --ec --cpu
INFO: ChromeOS UART stress test starts.
INFO:
INFO:     iConfiguration          3 DBG/cr50_v2.0.1303+630592631
INFO: CR50 PTY= /dev/ttyUSB0
INFO:   EC PTY= /dev/ttyUSB2
INFO:  CPU PTY= /dev/ttyUSB1
INFO:
ERROR: get_sample_txt_cat: Not implemented yet. Run servod and retry
DEBUG: Test files are in /tmp/uart_stress_tester.sh_latest

Change-Id: Iedd8c9a62e089fde8894ee93329ee9f4a31bb3e7
Signed-off-by: Namyoon Woo <namyoon@chromium.org>