WIP: gitlab: Add posix-ec
Add this board so we get coverage on gitlab.

Sadly this does not work:

from /home/zephyr/zephyr/arch/posix/core/offsets/offsets.c:26:
/usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h:
   No such file or directory
 #include <bits/libc-header-start.h>

BUG=b:178731498
BRANCH=none
TEST=try on gitlab

Change-Id: I27dab970650d5e705d0f04f5b0e9096b0ae25cec
Signed-off-by: Simon Glass <sjg@chromium.org>