btle_ll.c: Initialize variables to fix GCC 5.3 warnings
It looks like the variable offset really should have been initialized
for the first data packet, so this may fix a real issue.

common/btle_ll.c: In function 'connected_communicate':
common/btle_ll.c:729:15: error: 'offset' may be used uninitialized
in this function [-Werror=maybe-uninitialized]

The variable last_rx_time shouldn't be able to be used without being
initialized, so just initialize it to make GCC 5.3 happy.

common/btle_ll.c: In function 'bluetooth_ll_task':
common/btle_ll.c:835:25: error: 'last_rx_time' may be used uninitialized
in this function [-Werror=maybe-uninitialized]

BRANCH=none
BUG=none
TEST=build succeeds under GCC 5.3 and 4.9.2

Change-Id: Ib3882aab3e081afc4b00dc02b002ba4c590cb0f9
Signed-off-by: Martin Roth <martinroth@chromium.org>