util: Add unused attribute to unused function
When compiling with C++, it complains this function is unused:

util/iteflash.cc:170:12: error: unused function
'spi_flash_command_short' [-Werror,-Wunused-function]
static int spi_flash_command_short(struct common_hnd *chnd, uint8_t cmd,
           ^

BUG=b:303185818
TEST=make BOARD=host utils

Change-Id: I911c9389200f80e7e8a75f73bbd4ace185270c14