Update patch set 2
Patch Set 2:

This change broke the EC build for Octopus. I've confirmed that reverting fixes the build error.

chromeos-ec-0.0.1-r5528: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.3.0/../../../../arm-eabi/bin/ld: build/bobba/pingpong/RW/board/bobba/board.o: in function `board_update_sensor_config_from_sku':
chromeos-ec-0.0.1-r5528: /build/octopus/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5528/work/chromeos-ec-0.0.1/platform/ec/board/bobba/board.c:278: undefined reference to `keyboard_cols'
chromeos-ec-0.0.1-r5528: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.3.0/../../../../arm-eabi/bin/ld: build/bobba/mutex/RW/board/bobba/board.o: in function `board_update_sensor_config_from_sku':
chromeos-ec-0.0.1-r5528: /build/octopus/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5528/work/collect2: error: ld returned 1 exit status
chromeos-ec-0.0.1-r5528: chromeos-ec-0.0.1/platform/ec/board/bobba/board.c:278: undefined reference to `keyboard_cols'
chromeos-ec-0.0.1-r5528: collect2: error: ld returned 1 exit status
chromeos-ec-0.0.1-r5528: make[1]: *** [Makefile.rules:454: build/bobba/mutex/RW/mutex.RW.elf] Error 1
chromeos-ec-0.0.1-r5528: make[1]: *** Waiting for unfinished jobs....
chromeos-ec-0.0.1-r5528: make[1]: *** [Makefile.rules:454: build/bobba/pingpong/RW/pingpong.RW.elf] Error 1
chromeos-ec-0.0.1-r5528: make[1]: *** Waiting for unfinished jobs....

Patch-set: 2
Reviewer: Gerrit User 1115020 <1115020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>