usbc_ppc: fix build by moving ppc_prints() function to header
When running emerge-octopus chromeos-ec command, build fails because of
undefined reference to ppc_prints(). This patch moves ppc_prints and
ppc_prints_err to header file.

BUG=none
BRANCH=none
TEST=emerge-octopus chromeos-ec

Signed-off-by: Patryk Duda <pdk@semihalf.com>
Change-Id: I90177292865b335d292716bfbca4becdd2372289