Update patch set 27
Patch Set 27: Verified-1

https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8903627933182594448/+/steps/install_packages/0/steps/call_chromite.api.SysrootService_InstallPackages/0/steps/call_build_API_script/0/stdout

FAILED: obj/power_manager/powerd/system/libsystem.wake_on_dp_configurator.o 
  x86_64-cros-linux-gnu-clang++ -MMD -MF obj/power_manager/powerd/system/libsystem.wake_on_dp_configurator.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_BUFFET=true -Igen/include -I../../../power_manager-0.0.2 -I/build/amd64-generic/usr/include -Wall -Wunused -Wno-unused-parameter -Wunreachable-code -ggdb3 -fstack-protector-strong -Wformat=2 -fvisibility=internal -Wa,--noexecstack -Wimplicit-fallthrough -Werror --sysroot=/build/amd64-generic -fPIE -DUSE_RTTI_FOR_TYPE_TAGS -pthread -Wno-unused-local-typedefs -DBASE_VER=462023 -pthread -I/build/amd64-generic/usr/include/chromeos -I/build/amd64-generic/usr/include/base-462023 -I/build/amd64-generic/usr/include/glib-2.0 -I/build/amd64-generic/usr/lib64/glib-2.0/include -I/build/amd64-generic/usr/include/nss -I/build/amd64-generic/usr/include/nspr -I/build/amd64-generic/usr/include/dbus-1.0 -I/build/amd64-generic/usr/lib64/dbus-1.0/include -I/build/amd64-generic/usr/include/chromeos -std=gnu++14 -DVCSID=\"0.0.2-r3128-2617f00881f2c53b7ebe6c103f4165845e3b67ef\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -O2 -pipe -march=x86-64 -msse3 -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -c ../../../power_manager-0.0.2/power_manager/powerd/system/wake_on_dp_configurator.cc -o obj/power_manager/powerd/system/libsystem.wake_on_dp_configurator.o
  In file included from ../../../power_manager-0.0.2/power_manager/powerd/system/wake_on_dp_configurator.cc:10:
  In file included from ../../../power_manager-0.0.2/power_manager/powerd/system/cros_ec_ioctl.h:12:
  In file included from ../../../../../../../../usr/include/chromeos/ec/cros_ec_dev.h:11:
  ../../../../../../../../usr/include/chromeos/ec/ec_commands.h:4676:22: error: types cannot be declared in an anonymous union
                  struct __ec_align1 ec_param_ec_codec_dmic_set_gain {
                                     ^
  ../../../../../../../../usr/include/chromeos/ec/ec_commands.h:4723:22: error: types cannot be declared in an anonymous union
                  struct __ec_align1 ec_param_ec_codec_i2s_rx_set_sample_depth {
                                     ^
  ../../../../../../../../usr/include/chromeos/ec/ec_commands.h:4728:22: error: types cannot be declared in an anonymous union
                  struct __ec_align1 ec_param_ec_codec_i2s_rx_set_daifmt {
                                     ^
  ../../../../../../../../usr/include/chromeos/ec/ec_commands.h:4733:22: error: types cannot be declared in an anonymous union
                  struct __ec_align4 ec_param_ec_codec_i2s_rx_set_bclk {
                                     ^
  4 errors generated.

Patch-set: 27
Reviewer: Gerrit User 1129199 <1129199@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1