Update patch set 2
Patch Set 2:

The following build(s) failed:

pre-cq-group: The UploadTestArtifacts [rambi] stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
Copying file:///b/cbuild/internal_master/trybot_archive/trybot-rambi-pre-cq/R39-6215.0.0-b30815/stateful.tgz [Content-Type=application/x-gzip]...
==> NOTE: You are uploading one or more large file(s), which would run
significantly faster if you enable parallel composite uploads. This
feature can be enabled by editing the
"parallel_composite_upload_threshold" value in your .boto
configuration file. However, note that if you do this you and any
users that download such composite files will need to have a compiled
crcmod installed (see "gsutil help crcmod").

Uploading   ...t-rambi-pre-cq/R39-6215.0.0-b30815/stateful.tgz:  0 B/176.96 MB    Unable to find the server at www.googleapis.com
CommandException: 1 files/objects could not be transferred.

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.5.tar.gz/gsutil/gsutil -o 'GSUtil:parallel_composite_upload_threshold=0' -o 'Boto:num_retries=10' -m cp -- /b/cbuild/internal_master/trybot_archive/trybot-rambi-pre-cq/R39-6215.0.0-b30815/stateful.tgz gs://chromeos-image-archive/trybot-rambi-pre-cq/R39-6215.0.0-b30815/stateful.tgz", cwd=None, extra env={'BOTO_CONFIG': '/b/build/site_config/.boto'} in https://uberchromegw.corp.google.com/i/chromiumos.tryserver/builders/pre-cq-group/builds/30815

The build failure may have been caused by infrastructure issues and/or bad chromite changes.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 2