test/timer: Disable compiler warning when building with clang
When building with clang, we get the following warning:

test/timer.cc:35:6: error: attribute 'error' is already applied with
different arguments [-Werror,-Wignored-attributes]
   35 |         if (IS_ENABLED(BASEBOARD_HELIPILOT)) {
      |             ^

This warning is triggered because the IS_ENABLED() macro references
IS_ENABLED_BAD_ARGS(), which has an error attribute with a message that
includes the name of the config being used. The test/timer.cc file uses
both IS_ENABLED(BASEBOARD_HELIPILOT) and
IS_ENABLED(CONFIG_COMMON_TIMER), so there are two different error
strings used.

BUG=b:332378804
TEST=make run-timer

Change-Id: Ieda760ff376441d02c1b3aab3f69afe6fa8397fa