power: Combine chipset_reset_reason and chipset_shutdown_reason
When building with clang, it warns:

power/amd_x86.c:59:18: error: implicit conversion from enumeration type
'enum chipset_reset_reason' to different enumeration type 'enum
chipset_shutdown_reason' [-Werror,-Wenum-conversion]
        report_ap_reset(reason);

The two enums are already set up so that they don't overlap, so just
combine them into a single enum.

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => All boards match, except:
     burnet cerise damu fennel jacuzzi juniper kakadu kappa katsu kodama
     krane kukui makomo stern willow

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I47620e59e02a84c04dde4469f36ad37dccbcd9e5