Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8828445891756881665
    Merge conflict detected! Please rebase and retry.
    
        error: battery.c: does not exist in index
        error: cannot read the current contents of 'battery.c'
        Falling back to direct application...
        Applied patch to 'board/taniks/battery.c' cleanly.
        Applied patch to 'board/taniks/board.c' cleanly.
        Applied patch to 'board/taniks/board.h' cleanly.
        Applied patch to 'board/taniks/build.mk' cleanly.
        Falling back to direct application...
        Applied patch to 'board/taniks/charger.c' with conflicts.
        Applied patch to 'board/taniks/ec.tasklist' cleanly.
        Applied patch to 'board/taniks/fans.c' cleanly.
        Applied patch to 'board/taniks/fw_config.c' cleanly.
        Applied patch to 'board/taniks/fw_config.h' cleanly.
        Falling back to direct application...
        Applied patch to 'board/taniks/gpio.inc' cleanly.
        Applied patch to 'board/taniks/i2c.c' cleanly.
        Applied patch to 'board/taniks/keyboard.c' cleanly.
        Applied patch to 'board/taniks/led.c' cleanly.
        Applied patch to 'board/taniks/pwm.c' cleanly.
        Applied patch to 'board/taniks/sensors.c' cleanly.
        Falling back to direct application...
        Applied patch to 'board/taniks/usbc_config.c' cleanly.
        Applied patch to 'board/taniks/usbc_config.h' cleanly.
        U board/taniks/charger.c

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1520957 \u003c1520957@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ full run failed."}