make i2c_handle_sda_irq() static to fix GCC 5.3 warning
GCC 5.3 and 6.2 complain about the the i2c_irqs array being defined as
static because it's used by a non-static inline function.  Since
i2c_handle_sda_irq is only used in the i2c.c file, make it static as
well.

chip/npcx/i2c.c:462:22: error: 'i2c_irqs' is static but used in inline
function 'i2c_handle_sda_irq' which is not static [-Werror]
task_disable_irq(i2c_irqs[controller]);

This reduces the size of 70392 npcx_evb/RW/ec.RW.flat and
npcx_evb_arm/RW/ec.RW.flat by 20 bytes each.

BUG=none
BRANCH=none
TEST=make buildall passes under GCC 4.9.2, 5.3 and 6.2

Change-Id: I79691bb57083fd925f9c4be06de706f676a1d043
Signed-off-by: Martin Roth <martinroth@chromium.org>