core/cortex-m0: Function only used when CONFIG_TASK_PROFILING is defined
When compiling with clang, it warns:

core/cortex-m0/task.c:182:19: error: unused function 'get_interrupt_context'
[-Werror,-Wunused-function]
static inline int get_interrupt_context(void)

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I914a2a8f950a340c570f5d105859a80be3efb82a