Update patch set 5
Patch Set 5:

When EC tests is run there is conflict with assert.h which was being included in common/nvmem.c . This include was no longer needed by common/nvmem.c and was removed in patch set 5. Including the build error here for reference.

chromeos-ec-0.0.1-r3040: In file included from include/util.h:15:0,
chromeos-ec-0.0.1-r3040:                  from common/nvmem.c:13:
chromeos-ec-0.0.1-r3040: ./builtin/assert.h:42:0: error: "assert" redefined [-Werror]
chromeos-ec-0.0.1-r3040:  #define assert(x...) ASSERT(x)
chromeos-ec-0.0.1-r3040:  ^
chromeos-ec-0.0.1-r3040:   CC      RO/core/host/timer.o
chromeos-ec-0.0.1-r3040:   CC      RO/common/switch.o
chromeos-ec-0.0.1-r3040:   CC      RO/test/charge_ramp.o
chromeos-ec-0.0.1-r3040: In file included from common/nvmem.c:6:0:
chromeos-ec-0.0.1-r3040: /usr/include/assert.h:85:0: note: this is the location of the previous definition
chromeos-ec-0.0.1-r3040:  # define assert(expr)       \
chromeos-ec-0.0.1-r3040:  ^
chromeos-ec-0.0.1-r3040:   CC      RO/common/system.o
chromeos-ec-0.0.1-r3040:   CC      RO/common/test_util.o
chromeos-ec-0.0.1-r3040:   CC      RO/common/uart_buffering.o
chromeos-ec-0.0.1-r3040:   CC      RO/common/util.o
chromeos-ec-0.0.1-r3040: cc1: all warnings being treated as errors
chromeos-ec-0.0.1-r3040:   CC      RO/common/version.o

Patch-set: 5