Update patch set 1
Patch Set 1:

The build error is caused by:
ec-devutils-0.0.2-r4375: touchpad_updater.c:18:10: fatal error: 'libusb.h' file not found
ec-devutils-0.0.2-r4375: #include <libusb.h>
ec-devutils-0.0.2-r4375:          ^~~~~~~~~~
ec-devutils-0.0.2-r4375: 1 error generated.

Patch-set: 1
Reviewer: Gerrit User 1265046 <1265046@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>