Create patch set 5
Change has been successfully rebased and submitted as e0c62a6524a691b01c0454559af6f678169a6c24

3 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: util/build_with_clang.py
Insertions: 1, Deletions: 1.

@@ -27,12 +27,12 @@
     # Boards that use CHIP:=stm32 and *not* CHIP_FAMILY:=stm32f0
     # git grep  --name-only 'CHIP:=stm32' | xargs grep -L 'CHIP_FAMILY:=stm32f0' | sed 's#board/\(.*\)/build.mk#"\1",#'
     "baklava",
-    # "bellis", # overflows flash
+    # "bellis",
     "discovery",
     "gingerbread",
     "hatch_fp",
     "hyperdebug",
-    # "munna", # overflows flash
+    # "munna",
     "nocturne_fp",
     "nucleo-f411re",
     "nucleo-g431rb",
@@ -48,7 +48,7 @@
     # "burnet",  # overflows flash
     "c2d2",
     # "cerise",  # overflows flash
-    "chocodile_vpdmcu",
+    # "chocodile_vpdmcu",  # compilation error: b/254710459
     "coffeecake",
     # "damu",  # overflows flash
     "dingdong",
@@ -77,7 +77,7 @@
     "minimuffin",
     "moonball",
     "nucleo-f072rb",
-    "oak",
+    # "oak",  # overflows flash
     "pdeval-stm32f072",
     "plankton",
     "prism",
@@ -97,10 +97,10 @@
     "zinger",
     # Boards that use CHIP:=mchp
     # git grep --name-only 'CHIP:=mchp' | sed 's#board/\(.*\)/build.mk#"\1",#'
-    # "adlrvpp_mchp1521", # compilation errors
-    # "adlrvpp_mchp1727", # compilation errors
-    # "mchpevb1", # compilation errors
-    # "reef_mchp", # compilation errors
+    # "adlrvpp_mchp1521",
+    # "adlrvpp_mchp1727",
+    # "mchpevb1",
+    # "reef_mchp",
     # Boards that use CHIP:=max32660
     # git grep --name-only 'CHIP:=max32660' | sed 's#board/\(.*\)/build.mk#"\1",#'
     "max32660-eval",
@@ -153,8 +153,8 @@
     "fleex",
     "foob",
     "gaelin",
-    # "garg", # overflows flash
-    # "gelarshie", # overflows flash
+    # "garg",
+    # "gelarshie",
     "genesis",
     "gimble",
     "grunt",
@@ -189,12 +189,12 @@
     "moonbuggy",
     "morphius",
     "mrbland",
-    # "mushu", # overflows flash
+    # "mushu",
     "nami",
     "nautilus",
     "nightfury",
     "nipperkin",
-    # "nocturne", # overflows flash
+    # "nocturne",
     "npcx7_evb",
     "npcx9_evb",
     "npcx_evb",
@@ -211,7 +211,7 @@
     "quackingstick",
     "rammus",
     "redrix",
-    "reef",
+    # "reef",
     "sasuke",
     "scout",
     "shuboz",
@@ -219,7 +219,7 @@
     "stryke",
     "taeko",
     "taniks",
-    # "terrador", # overflows flash
+    # "terrador",
     "treeya",
     "trembyle",
     "trogdor",
@@ -228,14 +228,13 @@
     "voema",
     "volet",
     "volmar",
-    # "volteer", # overflows flash
+    # "volteer",
     "volteer_npcx797fc",
     "voxel",
     "voxel_ecmodeentry",
     "voxel_npcx797fc",
-    # "waddledoo", # overflows flash
+    # "waddledoo",
     "waddledoo2",
-    "whiskers",
     "woomax",
     "wormdingler",
     "yorp",
```


Patch-set: 5
Patch-set-description: Rebase
Subject: util/build_with_clang: Add more boards that compile
Status: merged
Commit: e0c62a6524a691b01c0454559af6f678169a6c24
Tag: autogenerated:gerrit:merged
Groups: 3e5faba66a45c1f15bd0bc5a5b49e84053dd6b56
Label: Code-Review=+2, 1de1b603ac23f32aea7d950060005b73deff71d0 Gerrit User 1308749 <1308749@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, d717ae984fd72bb0caa8ee1881fc1038a9e41b2a Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=+1, 7dcbfc7f225c22096931d7ff8faf431435b311d2 Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, d10ae5720aea5f5d903d631bc400bd8078e93c2c
Submission-id: 3975945
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Code-Review: Gerrit User 1308749 <1308749@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Verified: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Feels
Submitted-with: MAY: Code-Coverage
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners