include/host_command.h: Fix C++ compilation error
include/host_command.h:277:41: error: invalid suffix on literal; C++11
requires a space between literal and identifier
[-Wreserved-user-defined-literal]
        __attribute__((section(".rodata.hcmds."EXPANDSTR(0x0000, command)))) \
                                               ^

BRANCH=none
BUG=b:234181908
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I7428c6bf5fa6aa0c9440ae44d665f7d744d23c00