Update patch set 3
Patch Set 3:

Since you apparently ignored my request before, I'll run the upload hooks for you:

        Errors:
            * checkpatch.pl errors/warnings
            
            ERROR: code indent should use tabs where possible
            #64: FILE: board/minnie/battery.c:30:
            +        int temp;$
            
            WARNING: please, no spaces at the start of a line
            #64: FILE: board/minnie/battery.c:30:
            +        int temp;$
            
            ERROR: code indent should use tabs where possible
            #68: FILE: board/minnie/battery.c:32:
            +        if (!(batt->flags & BATT_FLAG_BAD_TEMPERATURE))$
            
            WARNING: please, no spaces at the start of a line
            #68: FILE: board/minnie/battery.c:32:
            +        if (!(batt->flags & BATT_FLAG_BAD_TEMPERATURE))$
            
            ERROR: that open brace { should be on the previous line
            #68: FILE: board/minnie/battery.c:32:
            +        if (!(batt->flags & BATT_FLAG_BAD_TEMPERATURE))
            +        {
            
            ERROR: code indent should use tabs where possible
            #69: FILE: board/minnie/battery.c:33:
            +        {$
            
            WARNING: please, no spaces at the start of a line
            #69: FILE: board/minnie/battery.c:33:
            +        {$
            
            ERROR: code indent should use tabs where possible
            #70: FILE: board/minnie/battery.c:34:
            +                temp = DECI_KELVIN_TO_CELSIUS(batt->temperature);$
            
            WARNING: please, no spaces at the start of a line
            #70: FILE: board/minnie/battery.c:34:
            +                temp = DECI_KELVIN_TO_CELSIUS(batt->temperature);$
            
            ERROR: code indent should use tabs where possible
            #73: FILE: board/minnie/battery.c:36:
            +                if (temp < 0)$
            
            WARNING: please, no spaces at the start of a line
            #73: FILE: board/minnie/battery.c:36:
            +                if (temp < 0)$
            
            ERROR: that open brace { should be on the previous line
            #73: FILE: board/minnie/battery.c:36:
            +                if (temp < 0)
            +                {
            
            ERROR: code indent should use tabs where possible
            #74: FILE: board/minnie/battery.c:37:
            +                {$
            
            WARNING: please, no spaces at the start of a line
            #74: FILE: board/minnie/battery.c:37:
            +                {$
            
            ERROR: code indent should use tabs where possible
            #75: FILE: board/minnie/battery.c:38:
            +                        batt->desired_voltage = 4350;$
            
            WARNING: please, no spaces at the start of a line
            #75: FILE: board/minnie/battery.c:38:
            +                        batt->desired_voltage = 4350;$
            
            ERROR: code indent should use tabs where possible
            #76: FILE: board/minnie/battery.c:39:
            +                        batt->desired_current = 0;$
            
            WARNING: please, no spaces at the start of a line
            #76: FILE: board/minnie/battery.c:39:
            +                        batt->desired_current = 0;$
            
            ERROR: code indent should use tabs where possible
            #77: FILE: board/minnie/battery.c:40:
            +                        batt->flags |= BATT_FLAG_BAD_ANY;$
            
            WARNING: please, no spaces at the start of a line
            #77: FILE: board/minnie/battery.c:40:
            +                        batt->flags |= BATT_FLAG_BAD_ANY;$
            
            ERROR: code indent should use tabs where possible
            #78: FILE: board/minnie/battery.c:41:
            +                }$
            
            WARNING: please, no spaces at the start of a line
            #78: FILE: board/minnie/battery.c:41:
            +                }$
            
            ERROR: trailing whitespace
            #79: FILE: board/minnie/battery.c:42:
            +                else if (temp < 12) $
            
            ERROR: code indent should use tabs where possible
            #79: FILE: board/minnie/battery.c:42:
            +                else if (temp < 12) $
            
            WARNING: please, no spaces at the start of a line
            #79: FILE: board/minnie/battery.c:42:
            +                else if (temp < 12) $
            
            ERROR: that open brace { should be on the previous line
            #79: FILE: board/minnie/battery.c:42:
            +                else if (temp < 12) 
            +                {
            
            ERROR: else should follow close brace '}'
            #79: FILE: board/minnie/battery.c:42:
            +                }
            +                else if (temp < 12) 
            
            ERROR: code indent should use tabs where possible
            #80: FILE: board/minnie/battery.c:43:
            +                {$
            
            WARNING: please, no spaces at the start of a line
            #80: FILE: board/minnie/battery.c:43:
            +                {$
            
            ERROR: code indent should use tabs where possible
            #81: FILE: board/minnie/battery.c:44:
            +                        batt->desired_voltage = 4350;$
            
            WARNING: please, no spaces at the start of a line
            #81: FILE: board/minnie/battery.c:44:
            +                        batt->desired_voltage = 4350;$
            
            ERROR: code indent should use tabs where possible
            #82: FILE: board/minnie/battery.c:45:
            +                        batt->desired_current = 1500;$
            
            WARNING: please, no spaces at the start of a line
            #82: FILE: board/minnie/battery.c:45:
            +                        batt->desired_current = 1500;$
            
            ERROR: code indent should use tabs where possible
            #83: FILE: board/minnie/battery.c:46:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            WARNING: please, no spaces at the start of a line
            #83: FILE: board/minnie/battery.c:46:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            ERROR: code indent should use tabs where possible
            #84: FILE: board/minnie/battery.c:47:
            +                }$
            
            WARNING: please, no spaces at the start of a line
            #84: FILE: board/minnie/battery.c:47:
            +                }$
            
            ERROR: trailing whitespace
            #85: FILE: board/minnie/battery.c:48:
            +                else if (temp < 50) $
            
            ERROR: code indent should use tabs where possible
            #85: FILE: board/minnie/battery.c:48:
            +                else if (temp < 50) $
            
            WARNING: please, no spaces at the start of a line
            #85: FILE: board/minnie/battery.c:48:
            +                else if (temp < 50) $
            
            ERROR: that open brace { should be on the previous line
            #85: FILE: board/minnie/battery.c:48:
            +                else if (temp < 50) 
            +                {
            
            ERROR: else should follow close brace '}'
            #85: FILE: board/minnie/battery.c:48:
            +                }
            +                else if (temp < 50) 
            
            ERROR: code indent should use tabs where possible
            #86: FILE: board/minnie/battery.c:49:
            +                {$
            
            WARNING: please, no spaces at the start of a line
            #86: FILE: board/minnie/battery.c:49:
            +                {$
            
            ERROR: code indent should use tabs where possible
            #87: FILE: board/minnie/battery.c:50:
            +                        batt->desired_voltage = 4350;$
            
            WARNING: please, no spaces at the start of a line
            #87: FILE: board/minnie/battery.c:50:
            +                        batt->desired_voltage = 4350;$
            
            ERROR: code indent should use tabs where possible
            #88: FILE: board/minnie/battery.c:51:
            +                        batt->desired_current = 3500;$
            
            WARNING: please, no spaces at the start of a line
            #88: FILE: board/minnie/battery.c:51:
            +                        batt->desired_current = 3500;$
            
            ERROR: code indent should use tabs where possible
            #89: FILE: board/minnie/battery.c:52:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            WARNING: please, no spaces at the start of a line
            #89: FILE: board/minnie/battery.c:52:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            ERROR: code indent should use tabs where possible
            #90: FILE: board/minnie/battery.c:53:
            +                }$
            
            WARNING: please, no spaces at the start of a line
            #90: FILE: board/minnie/battery.c:53:
            +                }$
            
            ERROR: trailing whitespace
            #91: FILE: board/minnie/battery.c:54:
            +                else if (temp < 55) $
            
            ERROR: code indent should use tabs where possible
            #91: FILE: board/minnie/battery.c:54:
            +                else if (temp < 55) $
            
            WARNING: please, no spaces at the start of a line
            #91: FILE: board/minnie/battery.c:54:
            +                else if (temp < 55) $
            
            ERROR: that open brace { should be on the previous line
            #91: FILE: board/minnie/battery.c:54:
            +                else if (temp < 55) 
            +                {
            
            ERROR: else should follow close brace '}'
            #91: FILE: board/minnie/battery.c:54:
            +                }
            +                else if (temp < 55) 
            
            ERROR: code indent should use tabs where possible
            #92: FILE: board/minnie/battery.c:55:
            +                {$
            
            WARNING: please, no spaces at the start of a line
            #92: FILE: board/minnie/battery.c:55:
            +                {$
            
            ERROR: code indent should use tabs where possible
            #93: FILE: board/minnie/battery.c:56:
            +                        batt->desired_voltage = 4110;$
            
            WARNING: please, no spaces at the start of a line
            #93: FILE: board/minnie/battery.c:56:
            +                        batt->desired_voltage = 4110;$
            
            ERROR: code indent should use tabs where possible
            #94: FILE: board/minnie/battery.c:57:
            +                        batt->desired_current = 3500;$
            
            WARNING: please, no spaces at the start of a line
            #94: FILE: board/minnie/battery.c:57:
            +                        batt->desired_current = 3500;$
            
            ERROR: code indent should use tabs where possible
            #95: FILE: board/minnie/battery.c:58:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            WARNING: please, no spaces at the start of a line
            #95: FILE: board/minnie/battery.c:58:
            +                        batt->flags |= BATT_FLAG_WANT_CHARGE;$
            
            ERROR: code indent should use tabs where possible
            #96: FILE: board/minnie/battery.c:59:
            +                }$
            
            WARNING: please, no spaces at the start of a line
            #96: FILE: board/minnie/battery.c:59:
            +                }$
            
            ERROR: code indent should use tabs where possible
            #97: FILE: board/minnie/battery.c:60:
            +                else$
            
            WARNING: please, no spaces at the start of a line
            #97: FILE: board/minnie/battery.c:60:
            +                else$
            
            ERROR: that open brace { should be on the previous line
            #97: FILE: board/minnie/battery.c:60:
            +                else
            +                {
            
            ERROR: else should follow close brace '}'
            #97: FILE: board/minnie/battery.c:60:
            +                }
            +                else
            
            ERROR: code indent should use tabs where possible
            #98: FILE: board/minnie/battery.c:61:
            +                {$
            
            WARNING: please, no spaces at the start of a line
            #98: FILE: board/minnie/battery.c:61:
            +                {$
            
            ERROR: code indent should use tabs where possible
            #99: FILE: board/minnie/battery.c:62:
            +                        batt->desired_voltage = 4110;$
            
            WARNING: please, no spaces at the start of a line
            #99: FILE: board/minnie/battery.c:62:
            +                        batt->desired_voltage = 4110;$
            
            ERROR: code indent should use tabs where possible
            #100: FILE: board/minnie/battery.c:63:
            +                        batt->desired_current = 0;$
            
            WARNING: please, no spaces at the start of a line
            #100: FILE: board/minnie/battery.c:63:
            +                        batt->desired_current = 0;$
            
            ERROR: code indent should use tabs where possible
            #101: FILE: board/minnie/battery.c:64:
            +                        batt->flags |= BATT_FLAG_BAD_ANY;$
            
            WARNING: please, no spaces at the start of a line
            #101: FILE: board/minnie/battery.c:64:
            +                        batt->flags |= BATT_FLAG_BAD_ANY;$
            
            ERROR: code indent should use tabs where possible
            #102: FILE: board/minnie/battery.c:65:
            +                }$
            
            WARNING: please, no spaces at the start of a line
            #102: FILE: board/minnie/battery.c:65:
            +                }$
            
            ERROR: code indent should use tabs where possible
            #103: FILE: board/minnie/battery.c:66:
            +        }$
            
            WARNING: please, no spaces at the start of a line
            #103: FILE: board/minnie/battery.c:66:
            +        }$
            
            total: 48 errors, 35 warnings, 101 lines checked
            
            NOTE: whitespace errors detected, you may wish to use scripts/cleanpatch or
                  scripts/cleanfile
            
            NOTE: Ignored message types: MSLEEP VOLATILE
            
            Your patch has style problems, please review.
            
            If any of these errors are false positives, please report
            them to the maintainer, see CHECKPATCH in MAINTAINERS.
            
            * Hook script "util/presubmit_check.sh 2>&1" failed with code 1:
              Files have changed since last time unit tests passed:
                /b/tip/src/platform/ec/board/minnie/battery.c
                /b/tip/src/platform/ec/board/minnie/board.h
              Please run "make buildall -j".

Please fix.

Patch-set: 3