gsctool: Add command to get console logs.
Add '-l' command to fetch GSC console logs and print them to stdsout.

BUG=b:268396021
TEST=localhost ~ # gsctool -aDl
Valid CCD config found
CCD_MODE:      deasserted
AP RO verification result: setting unprovisioned
PLT_RST_L DEASSERTED
WARNING: with `AllowUnverifiedRo` disabled EC will be kept in reset in
future Ti50 versions
Unverified AP RO allowed
ERROR: failed to retrieve key ladder state, setting to dev
libtpm initialized
Deferring NV write.
Deferring NV write.
Servo: debouncing -> disconnected
Starting erase

Change-Id: I59db7ebba0517d89900f31451b0d919712d2c564
Signed-off-by: Brian Granaghan <granaghan@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4266190
Reviewed-by: Mary Ruthven <mruthven@chromium.org>
(cherry picked from commit 78c483d9c9303354a2ff4b15f4939951fd8a6eff)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4482195
Auto-Submit: Mary Ruthven <mruthven@chromium.org>
Commit-Queue: Mary Ruthven <mruthven@chromium.org>
Reviewed-by: Jett Rink <jettrink@chromium.org>
Tested-by: Mary Ruthven <mruthven@chromium.org>
(cherry picked from commit c341055675bf25f232e4fb673d819adbd77ec69c)