Update patch set 1
Patch Set 1:

Did not pass `make buildall` due to broken of hadoken
hadoken V=
make obj=/mnt/host/source/src/platform/ec/build/cr50/tpm2 EMBEDDED_MODE=1 OBJ_PREFIX=Tpm2_ -C /mnt/host/source/src/third_party/tpm2
make[3]: '/mnt/host/source/src/platform/ec/build/cr50/tpm2/libtpm2.a' is up to date.
make obj=/mnt/host/source/src/platform/ec/build/cr50/cryptoc SUPPORT_UNALIGNED=1 \
	CONFIG_UPTO_SHA512=y -C /mnt/host/source/src/third_party/cryptoc
make[3]: '/mnt/host/source/src/platform/ec/build/cr50/cryptoc/libcryptoc.a' is up to date.
  CC      RO/chip/g/dcrypto/sha256.o
In file included from chip/g/dcrypto/dcrypto.h:15:0,
                 from chip/g/dcrypto/sha256.c:6:
chip/g/dcrypto/internal.h:18:28: fatal error: cryptoc/sha384.h: No such file or directory
 #include "cryptoc/sha384.h"
                            ^
compilation terminated.
make[2]: *** [Makefile.rules:304: build/cr50/RO/chip/g/dcrypto/sha256.o] Error 1
make[1]: *** [Makefile.rules:124: proj-cr50] Error 2
make[1]: *** Waiting for unfinished jobs....
  OBJCOPY RO/ec.RO.flat
  OBJCOPY RW/ec.RW.flat
  CAT     ec.obj
  OBJCOPY ec.bin
  COPY_RW ec.bin
  MV      ec.bin
make[1]: Leaving directory '/mnt/host/source/src/platform/ec'
make: *** [Makefile.rules:101: buildall] Error 2

Patch-set: 1
Label: Code-Review=0