aes-gcm: Fix unused error for kSizeTWithoutLower4Bits
This fixes the following compiler error when CORE_CORTEX_M is not set.

 common/aes-gcm.c:101:21: error: unused variable 'kSizeTWithoutLower4Bits' [-Werror,-Wunused-const-variable]
 static const size_t kSizeTWithoutLower4Bits = (size_t) -16;

This occurs when compiling the host-based unit and fuzzer tests.
The trace for this goes as follows:
Setting CORE_CORTEX_M sets GHASH_ASM, which later on sets GHASH.
Certain sections of code that use this static const are
disabled if GHASH is not set.
Thus, no uses of this static const.

This issue arose when attempting to add the fpsensor task to
host_command_fuzz, but is actually present(and unreported)
in the fpsensor unit test.
The presence of this unreported issue in the host-fpsensor build target
was discovered by manually invoking cpp for aes-gcm.c and checking that
the static const existed, but was not references.

BRANCH=none
BUG=none
TEST=make buildall -j

Change-Id: I2ef5d73e11ced421d888221ef3c672e42bba53a3
Signed-off-by: Craig Hesling <hesling@chromium.org>