DO NOT SUBMIT: board/woomax, board/morphius: Add cast
clang warns:

board/morphius/board.c:406:8: error: implicit conversion from
enumeration type 'enum ioex_signal' to different enumeration type 'enum
gpio_signal'
[-Werror,-Wenum-conversion]
                                        ? IOEX_USB_C1_HPD_IN_DB
                                          ^~~~~~~~~~~~~~~~~~~~~

board/woomax/board.c:864:6: error: implicit conversion from enumeration
type 'enum ioex_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                        : IOEX_USB_C1_HPD_IN_DB;
                          ^~~~~~~~~~~~~~~~~~~~~

If the code that is calling this expects a gpio_signal, this may not
behave correctly when we return an ioex_signal. The caller should call
gpio_or_ioex_set_level() to handle this.

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I7be75c8a714ba103362b293413aadc6a92ab72c3