Update patch set 3
Patch Set 3:

A trybot failed to apply your change in http://cros-goldeneye/chromeos/healthmonitoring/buildDetails?buildbucketId=8945622103529154576 . CL:1070989 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: None; command: git log '--pretty=format:%H%x00%T%x00%s%x00%B%x00%ce%x00%cn' -n1 9ac01c365de9b74d47f1faa061e8cacf9db2d202
[Errno 2] No such file or directory: '/b/swarming/w/ir/cache/cbuild/repository/src/platform/ec'
Traceback (most recent call last):
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/parallel.py", line 603, in TaskRunner
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/parallel.py", line 801, in <lambda>
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/cbuildbot/patch_series.py", line 142, in _FetchChangesForRepo
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/patch.py", line 963, in HasBeenFetched
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/patch.py", line 901, in _PullData
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/git.py", line 808, in RunGit
  File "/b/swarming/w/ir/cache/cbuild/repository/chromite/lib/cros_build_lib.py", line 670, in RunCommand
RunCommandError: return code: None; command: git log '--pretty=format:%H%x00%T%x00%s%x00%B%x00%ce%x00%cn' -n1 9ac01c365de9b74d47f1faa061e8cacf9db2d202
[Errno 2] No such file or directory: '/b/swarming/w/ir/cache/cbuild/repository/src/platform/ec'


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 3
CC: Gerrit User 1104224 <1104224@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>