Fix EC build for latest llvm for nyan_big board
Mark host command structures as aligned for nyan_big board.
Without marking as aligned, llvm was correctly complaining about
taking address of packed member.

util/ectool.c:1158 error: taking address of packed member 'size' of
class or structure 'ec_params_usb_pd_fw_update' may result in an
unaligned pointer value [-Werror,-Waddress-of-packed-member]

This is same change as
https://chromium-review.googlesource.com/#/c/413108/
This change will not be required if arm/aarch64 boards have this value
set (https://crbug.com/668259).

BRANCH=none
BUG=chromium:665240
TEST=Builds now

Change-Id: I194c4c5c750636deebacf176d5709864c5e2f74e