Update patch set 1
Patch Set 1:

A trybot failed to apply your change in https://luci-milo.appspot.com/buildbot/chromiumos.tryserver/reef-no-vmtest-pre-cq/103953 . CL:630056 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/56/630056/1
fatal: The remote end hung up upon initial contact

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/ec', u'refs/changes/56/630056/1'], cwd=/b/c/cbuild/repository/src/platform/ec
Traceback (most recent call last):
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 602, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 800, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/c/cbuild/repository/chromite/cbuildbot/patch_series.py", line 138, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/c/cbuild/repository/chromite/lib/git.py", line 820, in RunGit
    ['git'] + cmd, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 243, in GenericRetry
    return _run()
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 176, in _Wrapper
    ret = func(*args, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 242, in _run
    return functor(*args, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/cros_build_lib.py", line 645, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/56/630056/1
fatal: The remote end hung up upon initial contact

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/ec', u'refs/changes/56/630056/1'], cwd=/b/c/cbuild/repository/src/platform/ec


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1
CC: Gerrit User 1104224 <1104224@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>