Update patch set 11
Patch Set 11:

The Commit Queue failed to apply your change in http://cros-goldeneye/chromeos/healthmonitoring/buildDetails?buildbucketId=8948227670087677536 . CL:905923 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/tast-tests
fatal: remote error: Git repository not found

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/tast-tests'], cwd=/b/c/cbuild/repository/src/platform/tast-tests
Traceback (most recent call last):
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 603, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 801, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/c/cbuild/repository/chromite/cbuildbot/patch_series.py", line 139, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/c/cbuild/repository/chromite/lib/git.py", line 808, in RunGit
    return cros_build_lib.RunCommand(['git'] + cmd, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/cros_build_lib.py", line 658, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/tast-tests
fatal: remote error: Git repository not found

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/tast-tests'], cwd=/b/c/cbuild/repository/src/platform/tast-tests

<class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/crosvm
fatal: remote error: Git repository not found

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/crosvm'], cwd=/b/c/cbuild/repository/src/platform/crosvm
Traceback (most recent call last):
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 603, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 801, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/c/cbuild/repository/chromite/cbuildbot/patch_series.py", line 139, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/c/cbuild/repository/chromite/lib/git.py", line 808, in RunGit
    return cros_build_lib.RunCommand(['git'] + cmd, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/cros_build_lib.py", line 658, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/crosvm
fatal: remote error: Git repository not found

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/crosvm'], cwd=/b/c/cbuild/repository/src/platform/crosvm


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 11