Update patch set 66
Patch Set 66:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8785656924700634113) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    Applied patch to 'common/fpsensor/fpsensor_state.cc' with conflicts.
    Applied patch to 'include/ec_commands.h' with conflicts.
    error: test/fpsensor_state.cc: does not exist in index

Patch-set: 66
Tag: autogenerated:cq:dry-run:1679741355
Attention: {"person_ident":"Gerrit User 1293547 \u003c1293547@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#66: Tryjobs failed"}