Update patch set 1
Patch Set 1: Verified-1 Code-Review-1

This causes a compile time failure in the master branch.

board/nightfury/board.c:13:10: fatal error: driver/accel_lis2ds.h: No such file or directory
 #include "driver/accel_lis2ds.h"
          ^~~~~~~~~~~~~~~~~~~~~~~

Patch-set: 1
Reviewer: Gerrit User 1273086 <1273086@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=-1
Label: Verified=-1