Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8867772219903517408
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: common/usb_pd_protocol.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usb_pd_protocol.c' cleanly.
        error: patch failed: common/usbc/usb_tc_drp_acc_trysrc_sm.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usbc/usb_tc_drp_acc_trysrc_sm.c' cleanly.
        error: patch failed: common/usbc_ppc.c:1
        Falling back to three-way merge...
        Applied patch to 'common/usbc_ppc.c' with conflicts.
        U common/usbc_ppc.c

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1182824 \u003c1182824@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}