Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8884118040609113552
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in test/fake_usbc.c
        CONFLICT (content): Merge conflict in common/usbc/usb_tc_drp_acc_trysrc_sm.c

Patch-set: 1
Tag: autogenerated:cq:full-run