Update patch set 1
Patch Set 1: Verified+1

I upload EC code that used no verify.
Because pre-upload.py have something wrong.
Please check below message, thanks.
============================================================ 
Repo must run the script:
  /mnt/host/source/src/repohooks/pre-upload.py

Do you want to allow this script to run (yes/yes-never-ask-again/NO)? y

ERROR: Traceback (most recent call last):
  File "/mnt/host/source/.repo/repo/project.py", line 417, in _ExecuteHook
    execfile(self._script_fullpath, context)
  File "/mnt/host/source/src/repohooks/pre-upload.py", line 632
    print msg + str(e)
            ^
SyntaxError: invalid syntax
============================================================

Patch-set: 1
Label: Verified=+1