Update patch set 2
Patch Set 2:

The following build(s) failed:

beaglebone-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/beaglebone-paladin/17605

wolf-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/wolf-paladin/18583

betty-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/betty-paladin/3705

kevin-arcnext-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/kevin-arcnext-paladin/1204

caroline-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/caroline-paladin/4167

kevin-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/kevin-paladin/5343

lakitu-gpu-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-gpu-paladin/4284

betty-arcnext-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/betty-arcnext-paladin/1205

tidus-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/tidus-paladin/3707

monroe-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/monroe-paladin/17463

winky-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/winky-paladin/5880

veyron_mighty-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_mighty-paladin/9538

zoombini-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/zoombini-paladin/3704

glados-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/glados-paladin/9530

nyan_big-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/nyan_big-paladin/5879

betty-arc64-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/betty-arc64-paladin/3314

cave-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/cave-paladin/4501

fizz-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/fizz-paladin/4862

oak-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/oak-paladin/11549

veyron_rialto-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_rialto-paladin/8399

scarlet-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/scarlet-paladin/4769

stout-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/stout-paladin/26593

nyan_kitty-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/nyan_kitty-paladin/5883

hana-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/hana-paladin/3829

gale-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/gale-paladin/6800

auron_yuna-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/auron_yuna-paladin/3707

daisy_skate-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy_skate-paladin/14143

veyron_speedy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/veyron_speedy-paladin/9537

nami-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/nami-paladin/2046

quawks-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/quawks-paladin/3706

daisy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy-paladin/30255

rainier-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/rainier-paladin/1977

kip-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/kip-paladin/5873

leon-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/leon-paladin/18013

terra-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/terra-paladin/1538

chell-nowithdebug-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/chell-nowithdebug-paladin/4121

daisy_spring-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy_spring-paladin/19528

samus-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/samus-paladin/18021

veyron_minnie-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/veyron_minnie-paladin/6810

panther-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/panther-paladin/17457

wizpig-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/wizpig-paladin/3833

peach_pit-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/peach_pit-paladin/19982

caroline-arcnext-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/caroline-arcnext-paladin/1205

veyron_tiger-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_tiger-paladin/3989

lakitu-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-paladin/10701

veyron_jaq-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_jaq-paladin/4200

tricky-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/tricky-paladin/12491

elm-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/elm-paladin/6992

link-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/link-paladin/32572

chell-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/chell-paladin/5463

guado_moblab-paladin: The HWTest [moblab_quick] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/guado_moblab-paladin/10169

poppy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/poppy-paladin/5610

falco-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/falco-paladin/19429

octopus-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/octopus-paladin/1440

bob-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** in https://luci-milo.appspot.com/buildbot/chromeos/bob-paladin/3830

veyron_jerry-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_jerry-paladin/4119

cyan-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/cyan-paladin/6807

grunt-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/grunt-paladin/2601

peppy-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/peppy-paladin/19399

sentry-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/sentry-paladin/3828

edgar-paladin: The HWTest [provision] stage failed: ** HWTest did not complete due to infrastructure issues (code 3) ** The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/edgar-paladin/3708

lakitu-st-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-st-paladin/3825

Your change may have caused this failure. There are also other changes that may be at fault: CL:1176723 CL:1179261 CL:1179438

Commit queue documentation: https://dev.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 2