Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8880366712274771424
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/hatch_fp/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'board/hatch_fp/build.mk' with conflicts.
        error: patch failed: board/nocturne_fp/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'board/nocturne_fp/build.mk' with conflicts.
        error: patch failed: board/nucleo-f412zg/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'board/nucleo-f412zg/build.mk' with conflicts.
        error: patch failed: board/nucleo-h743zi/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'board/nucleo-h743zi/build.mk' with conflicts.
        error: patch failed: test/build.mk:1
        Falling back to three-way merge...
        Applied patch to 'test/build.mk' with conflicts.
        U board/hatch_fp/build.mk
        U board/nocturne_fp/build.mk
        U board/nucleo-f412zg/build.mk
        U board/nucleo-h743zi/build.mk
        U test/build.mk

Patch-set: 2
Tag: autogenerated:cq:full-run