Move DECLARE_IRQ so that declaration of function precedes definition
DECLARE_IRQ needs to be before the interrupt handler definition or else
the following warning is generated by clang:

chip/stm32/clock-stm32h7.c:269:139:
error: attribute declaration must precede definition
[-Werror,-Wignored-attributes]

void irq_93_handler(void) __attribute__((naked)); typedef struct { int
dummy[93 >= 150 ? -1 : 1]; } irq_num_check_93; void
__attribute__((used)) __attribute__((used)) lptim_interrupt(void); void
irq_93_handler(void) { asm volatile("mov r0, lr\n" "push {r0, lr}\n" ""
"bl ""lptim_interrupt""\n" "pop {r0, lr}\n" "b task_resched_if_needed\n"
); } const struct irq_priority __attribute__((used))
__attribute__((used)) prio_93
__attribute__((section(".rodata.irqprio"))) = {93, 2}; ^

chip/stm32/clock-stm32h7.c:265:6: note: previous definition is here
void lptim_interrupt(void)

With this change all interrupt handlers appear to be preserved in the
symbol table. The following differences in the symbol table after this
change:

./util/compare_smaps.sh build.orig
ARD: aquila RW:
299a300
> r __func__.4157
302d302
< r __func__.4168
303a304
> r __func__.4173
308d308
< r __func__.4184

BOARD: arcadia RW:
207,208c207,208
< r __func__.4172
< r __func__.4188
---
> r __func__.4161
> r __func__.4177

BOARD: cr50 RW:
72c72
< b count.8358
---
> b count.8347
167c167
< b line_length.8360
---
> b line_length.8349
319c319
< b ws.8359
---
> b ws.8348
515,516c515,516
< r __func__.4305
< r __func__.4321
---
> r __func__.4294
> r __func__.4310
1049c1049
< r wheel.8361
---
> r wheel.8350

BOARD: cr51_base RW:
204,205c204,205
< r __func__.4161
< r __func__.4177
---
> r __func__.4150
> r __func__.4166

BOARD: glkrvp RO:
9c9
< b acpi_read_cache
---
> B acpi_read_cache.lto_priv.352
13,14c13,14
< B addr_prot_length.lto_priv.365
< B addr_prot_start.lto_priv.364
---
> B addr_prot_length.lto_priv.363
> B addr_prot_start.lto_priv.362
71c71
< B evt_cnt.lto_priv.362
---
> B evt_cnt.lto_priv.360
98c98
< B host_cmd_flags.lto_priv.359
---
> b host_cmd_flags
109c109
< B init_done.lto_priv.357
---
> B init_done.lto_priv.356
139c139
< B lpc_host_events.lto_priv.358
---
> B lpc_host_events.lto_priv.357
157,158c157,158
< B pending_args.lto_priv.349
< B pkt0.lto_priv.350
---
> B pending_args.lto_priv.350
> B pkt0.lto_priv.351
201c201
< B shm_mem_host_cmd.lto_priv.360
---
> B shm_mem_host_cmd.lto_priv.349
259c259
< D dptf_limit_ma.lto_priv.351
---
> D dptf_limit_ma.lto_priv.353
708c708
< R spi_flash_protect_ranges.lto_priv.363
---
> R spi_flash_protect_ranges.lto_priv.361
722c722
< R uart_wui.lto_priv.366
---
> R uart_wui.lto_priv.364
728c728
< t acpi_disable_burst_deferred
---
> T acpi_disable_burst_deferred.lto_priv.358
1013c1013
< T i2c_init_bus.lto_priv.361
---
> T i2c_init_bus.lto_priv.359
1016c1016
< t i2c_master_int_handler
---
> T i2c_master_int_handler
1089c1089
< T lpc_generate_sci.lto_priv.354
---
> t lpc_generate_sci
1098,1099c1098,1099
< T lpc_send_response.lto_priv.347
< T lpc_send_response_packet.lto_priv.348
---
> t lpc_send_response
> t lpc_send_response_packet
1105,1106c1105,1106
< T lpc_task_disable_irq.lto_priv.353
< T lpc_task_enable_irq.lto_priv.352
---
> T lpc_task_disable_irq.lto_priv.348
> T lpc_task_enable_irq.lto_priv.347

BOARD: glkrvp RW:
9c9
< b acpi_read_cache
---
> B acpi_read_cache.lto_priv.352
13,14c13,14
< B addr_prot_length.lto_priv.365
< B addr_prot_start.lto_priv.364
---
> B addr_prot_length.lto_priv.363
> B addr_prot_start.lto_priv.362
71c71
< B evt_cnt.lto_priv.362
---
> B evt_cnt.lto_priv.360
98c98
< B host_cmd_flags.lto_priv.359
---
> b host_cmd_flags
109c109
< B init_done.lto_priv.357
---
> B init_done.lto_priv.356
139c139
< B lpc_host_events.lto_priv.358
---
> B lpc_host_events.lto_priv.357
157,158c157,158
< B pending_args.lto_priv.349
< B pkt0.lto_priv.350
---
> B pending_args.lto_priv.350
> B pkt0.lto_priv.351
201c201
< B shm_mem_host_cmd.lto_priv.360
---
> B shm_mem_host_cmd.lto_priv.349
259c259
< D dptf_limit_ma.lto_priv.351
---
> D dptf_limit_ma.lto_priv.353
706c706
< R spi_flash_protect_ranges.lto_priv.363
---
> R spi_flash_protect_ranges.lto_priv.361
720c720
< R uart_wui.lto_priv.366
---
> R uart_wui.lto_priv.364
726c726
< t acpi_disable_burst_deferred
---
> T acpi_disable_burst_deferred.lto_priv.358
1011c1011
< T i2c_init_bus.lto_priv.361
---
> T i2c_init_bus.lto_priv.359
1014c1014
< t i2c_master_int_handler
---
> T i2c_master_int_handler
1087c1087
< T lpc_generate_sci.lto_priv.354
---
> t lpc_generate_sci
1096,1097c1096,1097
< T lpc_send_response.lto_priv.347
< T lpc_send_response_packet.lto_priv.348
---
> t lpc_send_response
> t lpc_send_response_packet
1103,1104c1103,1104
< T lpc_task_disable_irq.lto_priv.353
< T lpc_task_enable_irq.lto_priv.352
---
> T lpc_task_disable_irq.lto_priv.348
> T lpc_task_enable_irq.lto_priv.347

BOARD: granite RW:
290a291
> r __func__.4150
292d292
< r __func__.4161
293a294
> r __func__.4166
298d298
< r __func__.4177

BOARD: hammer RO:
13c13
< B bus_fault_ignored.lto_priv.164
---
> B bus_fault_ignored.lto_priv.163
372c372
< T keyboard_raw_gpio_interrupt.lto_priv.163
---
> t keyboard_raw_gpio_interrupt

BOARD: hammer RW:
546c546
< t keyboard_raw_gpio_interrupt
---
> T keyboard_raw_gpio_interrupt

BOARD: haven_dev RW:
305,306c305,306
< r __func__.4165
< r __func__.4181
---
> r __func__.4154
> r __func__.4170

BOARD: hg_0004 RW:
228,229c228,229
< r __func__.4176
< r __func__.4192
---
> r __func__.4165
> r __func__.4181

BOARD: hg_0005 RW:
205,206c205,206
< r __func__.4183
< r __func__.4199
---
> r __func__.4172
> r __func__.4188

BOARD: hg_dvt RW:
252,253c252,253
< r __func__.4175
< r __func__.4191
---
> r __func__.4164
> r __func__.4180

BOARD: hg_dvt2 RW:
252,253c252,253
< r __func__.4176
< r __func__.4192
---
> r __func__.4165
> r __func__.4181

BOARD: hg_evt_1_0 RW:
245,246c245,246
< r __func__.4174
< r __func__.4190
---
> r __func__.4163
> r __func__.4179

BOARD: hg_evt_2_0 RW:
245,246c245,246
< r __func__.4174
< r __func__.4190
---
> r __func__.4163
> r __func__.4179

BOARD: hg_overmold_dvt1 RW:
252,253c252,253
< r __func__.4176
< r __func__.4192
---
> r __func__.4165
> r __func__.4181

BOARD: hg_overmold_dvt2 RW:
252,253c252,253
< r __func__.4176
< r __func__.4192
---
> r __func__.4165
> r __func__.4181

BOARD: hg_pvt RW:
245,246c245,246
< r __func__.4176
< r __func__.4192
---
> r __func__.4165
> r __func__.4181

BOARD: hg_sku1 RW:
245,246c245,246
< r __func__.4178
< r __func__.4194
---
> r __func__.4167
> r __func__.4183

BOARD: hotelgolf RW:
245,246c245,246
< r __func__.4174
< r __func__.4190
---
> r __func__.4163
> r __func__.4179

BOARD: hslt_2 RW:
296,297c296,297
< r __func__.4193
< r __func__.4209
---
> r __func__.4182
> r __func__.4198

BOARD: hslt_b2cd RW:
314,315c314,315
< r __func__.4193
< r __func__.4209
---
> r __func__.4182
> r __func__.4198

BOARD: hslt_b2g RW:
310,311c310,311
< r __func__.4193
< r __func__.4209
---
> r __func__.4182
> r __func__.4198

BOARD: hslt_b2p RW:
296,297c296,297
< r __func__.4193
< r __func__.4209
---
> r __func__.4182
> r __func__.4198

BOARD: hslt_c2m1 RW:
316,317c316,317
< r __func__.4193
< r __func__.4209
---
> r __func__.4182
> r __func__.4198

BOARD: indus RW:
296a297
> r __func__.4162
298d298
< r __func__.4173
299a300
> r __func__.4178
304d304
< r __func__.4189

BOARD: nautilus RO:
1229c1229
< T i2c_master_int_handler
---
> t i2c_master_int_handler

BOARD: nautilus RW:
1227c1227
< T i2c_master_int_handler
---
> t i2c_master_int_handler

BOARD: proto2 RW:
314,315c314,315
< r __func__.4182
< r __func__.4198
---
> r __func__.4171
> r __func__.4187

BOARD: red RW:
255,256c255,256
< r __func__.4177
< r __func__.4193
---
> r __func__.4166
> r __func__.4182

BOARD: reef_it8320 RO:
4658d4657
< W gpio.c.80273340
4659a4659
> W gpio.c.d93da6c9
4664c4664
< W hwtimer.c.0d5fd6af
---
> W hwtimer.c.22fc2582
4667c4667
< W intc.c.43dfbcc5
---
> W intc.c.fe8bff28
4722c4722
< W uart.c.3944d8a8
---
> W uart.c.a62a79c5

BOARD: reef_it8320 RW:
4657d4656
< W gpio.c.80273340
4658a4658
> W gpio.c.d93da6c9
4663c4663
< W hwtimer.c.0d5fd6af
---
> W hwtimer.c.22fc2582
4666c4666
< W intc.c.43dfbcc5
---
> W intc.c.fe8bff28
4721c4721
< W uart.c.3944d8a8
---
> W uart.c.a62a79c5

BOARD: staff RO:
13c13
< B bus_fault_ignored.lto_priv.165
---
> B bus_fault_ignored.lto_priv.164
372c372
< T keyboard_raw_gpio_interrupt.lto_priv.164
---
> t keyboard_raw_gpio_interrupt

BOARD: staff RW:
546c546
< t keyboard_raw_gpio_interrupt
---
> T keyboard_raw_gpio_interrupt

BOARD: starcard RW:
249,250c249,250
< r __func__.4177
< r __func__.4193
---
> r __func__.4166
> r __func__.4182

BOARD: tk-x001 RW:
205,206c205,206
< r __func__.4183
< r __func__.4199
---
> r __func__.4172
> r __func__.4188

BOARD: wand RO:
13c13
< B bus_fault_ignored.lto_priv.156
---
> B bus_fault_ignored.lto_priv.155
361c361
< T keyboard_raw_gpio_interrupt.lto_priv.155
---
> t keyboard_raw_gpio_interrupt

BOARD: whiskers RO:
13c13
< B bus_fault_ignored.lto_priv.164
---
> B bus_fault_ignored.lto_priv.163
372c372
< T keyboard_raw_gpio_interrupt.lto_priv.163
---
> t keyboard_raw_gpio_interrupt

Boards that differ:
aquila_RW
arcadia_RW
cr50_RW
cr51_base_RW
glkrvp_RO
glkrvp_RW
granite_RW
hammer_RO
hammer_RW
haven_dev_RW
hg_0004_RW
hg_0005_RW
hg_dvt_RW
hg_dvt2_RW
hg_evt_1_0_RW
hg_evt_2_0_RW
hg_overmold_dvt1_RW
hg_overmold_dvt2_RW
hg_pvt_RW
hg_sku1_RW
hotelgolf_RW
hslt_2_RW
hslt_b2cd_RW
hslt_b2g_RW
hslt_b2p_RW
hslt_c2m1_RW
indus_RW
nautilus_RO
nautilus_RW
proto2_RW
red_RW
reef_it8320_RO
reef_it8320_RW
staff_RO
staff_RW
starcard_RW
tk-x001_RW
wand_RO
whiskers_RO

BRANCH=nocturne,nami
BUG=chromium:931797
TEST=make buildall -j

Change-Id: I4a13204795c3893ac8a8793ec304f9073e8ef6ef
Signed-off-by: Tom Hughes <tomhughes@chromium.org>