Update patch set 5
Patch Set 5: Verified-1

Hi, please check hatch-paladin BuildPackage failure caused by this CL.

Milo page:
https://ci.chromium.org/p/chromeos/builders/general/CQ/b8919051190451556352

Log link:
https://luci-logdog.appspot.com/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8919051190451556352/+/steps/BuildPackages/0/stdout

Log:
chromeos-ec-0.0.1-r5422: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.2.0/../../../../arm-eabi/bin/ld: build/hatch/utils_str/RO/driver/bc12/pi3usb9201.o: in function `bc12_power_up':
chromeos-ec-0.0.1-r5422: /build/hatch/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5422/work/chromeos-ec-0.0.1/platform/ec/driver/bc12/pi3usb9201.c:207: undefined reference to `power_5v_enable'
chromeos-ec-0.0.1-r5422: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.2.0/../../../../arm-eabi/bin/ld: build/hatch/utils_str/RO/driver/bc12/pi3usb9201.o: in function `bc12_power_down':
chromeos-ec-0.0.1-r5422: /build/hatch/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5422/work/chromeos-ec-0.0.1/platform/ec/driver/bc12/pi3usb9201.c:199: undefined reference to `power_5v_enable'

Patch-set: 5
Reviewer: Gerrit User 1112716 <1112716@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1