Add support for building firmware with clang
By default all builds will use gcc. To build with clang, set CC=clang.

When building nocturne_fp with clang, the size reported at the end is
incorrect (it's not actually so large to overflow flash):

*** -240034 bytes in flash and 240034 bytes in RAM still available on
  nocturne_fp ****

Note that DECLARE_IRQ now needs to be before the interrupt handler
definition or else the following warning is generated by clang:

chip/stm32/clock-stm32h7.c:269:139:
error: attribute declaration must precede definition
[-Werror,-Wignored-attributes]

void irq_93_handler(void) __attribute__((naked)); typedef struct { int
dummy[93 >= 150 ? -1 : 1]; } irq_num_check_93; void
__attribute__((used)) __attribute__((used)) lptim_interrupt(void); void
irq_93_handler(void) { asm volatile("mov r0, lr\n" "push {r0, lr}\n" ""
"bl ""lptim_interrupt""\n" "pop {r0, lr}\n" "b task_resched_if_needed\n"
); } const struct irq_priority __attribute__((used))
__attribute__((used)) prio_93
__attribute__((section(".rodata.irqprio"))) = {93, 2}; ^

chip/stm32/clock-stm32h7.c:265:6: note: previous definition is here
void lptim_interrupt(void)

BRANCH=nocturne,nami
BUG=chromium:931797
TEST=make BOARD=nocturne_fp -j
     flash_fp_mcu ec.bin
     ectool --name=cros_fp fpstats
     cat /sys/kernel/debug/cros_fp/console_log
TEST=CC=clang make BOARD=nocturne_fp -j
     flash_fp_mcu ec.bin
     ectool --name=cros_fp fpstats
     cat /sys/kernel/debug/cros_fp/console_log
TEST=make buildall -j

Change-Id: I6b0fad94bb25c565883acf6af9c05bb09c990dd7
Signed-off-by: Tom Hughes <tomhughes@chromium.org>