usbpd: ensure bad states generate compiler error
Now that we unconditionally include all enum values, which makes the
code easier to read, we still want to add compile-time errors for code
that uses an unsupported PD state based on the board's configuration.

BRANCH=none
BUG=none
TEST=through manually adding incorrect code that uses the wrong state,
that a compiler error is generated in the following form:
common/usb_pd_protocol.c:2669:18: error:
'UNSUPPORTED_PD_STATE_VCONN_SWAP_SEND' undeclared (first use in this
function); did you mean 'PD_STATE_VCONN_SWAP_SEND'?
  set_state(port, PD_STATE_VCONN_SWAP_SEND);

Change-Id: Ibf3c05826b32739afaa93cf9563aac61f10441ff
Signed-off-by: Jett Rink <jettrink@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1526317
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>