Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8882892869246818400
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: test/fake_usbc.c:1
        Falling back to three-way merge...
        Applied patch to 'test/fake_usbc.c' with conflicts.
        U test/fake_usbc.c

Patch-set: 4
Tag: autogenerated:cq:full-run