util: Enable -Wstrict-prototypes for ftdi.h
The pragma is missing a push before the ignore line, which means as it
was written the warning continued to be disabled.

https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html

clang catches this bug, but gcc doesn't.

util/ec_uartd.c:26:24: error: pragma diagnostic pop could not pop, no
matching push [-Werror,-Wunknown-pragmas]
                       ^
However, it appears we don't even need to disable this warning anymore
since the compilation succeeds without it.

BRANCH=none
BUG=chromium:931797
TEST=make buildall -j

Change-Id: I81d48a841cb16d54fe0878b218e80d8a1d89e129
Signed-off-by: Tom Hughes <tomhughes@chromium.org>