board/zinger: Remove unused forward reference
The forward reference isn't needed here and causes a compilation error
when included from C++:

board/zinger/board.h:95:6:
error: ISO C++ forbids forward references to 'enum' types
enum gpio_signal;
     ^

BRANCH=none
BUG=b:144959033
TEST=make buildall

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I0796946afbafb7a905d7ce880efa3f0b5bbcff41