Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8872210550136969920
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/voxel/board.h:1
        Falling back to three-way merge...
        Applied patch to 'board/voxel/board.h' cleanly.
        error: patch failed: board/voxel/gpio.inc:1
        Falling back to three-way merge...
        Applied patch to 'board/voxel/gpio.inc' with conflicts.
        U board/voxel/gpio.inc

Patch-set: 2
Tag: autogenerated:cq:full-run