Do not silently ignore invalid attempts to use raided programmer
When --raiden is passed as a command line parameter, do not proceed
programming as if it were not present, alert the user and refuse to
proceed instead.

Need to jump though a couple of extra hoops to avoid printing the
error message twice.

BRANCH=none
BUG=none
TEST=tried running with boards supporting and not supporting
     programming over CCD.

     $ ./util/flash_ec --board=oak --raiden --image rowan.ec.bin
     INFO: Using ec image : rowan.ec.bin
     ERROR: raiden mode not supported on oak
     $ ./util/flash_ec --board=kevin --raiden --image rowan.ec.bin
     INFO: Using ec image : rowan.ec.bin
     INFO: Flashing chip npcx_spi.
     INFO: Using raiden debug cable.
     ...

Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Change-Id: Ia40f348e6dde57fc2f4c49719bc2a0947036dcc1