Update patch set 18
Patch Set 18:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8784495708459103169) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    Applied patch to 'chip/host/clock.c' with conflicts.
    Applied patch to 'chip/ish/clock.c' with conflicts.
    Applied patch to 'chip/it83xx/clock.c' with conflicts.
    Applied patch to 'chip/max32660/clock_chip.c' with conflicts.
    Applied patch to 'chip/mchp/clock.c' with conflicts.
    Applied patch to 'chip/mt_scp/mt818x/clock_mt8183.c' with conflicts.
    Applied patch to 'chip/mt_scp/mt818x/clock_mt8186.c' with conflicts.
    Applied patch to 'chip/mt_scp/mt8192/clock.c' with conflicts.
    Applied patch to 'chip/mt_scp/mt8195/clock.c' with conflicts.
    Applied patch to 'chip/npcx/clock.c' with conflicts.
    Applied patch to 'chip/stm32/clock-stm32f0.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32f3.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32f4.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32g4.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32h7.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32l.c' cleanly.
    Applied patch to 'chip/stm32/clock-stm32l4.c' cleanly.
    Applied patch to 'common/mock/build.mk' cleanly.
    Falling back to direct application...
    Falling back to direct application...
    Applied patch to 'zephyr/shim/chip/it8xxx2/clock.c' with conflicts.
    Applied patch to 'zephyr/shim/chip/mchp/clock.c' cleanly.
    Applied patch to 'zephyr/shim/chip/npcx/clock.c' cleanly.
    error: zephyr/shim/chip/stm32/clock.c: does not exist in index

Patch-set: 18
Tag: autogenerated:cq:dry-run:1680848780
Attention: {"person_ident":"Gerrit User 1293547 \u003c1293547@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#18: Tryjobs failed"}