Update patch set 2
Patch Set 2:

A trybot failed to apply your change in https://uberchromegw.corp.google.com/i/chromiumos.tryserver/builders/mixed-b-pre-cq/builds/38342 . CL:342171 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/71/342171/2
remote: Short term bandwidth rate limit exceeded for 3su6n15k.default@developer.gserviceaccount.com.
fatal: protocol error: bad pack header

cwd=/b/cbuild/internal_master/src/platform/ec
Traceback (most recent call last):
  File "/b/build/slave/compile-only-pre-cq/build/chromite/lib/parallel.py", line 601, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/build/slave/compile-only-pre-cq/build/chromite/lib/parallel.py", line 799, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/build/slave/compile-only-pre-cq/build/chromite/cbuildbot/validation_pool.py", line 1041, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/build/slave/compile-only-pre-cq/build/chromite/lib/git.py", line 829, in RunGit
    ['git'] + cmd, **kwargs)
  File "/b/build/slave/compile-only-pre-cq/build/chromite/lib/retry_util.py", line 88, in GenericRetry
    ret = functor(*args, **kwargs)
  File "/b/build/slave/compile-only-pre-cq/build/chromite/lib/cros_build_lib.py", line 619, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/ec refs/changes/71/342171/2
remote: Short term bandwidth rate limit exceeded for 3su6n15k.default@developer.gserviceaccount.com.
fatal: protocol error: bad pack header

cwd=/b/cbuild/internal_master/src/platform/ec


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 2
Reviewer: Gerrit User 1118934 <1118934@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0