Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8875914475991171520
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: driver/ppc/syv682x.c:1
        Falling back to three-way merge...
        Applied patch to 'driver/ppc/syv682x.c' with conflicts.
        U driver/ppc/syv682x.c

Patch-set: 3
Tag: autogenerated:cq:full-run