Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8884349130209904960
    Merge conflict detected! Please rebase and retry.
    
        error: mode change for overlay-hatch/chromeos-base/chromeos-config-bsp-hatch/chromeos-config-bsp-hatch-0.0.1-r70.ebuild, which is not in current HEAD
        error: could not build fake ancestor
        hint: Use 'git am --show-current-patch' to see the failed patch

Patch-set: 1
Tag: autogenerated:cq:dry-run