WIP, flash_ec: build bridge to new servod architecture
In the new servod architecture, the main changes affecting flash_ec are
that
(1) there is support for prefix routing to route to the right device
// This requires adding --prefix as a parameter, and some logic to
// ignore it or use it iff the servod is the new architecture and the
// prefix is known

(2) the servo_type does no longer support servo_v4_with_[...] but rather
each device reports their own type.
// This requires adding ccd_cr50 as a standalone device to flash_ec

(3) the serialnames are also no longer required to have special logic,
but rather follow the prefix routing logic i.e. serialname will report
for the device that the control is intended for.
// This needs no adjustment as it works the same as using servo v4,
// servo micro, or ccd by itself now.

BRANCH=None
BUG=chromium:841121
TEST=manual testing

prep:
add echo & exit 0 statements below the new logic

// old servod without prefixes
./flash_ec --prefix lol
WARNING: old servod. no prefix support. prefix 'lol'
dut-control --port=9999

// new servod with an unknown prefix
./flash_ec --prefix lol
ERROR: prefix 'lol' unknown to servod.

// new servod with a known prefix
./flash_ec --prefix support
dut-control --port=9999 --prefix=support

// new servod without a prefix
./flash_ec
dut-control --port=9999

Change-Id: Ib01512a168c205c23507c1a5630677319ae1f6b4
Signed-off-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>