Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > The build error is caused by:
> > > ec-devutils-0.0.2-r4375: touchpad_updater.c:18:10: fatal error: 'libusb.h' file not found
> > > ec-devutils-0.0.2-r4375: #include <libusb.h>
> > > ec-devutils-0.0.2-r4375:          ^~~~~~~~~~
> > > ec-devutils-0.0.2-r4375: 1 error generated.
> > 
> > Yep, I can't repro locally so will do a tryjob. Thanks.
> 
> Seems like libusb dependency is missing from ebuild?

Yeah it's missing but that's not the problem. The problem is that PKG_CONFIG is not set.

Patch-set: 2
Reviewer: Gerrit User 1129199 <1129199@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>