core/cortex-m0: Fix inline asm in in_interrupt_context
"lsl" is not a valid instruction for Cortex-M0:
https://developer.arm.com/documentation/ddi0432/c/CHDCICDF.

Instead of "lsl", gcc will silently emit the correct variant of the
instruction ("lsls" which updates condition codes).

However, when using clang, it fails to compile due to the invalid
instruction:

core/cortex-m0/task.c:178:7: error: invalid instruction, any one of the
following would fix this:

"lsl %0, #23\n" : "=r"(ret)); /* exception bits are the 9 LSB */
^

<inline asm>:2:1: note: instantiated into assembly here
lsl r0, #23
^
core/cortex-m0/task.c:178:7: note: instruction requires: thumb2

"lsl %0, #23\n" : "=r"(ret)); /* exception bits are the 9 LSB */
^

<inline asm>:2:1: note: instantiated into assembly here
lsl r0, #23
^
core/cortex-m0/task.c:178:7: note: no flag-preserving variant of this
instruction available

"lsl %0, #23\n" : "=r"(ret)); /* exception bits are the 9 LSB */
^

Instead of writing assembly to do the shifting, just use C to shift the
result, which does not change the generated code:

00000000 <in_interrupt_context>:
   0:   f3ef 8005       mrs     r0, IPSR
   4:   05c0            lsls    r0, r0, #23
   6:   4770            bx      lr

Note that this change does not result in bit-for-bit exactness of the
final image on some boards.

BRANCH=none
BUG=b:172020503
TEST=CC=clang make BOARD=servo_micro -j
TEST=./util/compare_build.sh -b all -j 70
    All boards match exactly, except the following:
    bland burnet cerise chocodile_vpdmcu coffeecake damu don eel fennel
    hammer jacuzzi juniper kappa magnemite makomo masterball moonball
    oak servo_micro servo_v4 servo_v4p1 staff star stern wand whiskers
    willow zed

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I530896186c2dbbd582f7c9973d1157ebe3601b34