test/utils: Switch to run-time test to fix clang build
The BUILD_ASSERT that was used fails to compile with clang:

error: static_assert expression is not an integral
constant expression
        BUILD_ASSERT(str1 != str3)

BRANCH=none
BUG=b:172020503
TEST=make buildall -j
TEST=./test/run_device_tests.py --board dartmonkey --compiler clang
       --tests=utils  --remote 127.0.0.1:2551
TEST=./test/run_device_tests.py --board dartmonkey --compiler gcc
       --tests=utils  --remote 127.0.0.1:2551

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Id93ea45b653b86fd5a79ed565e1fa94ffd317723