Update patch set 2
Patch Set 2:

NOTE: The Commit Queue will retry your change automatically.

The following build(s) failed:

oak-paladin: The ChromeSDK stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The CPEExport stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The UploadTestArtifacts stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The Archive stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret in https://uberchromegw.corp.google.com/i/chromeos/builders/oak%20paladin/builds/2063

This failure was probably caused by CL:309607

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 2