WIP: Convert Zephyr fingerprint tests to C++
We want to be able to use C++ in fpsensor_state.h, which is included by
these tests.

zephyr/test/fingerprint/task/src/fpsensor_init.cc:38:11:
error: initializer-string for char array is too long, array size is 32
but initializer has size 33 (including the null terminating character)
                 .seed = "very_secret_32_bytes_of_tpm_seed",
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

zephyr/test/fingerprint/task/src/fpsensor_init.cc:68:11:
error: initializer-string for char array is too long, array size is 32
but initializer has size 33 (including the null terminating character)
                 .seed = "very_secret_32_bytes_of_tpm_seed",

BUG=none
TEST=none

Change-Id: Iee5882239b01949a047ddd27d79ee219998cadfc