Revert "flash_ec: npcx: Updating the preserve mechanism"
This reverts commit 7b4ff233696ef317b0829144aecfc695b78f8ae4.

Reason for revert: broke flashing on Pujjo:

    INFO: Reading FMAP section from EC chip
    ./util/flash_ec: line 1855: 4: missing arg 4: Size
    ERROR: Failed to flash EC firmware image)

Original change's description:
> flash_ec: npcx: Updating the preserve mechanism
>
> So far we are preserving sections while flashing based on new image,
> with this change we will preserve sections based on old image preserve
> flags
>
> BUG=b:297804096
> TEST=Flashed on Rex
> FMAP read successful case
> wrong location read for FMAP case
> no_preserve case
> no preserve sections present case
> preserve sections not present in new image case
> invalid chip type case
>
> Change-Id: Ib9338a7442717967ac6d366ad7c65cc1d3719e18
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4845789
> Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
> Reviewed-by: Wai-Hong Tam <waihong@google.com>
> Tested-by: Madhurima Paruchuri <mparuchuri@google.com>
> Commit-Queue: Madhurima Paruchuri <mparuchuri@google.com>

BUG=b:297804096

Change-Id: I2732de14daa818caa2907986a71773e5667f2f1f