Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8832294381991961201
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'common/battery.c' cleanly.
        error: common/battery_v1.c: does not exist in index
        error: cannot read the current contents of 'common/battery_v1.c'
        Falling back to direct application...
        error: common/battery_v2.c: does not exist in index
        error: cannot read the current contents of 'common/battery_v2.c'
        Falling back to direct application...
        Applied patch to 'common/build.mk' cleanly.
        Applied patch to 'common/charge_state_v2.c' with conflicts.
        Applied patch to 'include/battery.h' cleanly.
        Applied patch to 'include/charge_state_v2.h' cleanly.
        Applied patch to 'include/config.h' cleanly.
        Applied patch to 'test/test_config.h' cleanly.
        Applied patch to 'zephyr/CMakeLists.txt' cleanly.
        Applied patch to 'zephyr/Kconfig.battery' cleanly.
        Applied patch to 'zephyr/shim/include/config_chip.h' cleanly.
        U common/charge_state_v2.c

Patch-set: 6
Tag: autogenerated:cv
Attention: {"person_ident":"Gerrit User 1106949 \u003c1106949@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: CQ dry run failed."}