Update patch set 10
Patch Set 10:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8878543908783144960
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/waddledoo/board.c:1
        Falling back to three-way merge...
        Applied patch to 'board/waddledoo/board.c' cleanly.
        error: patch failed: board/waddledoo/board.h:1
        Falling back to three-way merge...
        Applied patch to 'board/waddledoo/board.h' with conflicts.
        U board/waddledoo/board.h

Patch-set: 10
Tag: autogenerated:cq:full-run