Update patch set 1
Patch Set 1: Verified-1

Lots of complaining about missing functions, we're probably getting hit by one of "-ffreestanding -fno-builtin -nostdinc -nostdlib":

  LD      RW/ec.RW.elf
/tmp/ccMZCxWm.ltrans20.ltrans.o: In function `normalize':
ccMZCxWm.ltrans20.o:(.text+0x244): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x24c): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x254): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x262): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x26a): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x278): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x280): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x290): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x2a0): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x2a8): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x2bc): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x2c4): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x2d8): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x2e0): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x2ee): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x2f4): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x2fc): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x30c): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x314): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x328): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x330): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x33e): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x344): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x34c): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x35c): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x364): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x372): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x378): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x380): undefined reference to `__aeabi_fadd'
ccMZCxWm.ltrans20.o:(.text+0x3b4): undefined reference to `__aeabi_i2f'
ccMZCxWm.ltrans20.o:(.text+0x3be): undefined reference to `__aeabi_fdiv'
ccMZCxWm.ltrans20.o:(.text+0x3c8): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x3d6): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x3e4): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x3f2): undefined reference to `__aeabi_fmul'
ccMZCxWm.ltrans20.o:(.text+0x3fe): undefined reference to `__aeabi_fmul'

Patch-set: 1
Reviewer: Gerrit User 1113904 <1113904@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1