Update patch set 2
Patch Set 2:

this broke buildall

chip/npcx/spiflashfw/npcx_monitor.c: In function 'sspi_flash_upload':
chip/npcx/spiflashfw/npcx_monitor.c:290:2: error: implicit declaration of function 'watchdog_stop_and_unlock' [-Werror=implicit-function-declaration]
  watchdog_stop_and_unlock();
  ^~~~~~~~~~~~~~~~~~~~~~~~

"make buildall" actually returns success in spite of these
compiler errors, so that's another problem.

Patch-set: 2
CC: Gerrit User 1119124 <1119124@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>