Update patch set 3
Patch Set 3:

buildall is still fail because cr50 is unable to build

In file included from chip/g/dcrypto/dcrypto.h:15:0,
                 from chip/g/dcrypto/sha256.c:6:
chip/g/dcrypto/internal.h:18:28: fatal error: cryptoc/sha384.h: No such file or directory
 #include "cryptoc/sha384.h"
                            ^
compilation terminated.
make: *** [Makefile.rules:304: build/cr50/RO/chip/g/dcrypto/sha256.o] Error 1

Patch-set: 3
Label: Code-Review=0