Update patch set 1
Patch Set 1:

The following build(s) failed:

daisy paladin: The BuildImage stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/daisy-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/daisy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1884, in ArchivePayloads
    commands.GenerateFullPayload(self._build_root, image_path, tempdir)
  File "/b/cbuild/daisy-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1631, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/daisy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 736, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/daisy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/08/01 11:18:40 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/08/01 11:18:40 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 64, in <module>

2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy

2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/xbuddy.py", line 21, in <module>

2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy_lookup_table

2013/08/01 11:18:42 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named xbuddy_lookup_table

Traceback (most recent call last):
  File "/b/cbuild/daisy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/daisy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/daisy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    result... (truncated)

link paladin: The BuildImage stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/link-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1884, in ArchivePayloads
    commands.GenerateFullPayload(self._build_root, image_path, tempdir)
  File "/b/cbuild/link-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1631, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/cros_build_lib.py", line 736, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/link-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/08/01 11:20:31 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/08/01 11:20:31 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 64, in <module>

2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy

2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/xbuddy.py", line 21, in <module>

2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy_lookup_table

2013/08/01 11:20:33 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named xbuddy_lookup_table

Traceback (most recent call last):
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/link-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    results = Proce... (truncated)

amd64 generic paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in http://build.chromium.org/p/chromiumos/builders/amd64%20generic%20paladin/builds/15163

lumpy paladin: The BuildImage stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1884, in ArchivePayloads
    commands.GenerateFullPayload(self._build_root, image_path, tempdir)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1631, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 736, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/lumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/08/01 11:20:33 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/08/01 11:20:33 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 64, in <module>

2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy

2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/xbuddy.py", line 21, in <module>

2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy_lookup_table

2013/08/01 11:20:35 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named xbuddy_lookup_table

Traceback (most recent call last):
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/lumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
    result... (truncated)

mario paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in https://uberchromegw.corp.google.com/i/chromeos/builders/mario%20paladin/builds/12398

alex paladin: The BuildImage stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1884, in ArchivePayloads
    commands.GenerateFullPayload(self._build_root, image_path, tempdir)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1631, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 736, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/08/01 11:17:54 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/08/01 11:17:54 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 64, in <module>

2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy

2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/xbuddy.py", line 21, in <module>

2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy_lookup_table

2013/08/01 11:17:56 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named xbuddy_lookup_table

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in Gene... (truncated)

stumpy paladin: The BuildImage stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/parallel.py", line 281, in _Run
    self._task(*self._task_args, **self._task_kwargs)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1884, in ArchivePayloads
    commands.GenerateFullPayload(self._build_root, image_path, tempdir)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1631, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 736, in RunCommandCaptureOutput
    redirect_stderr=kwds.pop('redirect_stderr', True), **kwds)
  File "/b/cbuild/stumpy-paladin-bin-master/chromite/lib/cros_build_lib.py", line 458, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2013/08/01 11:25:39 - cros_generate_test_payloads.py - INFO    : Using target image as base image.
2013/08/01 11:25:39 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   : Could not find PREGENERATED_UPDATE in log:
2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log: Traceback (most recent call last):

2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib/devserver/devserver.py", line 64, in <module>

2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy

2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log:   File "/usr/lib64/devserver/xbuddy.py", line 21, in <module>

2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log:     import xbuddy_lookup_table

2013/08/01 11:25:41 - cros_generate_test_payloads.py - ERROR   :   log: ImportError: No module named xbuddy_lookup_table

Traceback (most recent call last):
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 487, in <module>
    main()
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 482, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/stumpy-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 331, in GeneratePayloads
 ... (truncated)

x86 generic paladin: The VMTest stage failed: ** VMTests failed with code 1 ** in http://build.chromium.org/p/chromiumos/builders/x86%20generic%20paladin/builds/15358

Your change may have caused this failure. There are also other changes that may be at fault: CL:*42103, CL:61963, CL:62931, CL:63130, CL:63363, CL:63484, CL:63772, CL:63847, CL:63848, CL:63975

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1