util/flash_ec: ec firmware image validation support
This change will add support of new argument
"--do_ec_image_validation" for ec firmware image validation
before initiating flashing. The boards which defines
ec_board_info in servo overlay files would be able to
validate ec image before flashing. EC firmware image validation
will be skipped for boards where ec_board_info is not defined.
This CL depends on CL:6999094

BUG=b:444366697
TEST=Run servod for ocelot using "sudo servod -b ocelot"
     Run "./flash_ec --image=../ocelotrvp-ite_ec.bin --do_ec_image_validation"
     Output:
       INFO: Using servo_micro.
       INFO: Using ec image : ../ocelotrvp-ite_ec.bin
       INFO: Validating EC image compatibility for ec chip going to be flashed...
       INFO: Detected EC board variant from servo: ocelotrvp-npcx
       INFO: Searching for EC board variant identifier 'ocelotrvp-npcx' in firmware image...
       ERROR: EC image compatibility validation failed!
       ERROR: Expected EC board variant: 'ocelotrvp-npcx'
       ERROR: This EC board variant identifier was not found in the firmware image: '../ocelotrvp-ite_ec.bin'
       ERROR: This could be possible due to the EC image provided does not support the connected EC chip.
       ERROR: Force flashing may fail or brick the device.
       ERROR:
       ERROR: Please verify:
       ERROR: 1. The firmware image is built for the correct EC board variant
       ERROR: 2. The servo overlay defines board details for connected variant and able to correctly detecting the board details
       ERROR: 3. You have provided the correct EC firmware file w.r.t EC board variant
       ERROR:
       ERROR: Aborting flash operation due to EC firmware image and EC board variant mismatch

Change-Id: Ie6325badd7b982fb9f691678b9f55461202a357a