Revert "whiskers: enable ST touchpad"
This reverts commit 225e6815a9dd44ebaca841262d854391a5dfa91d.

Original commit cause the following error during buildall

common/update_fw.c:27:12: error: size of array ‘__build_assertion_28’
is negative
 BUILD_ASSERT(sizeof(touchpad_fw_hashes) ==
 ^
make: *** [Makefile.rules:371: build/whiskers/RW/common/update_fw.o] Error
1
make: *** Waiting for unfinished jobs....

Change-Id: If979b4a90bcc52333920c38b6dd21d6756531143
Signed-off-by: Jett Rink <jettrink@chromium.org>