Update patch set 2
Patch Set 2:

The following build(s) failed:

x86-mario-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-mario%20paladin/builds/3332

wolf-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/wolf%20paladin/builds/4129

leon-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/leon%20paladin/builds/3567

lumpy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/lumpy%20paladin/builds/18081

parrot-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/parrot%20paladin/builds/12799

stumpy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/stumpy%20paladin/builds/18123

x86-alex-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-alex%20paladin/builds/17563

stout-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/stout%20paladin/builds/12146

daisy_spring-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/daisy_spring%20paladin/builds/5069

nyan-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/nyan%20paladin/builds/2572

daisy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/daisy%20paladin/builds/15815

samus-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/samus%20paladin/builds/3566

panther-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/panther%20paladin/builds/3011

peppy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/peppy%20paladin/builds/4961

peach_pit-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/peach_pit%20paladin/builds/5531

link-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/link%20paladin/builds/18121

x86-mario-nowithdebug-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-mario%20nowithdebug-paladin/builds/2832

falco-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/falco%20paladin/builds/4975

rambi-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/rambi%20paladin/builds/3012

duck-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/duck%20paladin/builds/2063

storm-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/storm%20paladin/builds/835

butterfly-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/butterfly%20paladin/builds/12142

monroe-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/monroe%20paladin/builds/3016

stumpy_moblab-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'output' in https://uberchromegw.corp.google.com/i/chromeos/builders/stumpy_moblab%20paladin/builds/2061

Your change may have caused this failure. There are also other changes that may be at fault: 25 other changes. See the blamelist for more details.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 2