Update patch set 3
Patch Set 3: Verified-1

Hi,

Looks like this broke peach/pit builder: 

http://chromegw/i/chromeos/builders/peach_pit%20paladin/builds/5633/steps/BuildPackages/logs/stdio

chromeos-ec-0.0.1-r1833: chip/stm32/flash-stm32l.c: In function 'flash_pre_init':
chromeos-ec-0.0.1-r1833: chip/stm32/flash-stm32l.c:425:4: error: implicit declaration of function 'flash_protect_ro_at_boot' [-Werror=implicit-function-declaration]
chromeos-ec-0.0.1-r1833:     flash_protect_ro_at_boot(1);
chromeos-ec-0.0.1-r1833:     ^
chromeos-ec-0.0.1-r1833: cc1: all warnings being treated as errors

Patch-set: 3