Update patch set 10
Patch Set 10: Verified-1 Code-Review-1

This possibly broke fizz paladin

https://uberchromegw.corp.google.com/i/chromeos/builders/fizz-paladin/builds/995/steps/BuildPackages/logs/stdio

chromeos-ec-0.0.1-r3944: make[1]: *** [Makefile.rules:361: build/fizz/mutex/RO/common/power_button_x86.o] Error 1
chromeos-ec-0.0.1-r3944: make[1]: *** Waiting for unfinished jobs....
chromeos-ec-0.0.1-r3944:   CC      RO/common/spi_flash_reg.o
chromeos-ec-0.0.1-r3944:   CC      RO/common/shared_mem.o
chromeos-ec-0.0.1-r3944:   CC      RO/common/spi_flash_reg.o
chromeos-ec-0.0.1-r3944: common/power_button_x86.c: In function 'state_machine':
chromeos-ec-0.0.1-r3944: common/power_button_x86.c:331:5: error: 'DSW_PWROK_TO_PWRBTN_US' undeclared (first use in this function)
chromeos-ec-0.0.1-r3944:      DSW_PWROK_TO_PWRBTN_US) {
chromeos-ec-0.0.1-r3944:      ^

Patch-set: 10
Reviewer: Gerrit User 1158909 <1158909@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=-1
Label: Verified=-1