Update patch set 11
Patch Set 11:

unittest failed in the CQ in the ec package.  it doesn't seem like this CL could have caused it, but there's no other relevant CLs in the list.  please double check.

>  chromeos-ec-0.0.1-r5885: In file included from include/config.h:4282:0,
chromeos-ec-0.0.1-r5885:                  from include/common.h:142,
chromeos-ec-0.0.1-r5885:                  from include/ec_commands.h:30,
chromeos-ec-0.0.1-r5885:                  from util/cros_ec_dev.h:11,
chromeos-ec-0.0.1-r5885:                  from util/comm-dev.c:19:
chromeos-ec-0.0.1-r5885: board/kodama/board.h:137:14: error: 'struct ec_response_usb_pd_power_info' declared inside parameter list [-Werror]
chromeos-ec-0.0.1-r5885:        struct ec_response_usb_pd_power_info *r);
chromeos-ec-0.0.1-r5885:               ^
chromeos-ec-0.0.1-r5885: board/kodama/board.h:137:14: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]

Patch-set: 11
CC: Gerrit User 1000768 <1000768@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>