Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Any reason not to suppress the repeated messages?
> """
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/logging/handlers.py", line 77, in emit
>     self.doRollover()
>   File "/usr/lib64/python2.7/logging/handlers.py", line 142, in doRollover
>     os.rename(self.baseFilename, dfn)
> OSError: [Errno 1] Operation not permitted
> Logged from file arm-none-eabi-gcc, line 466
> """

Nevermind, it seems that something changed in the chroot that made it drop privileges now.

Patch-set: 3