zephyr: flash: npcx: Initialize 'reg' to fix GCC uninitialized warning
The `reg` variable in `cros_flash_npcx.c` was being used uninitialized,
leading to a build error with the GCC compiler:

'/usr/local/google/home/fsammoura/chromiumos/src/platform/ec/zephyr/ \
/drivers/cros_flash/cros_flash_npcx.c:69:25: error: 'reg' may be used
uninitialized [-Werror=maybe-uninitialized]`

BUG=b:417755493
TEST=CQ

Change-Id: I4ec6d00e353568cbeb6c46639af1025456b29c2c