Update patch set 14
Patch Set 14: Verified-1

Broke last CQ run:

chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1139:8: error: macro "DECLARE_CONSOLE_COMMAND" passed 5 arguments, but takes just 4
chromeos-ec-0.0.1-r3268:     NULL);
chromeos-ec-0.0.1-r3268:         ^
chromeos-ec-0.0.1-r3268:   CC      RO/chip/stm32/usart_tx_interrupt.o
chromeos-ec-0.0.1-r3268:   CC      RO/chip/npcx/watchdog.o
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1136:1: error: data definition has no type or storage class [-Werror]
chromeos-ec-0.0.1-r3268:  DECLARE_CONSOLE_COMMAND(usb, command_usb,
chromeos-ec-0.0.1-r3268:  ^
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1136:1: error: type defaults to 'int' in declaration of 'DECLARE_CONSOLE_COMMAND' [-Werror=implicit-int]
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1230:6: error: macro "DECLARE_CONSOLE_COMMAND" passed 5 arguments, but takes just 4
chromeos-ec-0.0.1-r3268:   NULL);
chromeos-ec-0.0.1-r3268:       ^
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1227:1: error: data definition has no type or storage class [-Werror]
chromeos-ec-0.0.1-r3268:  DECLARE_CONSOLE_COMMAND(serialno, command_serialno,
chromeos-ec-0.0.1-r3268:  ^
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1227:1: error: type defaults to 'int' in declaration of 'DECLARE_CONSOLE_COMMAND' [-Werror=implicit-int]
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1125:12: error: 'command_usb' defined but not used [-Werror=unused-function]
chromeos-ec-0.0.1-r3268:  static int command_usb(int argc, char **argv)
chromeos-ec-0.0.1-r3268:             ^
chromeos-ec-0.0.1-r3268: chip/stm32/usb_dwc.c:1201:12: error: 'command_serialno' defined but not used [-Werror=unused-function]
chromeos-ec-0.0.1-r3268:  static int command_serialno(int argc, char **argv)
chromeos-ec-0.0.1-r3268:             ^

Patch-set: 14