driver/als_si114x: Add missing case statement
When building with clang it warns:

driver/als_si114x.c:317:10: error: no case matching constant switch
condition '0' [-Werror]
        switch (SI114X_NUM_LEDS) {
                ^~~~~~~~~~~~~~~
./driver/als_si114x.h:35:25: note: expanded from macro 'SI114X_NUM_LEDS'
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~

BRANCH=none
BUG=b:172020503
TEST=CC=clang make BOARD=eve

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I94db5530c681c438db53bb065c45b223caea7917