Update patch set 1
Patch Set 1:

The following build(s) failed:

stout32 paladin: The Archive stage failed: 


Traceback (most recent call last):
  File "/b/cbuild/stout32-paladin-bin-master/chromite/lib/parallel.py", line 450, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/cbuild/stout32-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 246, in <lambda>
    upload = lambda path: self.UploadArtifact(path, archive, strict)
  File "/b/cbuild/stout32-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 275, in UploadArtifact
    update_list=True, acl=self.acl)
  File "/b/cbuild/stout32-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1182, in UploadArchivedFile
    raise cros_build_lib.TimeoutError('Timed out uploading %s' % filename)
TimeoutError: Timed out uploading image.zip
 in https://uberchromegw.corp.google.com/i/chromeos/builders/stout32%20paladin/builds/2609

Your change may have caused this failure. There are also other changes that may be at fault: CL:*147452, CL:173935, CL:175525, CL:175554, CL:175558, CL:175559

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1