CR50: Initialize variables to fix GCC 5.3 warnings
Looking at these warnings, none of these are real issues, so just
initialize the variables to make GCC 5.3 happy.

check_encrypt_params() either initialized the variables or returns
an error, so the hashing variable can't be used without initialization.

board/cr50/tpm2/rsa.c: In function '_cpri__EncryptRSA':
board/cr50/tpm2/rsa.c:99:9: error: 'hashing' may be used
uninitialized in this function [-Werror=maybe-uninitialized]

board/cr50/tpm2/rsa.c: In function '_cpri__DecryptRSA':
board/cr50/tpm2/rsa.c:134:9: error: 'hashing' may be used uninitialized in this
function [-Werror=maybe-uninitialized]

digest_len is only initialized or used in the TEST_RSA_VERIFY operation,
so there's no path where it can be used uninitialized.

board/cr50/tpm2/rsa.c: In function 'rsa_command_handler':
board/cr50/tpm2/rsa.c:974:7: error: 'digest_len' may be used uninitialized in
this function [-Werror=maybe-uninitialized]

BRANCH=none
BUG=none
TEST=build succeeds under GCC 5.3 and 4.9.2

Change-Id: Iafaaaed8b05080f70f2b1c2f0dbf1ee22227fd78
Signed-off-by: Martin Roth <martinroth@chromium.org>