Update patch set 1
Patch Set 1:

The following build(s) failed:

x86-alex paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/parallel.py", line 480, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 254, in <lambda>
    upload = lambda path: self.UploadArtifact(path, archive, strict)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 283, in UploadArtifact
    update_list=True, acl=self.acl)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1242, in UploadArchivedFile
    UpdateUploadedList(filename, archive_path, upload_url, debug)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1214, in UpdateUploadedList
    update_list=False)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1236, in UploadArchivedFile
    gs_context.CopyInto(local_path, upload_url)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/gs.py", line 357, in CopyInto
    acl=acl, version=version)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/gs.py", line 546, in Copy
    return self.DoCommand(cmd, **kwargs)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/gs.py", line 497, in DoCommand
    extra_env=extra_env, **kwargs)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 748, in GenericRetry
    return functor(*args, **kwargs)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 549, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
Copying file:///b/cbuild/x86-alex-paladin-bin-master/buildbot_archive/x86-alex-paladin/R34-5208.0.0-rc2/UPLOADED [Content-Type=application/octet-stream]...
Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/.cache/common/gsutil_3.37.tar.gz/gsutil/gsutil", line 88, in <module>
    sys.exit(gslib.__main__.main())
  File "/b/cbuild/x86-alex-paladin-bin-master/.cache/common/gsutil_3.37.tar.gz/gsutil/gslib/__main__.py", line 246, in main
    parallel_operations)
  File "/b/cbuild/x86-alex-paladin-bin-master/.cache/common/gsutil_3.37.tar.gz/gsutil/gslib/__main__.py", line 404, in _RunNamedCommandAndHandleExceptions
    exc_name, message, detail = util.ParseErrorDetail(e)
  File "/b/cbuild/x86-alex-paladin-bin-master/.cache/common/gsutil_3.37.tar.gz/gsutil/gslib/util.py", line 305, in ParseErrorDetail
    match = re.search(r'<Message>(?P<message>.*)</Message>', e.body)
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

Failed command "/b/cbuild/x86-alex-paladin-bin-master/.cache/common/gsutil_3.37.tar.gz/gsutil/gsutil -o 'GSUtil:parallel_composite_upload_threshold=0' cp -- /b/cbuild/x86-alex-paladin-bin-master/buildbot_archive/x86-alex-paladin/R34-5208.0.0-rc2/UPLOADED gs://chromeos-image-archive/x86-alex-paladin/R34-5208.0.0-rc2/UPLOADED", cwd=None, extra env={'BOTO_CONFIG': '/home/chrome-bot/.boto'}
 in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-alex%20paladin/builds/15292

x86-generic paladin: The UploadPrebuilts stage failed: ./upload_prebuilts failed (code=1) in http://build.chromium.org/p/chromiumos/builders/x86-generic%20paladin/builds/17132

Your change may have caused this failure. There are also other changes that may be at fault: CL:*151306, CL:*151408, CL:179322, CL:181920

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1