Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8784440165297076577) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    error: test/malloc.c: does not exist in index

Patch-set: 2
Tag: autogenerated:cq:full-run:1680901748
Attention: {"person_ident":"Gerrit User 1314845 \u003c1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}