power/icelake: add casts for power signals
When building with clang, it warns:

power/icelake.c:43:11: error: implicit conversion from enumeration type
'enum espi_vw_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                .gpio = SLP_S3_SIGNAL_L,
                        ^~~~~~~~~~~~~~~
include/power/intel_x86.h:36:25: note: expanded from macro 'SLP_S3_SIGNAL_L'
                        ^~~~~~~~~~~

Although "enum espi_vw_signal" and "enum gpio_signal" are not directly
compatible, it appears that the code in power/common.c takes that into
account by calling espi_signal_is_vw().

clang also produces another warning:

power/icelake.c:267:19: error: implicit conversion from enumeration type
'enum espi_vw_signal' to different enumeration type 'enum gpio_signal'
[-Werror,-Wenum-conversion]
                        gpio_set_flags(SLP_S3_SIGNAL_L, GPIO_ODR_LOW);
                        ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~
include/power/intel_x86.h:36:25: note: expanded from macro 'SLP_S3_SIGNAL_L'
                        ^~~~~~~~~~~

However, this warning should not be emitted because this code is inside
an IS_ENABLED(CONFIG_CHIPSET_SLP_S3_L_OVERRIDE) block. Changing
IS_ENABLED(CONFIG_CHIPSET_SLP_S3_L_OVERRIDE) to
"#if defined(CONFIG_CHIPSET_SLP_S3_L_OVERRIDE)" works around this.

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I1fe6bbb1881572a3eff756220ee960d397344c69