Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8874647894839710048
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/wheelie/board.c:1
        error: board/wheelie/board.c: patch does not apply
        error: patch failed: board/wheelie/board.h:1
        error: board/wheelie/board.h: patch does not apply

Patch-set: 1
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1125984 \u003c1125984@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}