third_party/boringssl: Remove unused header
When compiling with C++ (and using the C stdlib), this include is not
found:

include/aes-gcm.h:53:10: fatal error: 'endian.h' file not found
         ^~~~~~~~~~

Remove the header since it's not actually used in these files.

BRANCH=none
BUG=b:234181908
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I2f90b42cbfd4ca5334bfa400c9124755c4b1cf0d