Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8884980109420054688
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in common/build.mk

Patch-set: 2
Tag: autogenerated:cq:full-run