Update patch set 1
Patch Set 1: Verified-1

> Patch Set 1: -Commit-Queue
> 
> Commit-Queue label set to 0 programmatically by chromite.

This CL might have caused build error in nami-paradin.

chromeos-ec-0.0.1-r5262: /build/nami/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5262/temp/ccVpvQAo.ltrans0.ltrans.o: In function `board_init':
chromeos-ec-0.0.1-r5262: <artificial>:(.text+0x4814): undefined reference to `scancode_set2'
https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8927472026416641104/+/steps/BuildPackages/0/stdout

Patch-set: 1
Reviewer: Gerrit User 1110159 <1110159@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1