emul/isl923x: prevent compile errors with multiple chargers
If using more than one emulated ISL923x charger, a semicolon is required
in the macro definition otherwise the resultant code is invalid:

> emul_isl923x.c: In function ‘emul_isl923x_reset_before’:
> emul_isl923x.c:456:9: error: expected ‘;’ before ‘isl923x_emul_reset’

BUG=b:267959470
TEST=Test with two emulated ISL923x compiles without this error.
BRANCH=none

Change-Id: I576d998b32c985d9c3469d345ce4b60899269954
Signed-off-by: Peter Marheine <pmarheine@chromium.org>