fpsensor: Fix comparison between two different enums
This isn't an actual bug since both EC_RES_SUCCESS and EC_SUCCESS are 0,
but we could end up with a bug in the future since we're mixing types.
This change refactors the internal functions to return "enum
ec_error_list". By doing this, the compiler will complain if we mix
EC_RES_SUCCESS and EC_SUCCESS:

common/fpsensor/fpsensor.c: In function 'fp_command_template':
common/fpsensor/fpsensor.c:507:11: error: comparison between 'enum
ec_error_list' and 'enum ec_status' [-Werror=enum-compare]
   if (ret != EC_RES_SUCCESS) {
           ^~

Found by coverity:

*** CID 188678:  Incorrect expression  (MIXED_ENUMS)
/common/fpsensor/fpsensor.c: 507 in fp_command_template()
501            * decryption.
502            */
503           fp_clear_finger_context(idx);
504           /* The beginning of the buffer contains nonce/salt/tag. */
505           enc_info = (void *)fp_enc_buffer;
506           ret = validate_template_format(enc_info);
>>> CID 188678:  Incorrect expression  (MIXED_ENUMS)
>>> Mixing enum types "enum ec_error_list" and "enum ec_status" for "ret".
507           if (ret != EC_RES_SUCCESS) {
508                   CPRINTS("fgr%d: Template format not supported", idx);
509                   return EC_RES_INVALID_PARAM;
510           }
511           ret = derive_encryption_key(key, enc_info->salt);
512           if (ret != EC_SUCCESS) {

BRANCH=nocturne
BUG=chromium:1004831
TEST=make buildall -j
TEST=enroll finger on kohaku, reboot, login, lock, unlock with
     fingerprint

Change-Id: Id24233d5ed34c7e5002e705643de16a2050ea305
Signed-off-by: Tom Hughes <tomhughes@chromium.org>