test/run_device_tests: Disable zephyr_kernel_poll test
There's a compilation error caused by the latest Zephyr downstream:

/mnt/host/source/src/third_party/zephyr/main/kernel/sched.c:1065:20:
error: unused function 'z_vrfy_k_reschedule' [-Werror,-Wunused-function]
 1065 | static inline void z_vrfy_k_reschedule(void)
      |                    ^~~~~~~~~~~~~~~~~~~

Disabling this test for now so that the remaining Zephyr tests can run
in the CQ.

BUG=b:372943952
TEST=none

Change-Id: Iadefaa3c6db1c6166adf2269c457a89434f7f3fb