Update patch set 10
Patch Set 10: Verified-1

Looks like this broke nami-paladin:

chromeos-ec-0.0.1-r5177: /opt/coreboot-sdk/lib/gcc/arm-eabi/8.1.0/../../../../arm-eabi/bin/ld: Dwarf Error: Could not find abbrev number 1068.
chromeos-ec-0.0.1-r5177: /build/nami/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5177/temp/ccdgHgKj.ltrans0.ltrans.o: In function `board_init':
chromeos-ec-0.0.1-r5177: <artificial>:(.text+0x4654): undefined reference to `keyboard_cols'

Patch-set: 10
Reviewer: Gerrit User 1103880 <1103880@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1