upgrade_fw: do not accept headers smaller than a flash page
Headers smaller than flash page are not valid, let's not accept them
durinf firmware updates.

BUG=b:272058500

TEST=using dd corrupted an existing image header size field to be set
     to 0x400, and tried to download the image using gsctool and
     observed the expected error message on the Cr50 console:

    fw_upgrade_command_handler:505 image at 4000 too small

     and in the host terminal:

    Error: status 0xb

Change-Id: I27b0bbd6a1204b20bd2d0ac1ce88082ed911d339
Signed-off-by: Vadim Bendebury <vbendeb@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4316741
Tested-by: Vadim Bendebury <vbendeb@chromium.org>
Commit-Queue: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-by: Mary Ruthven <mruthven@chromium.org>
(cherry picked from commit 8b6ac106ba968bb3321e0fae98be00b29156232a)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4409344
Commit-Queue: Andrey Pronin <apronin@chromium.org>
Auto-Submit: Mary Ruthven <mruthven@chromium.org>
Reviewed-by: Andrey Pronin <apronin@chromium.org>
Tested-by: Mary Ruthven <mruthven@chromium.org>
(cherry picked from commit d23e384aa22b90089e8a28bed6d7a9f1ec1d437b)