Update patch set 4
Patch Set 4: Code-Review-1

You're aware that you can run these hooks yourself, right???

dianders@tictac:ec ((2090c47...))$ /b/tip/src/repohooks/pre-upload.py 2090c471c60e58466a9c4740fedc608688431b45
Errors in PROJECT *chromiumos/platform/ec*!
    COMMIT 2090c471:
        Description:
            >Minnie: Set battery IC BQ27541 configure.
            >
            >Minnie use the gauge TI BQ27541,
            >and use the battery temperature to control the
            >charge voltage and charge current.
            >
            >BUG=chrome-os-partner:35119
            >TEST=(1)Plug AC only without battery, board can boot.
            >     (2)Plug the AC and battery to board, it can charge normal.
            >     (3)Use command 'ectool battery' can read the battery information.
            >BRANCH=firmware-veyron-6588.B
            >
            >Signed-off-by: james_chao <james_chao@asus.com>
            >Change-Id: I5edab27d5ed095f2c6f62b1f8efcba9f83f68f67
            >
            >
        Errors:
            * checkpatch.pl errors/warnings
            
            ERROR: that open brace { should be on the previous line
            #68: FILE: board/minnie/battery.c:32:
            +   if (!(batt->flags & BATT_FLAG_BAD_TEMPERATURE))
            +   {
            
            ERROR: that open brace { should be on the previous line
            #73: FILE: board/minnie/battery.c:36:
            +           if (temp < 0)
            +           {
            
            ERROR: trailing whitespace
            #79: FILE: board/minnie/battery.c:42:
            +^I^Ielse if (temp < 12) $
            
            ERROR: that open brace { should be on the previous line
            #79: FILE: board/minnie/battery.c:42:
            +           else if (temp < 12) 
            +           {
            
            ERROR: else should follow close brace '}'
            #79: FILE: board/minnie/battery.c:42:
            +           }
            +           else if (temp < 12) 
            
            ERROR: trailing whitespace
            #85: FILE: board/minnie/battery.c:48:
            +^I^Ielse if (temp < 50) $
            
            ERROR: that open brace { should be on the previous line
            #85: FILE: board/minnie/battery.c:48:
            +           else if (temp < 50) 
            +           {
            
            ERROR: else should follow close brace '}'
            #85: FILE: board/minnie/battery.c:48:
            +           }
            +           else if (temp < 50) 
            
            ERROR: trailing whitespace
            #91: FILE: board/minnie/battery.c:54:
            +^I^Ielse if (temp < 55) $
            
            ERROR: that open brace { should be on the previous line
            #91: FILE: board/minnie/battery.c:54:
            +           else if (temp < 55) 
            +           {
            
            ERROR: else should follow close brace '}'
            #91: FILE: board/minnie/battery.c:54:
            +           }
            +           else if (temp < 55) 
            
            ERROR: that open brace { should be on the previous line
            #97: FILE: board/minnie/battery.c:60:
            +           else
            +           {
            
            ERROR: else should follow close brace '}'
            #97: FILE: board/minnie/battery.c:60:
            +           }
            +           else
            
            total: 13 errors, 0 warnings, 101 lines checked
            
            NOTE: whitespace errors detected, you may wish to use scripts/cleanpatch or
                  scripts/cleanfile
            
            NOTE: Ignored message types: MSLEEP VOLATILE
            
            Your patch has style problems, please review.
            
            If any of these errors are false positives, please report
            them to the maintainer, see CHECKPATCH in MAINTAINERS.
            
            * Hook script "util/presubmit_check.sh 2>&1" failed with code 1:
              Files have changed since last time unit tests passed:
                /b/tip/src/platform/ec/board/minnie/battery.c
                /b/tip/src/platform/ec/board/minnie/board.h
              Please run "make buildall -j".

Patch-set: 4
Label: Code-Review=-1