Update patch set 1
Patch Set 1:

NOTE: The Commit Queue will retry your change automatically.

The following build(s) failed:

auron_paine-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904444904226672

nocturne-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904333856269872

wizpig-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904264327845136

wolf-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904262521886336

betty-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904434859627312

kevin-arcnext-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904360759657312

caroline-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904425052542784

kevin-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904358988472544

betty-arcnext-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904436936680848

tidus-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904285344965136

veyron_mighty-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904276701348336

glados-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904378922700928

amd64-generic-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904451514967072

betty-arc64-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904438869626880

cave-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904422304556528

fizz-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904382849036320

veyron_speedy-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904271227393904

atlas-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904446510033504

scarlet-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904298067647904

nyan_kitty-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904325341983600

hana-paladin: The CommitQueueSync stage failed: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/firmware refs/changes/88/1313788/1
error: RPC failed; curl 18 transfer closed with o in https://ci.chromium.org/b/8930904366690103712

auron_yuna-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904443342594192

sentry-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904295993623808

quawks-paladin: The CommitQueueSync stage failed: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/overlays/portage-stable refs/changes/74/1314274/1
fatal: unable to access 'https://chromium-r in https://ci.chromium.org/b/8930904308535826896

kip-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904356904546736

chell-nowithdebug-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904420604233408

chell-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904418966566400

samus-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904300501430304

cyan-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904410970167712

moblab-generic-vm-paladin: The MoblabVMTest stage failed: return code: 1; command: cros_sdk -- test_that --no-quickmerge -b moblab-generic-vm --results_dir /tmp/cbuildbotIwkxKs/results localhost:19875 moblab_DummyServerNoSspSuite --args 'services_init_timeout_m=10 target_build="moblab-generic-vm-p in https://ci.chromium.org/b/8930904339147675072

kukui-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904355201745424

reef-paladin: The CommitQueueSync stage failed: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/firmware refs/changes/88/1313788/1
fatal: unable to access 'https://chromium-review. in https://ci.chromium.org/b/8930904304486394544

caroline-arcnext-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904426639127312

eve-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904392571627792

elm-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904400084019168

link-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904343193143424

arm-generic-paladin: The BuildPackages stage failed: Packages failed in ./build_packages: sys-kernel/chromeos-kernel-4_14 in https://ci.chromium.org/b/8930904448514282816

coral-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904413172180464

edgar-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904401827166224

poppy-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904310232828880

octopus-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904319040089792

bob-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904431928672016

cheza-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904417370870960

grunt-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904375296283216

peppy-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904312000018224

guado_moblab-paladin: aborted by self-destruction in https://ci.chromium.org/b/8930904368090608272

This failure was probably caused by CL:1163525

Commit queue documentation: https://dev.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1