util/genvif: Fix array bounds check
When removing the "-flto" flag when building genvif, gcc warns that that
the array can be out of bounds. This could occur if pushback_count was
set to a negative value since the if statement would be true:

util/genvif.c: In function ‘get_next_tag’:
util/genvif.c:1131:24: error: array subscript [-1, 2147483646] is
outside array bounds of ‘char[20]’ [-Werror=array-bounds]
 1131 |   return pushback_stack[--pushback_cnt];
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
util/genvif.c:1116:6: note: while referencing ‘pushback_stack’
 1116 | char pushback_stack[20];
      |      ^~~~~~~~~~~~~~

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I1bc84f1b58ceb0b921c2d51bf94ac378211d556c