common: online_calibration: Fix compilation issue
- Fix compilation error: sizeof() of an input array
was not calculated properly.
- Fix calling convetion: use sensor pointer instead of
sensor number
- Use common formula to calculate sensor number.

BUG=none
BRANCH=none
TEST=compile, unittest, load on eve with online calibration added.

Change-Id: I06ff30eb5710cbe8f91c939b2ccc084c20a37847
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>