Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8824115009251630785
    Merge conflict detected! Please rebase and retry.
    
        error: zephyr/boards/arm/herobrine_npcx9/herobrine_npcx9.dts: does not exist in index
        Applied patch to 'zephyr/projects/herobrine/BUILD.py' cleanly.
        Falling back to direct application...

Patch-set: 1
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1000407 \u003c1000407@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ full run failed."}