intel_x86: fix the build error when removing CONFIG_POWER_S0IX
The ec build error if the CONFIG_POWER_S0IX is removed from board.h
This patch fixes the build error:

power/intel_x86.c:515:13: error: 'lpc_s0ix_suspend_clear_masks' defined but not used [-Werror=unused-function]
 static void lpc_s0ix_suspend_clear_masks(void)
             ^
power/intel_x86.c:529:13: error: 'lpc_s0ix_resume_restore_masks' defined but not used [-Werror=unused-function]
 static void lpc_s0ix_resume_restore_masks(void)
             ^

BUG=none
BRANCH=master
TEST=1. make buildall -j
     2. Removing CONFIG_POWER_S0IX from rammus/board.h, build pass

Change-Id: I8c533736a7efb9f9f78ff71044431dd8a1698481
Signed-off-by: Zhuohao Lee <zhuohao@chromium.org>