driver/touchpad_st: Fix unaligned access warnings
When building with clang, it now warns if there is an unpacked struct
nested in a packed struct:

driver/touchpad_st.c:109:2: error: field  within 'struct (unnamed at
driver/touchpad_st.c:105:8)' is less aligned than 'union (anonymous at
driver/touchpad_st.c:109:2)' and is usually due to 'struct (unnamed at
driver/touchpad_st.c:105:8)' being packed, which can lead to unaligned
accesses [-Werror,-Wunaligned-access]
        union {
        ^

See https://github.com/llvm/llvm-project/issues/55520.

BRANCH=none
BUG=b:172020503
TEST=CC=clang make BOARD=whiskers

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Id870922e05ecb89037e323a6d38083d07f205ee3