common: fixed build error if not define CONFIG_USB_PORT_POWER_ENABLE_DELAY
remove the 'static' attribute to fixed build error:
"common/usb_port_power_smart.c:57:12: error: ‘usb_charge_is_enabled’
defined but not used [-Werror=unused-function]"

BUG=none
BRANCH=firmware-strago-7287.B
TEST=build success without CONFIG_USB_PORT_POWER_ENABLE_DELAY

Change-Id: I82c43c986e42e626d551ca3d8bde6e16149b7e7d
Signed-off-by: lehai deng <denglehai@ithaier.com>