Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8884261234622965008
    Merge conflict detected! Please rebase and retry.
    
        error: mode change for overlay-hatch/chromeos-base/chromeos-config-bsp-hatch/chromeos-config-bsp-hatch-0.0.1-r72.ebuild, which is not in current HEAD
        error: could not build fake ancestor
        hint: Use 'git am --show-current-patch' to see the failed patch

Patch-set: 2
Tag: autogenerated:cq:dry-run