Update patch set 2
Patch Set 2: Verified-1

Has this caused a build failure? Sorry if I got the wrong change

https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8939921639282843952

https://luci-logdog.appspot.com/v/?s=chromeos/bb/chromeos/caroline-arcnext-paladin/1055/+/recipes/steps/UnitTest/0/stdout

chromeos-ec-0.0.1-r4975: power/intel_x86.c:52:19: error: 'GPIO_PCH_SLP_S3_L' undeclared here (not in a function)
chromeos-ec-0.0.1-r4975:   [SYS_SLEEP_S3] = GPIO_PCH_SLP_S3_L,
chromeos-ec-0.0.1-r4975:                    ^
chromeos-ec-0.0.1-r4975: power/intel_x86.c:53:19: error: 'GPIO_PCH_SLP_S4_L' undeclared here (not in a function)
chromeos-ec-0.0.1-r4975:   [SYS_SLEEP_S4] = GPIO_PCH_SLP_S4_L,
chromeos-ec-0.0.1-r4975:

Patch-set: 2
Reviewer: Gerrit User 1165921 <1165921@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1