stm32: Work around gcc-6.3 issue
gcc 6.3 doesn't detect that alarm_us is only used if initialized:
    chip/stm32/clock-f.c: In function 'set_rtc_alarm':
    chip/stm32/clock-f.c:216:10: error: 'alarm_us' may be used
         uninitialized in this function [-Werror=maybe-uninitialized]
         (us_to_rtcss(alarm_us) | 0x0f000000) : 0;
          ^~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

gcc 8.1 doesn't have this problem, but upstream coreboot has an issue
with this until crossgcc can migrate to 8.1, for which building EC code
is a pre-requisite.

BUG=b:65441143
BRANCH=none
TEST=glados_pd builds with gcc 4.9, 6.3 and 8.1

Change-Id: I905fb2dfcdd070daec8b969c65ece69517f66f34
Signed-off-by: Patrick Georgi <pgeorgi@google.com>