zephyr: kscan: npcx: remove register define and delete kscan node
The register definition and devicetree node of the keyboard scan module
are added to the upstream. This CL removes the duplicate register
definition to avoid a compiler error: redefinition of 'struct kbs_reg'

Also, add "/delete-node/ kscan@400a3000" to arm/board/*/npcx*.dtsi to
suppress the compiler warning: soc/kscan@400a3000: duplicate
unit-address (also used in node /soc/cros-kb-raw@400a3000).

This CL has dependency on PR:
https://github.com/zephyrproject-rtos/zephyr/pull/50457

BUG=none
BRANCH=none
TEST=With PR:50457 and this CL, zmake npcx9/nivviks/steelix/skyrim,
there is no compiler error or warning related to kscan.

Signed-off-by: Jun Lin <CHLin56@nuvoton.com>
Change-Id: I259ef6b2d1119dcb67a20292d21f20bfc12aca1c