Update patch set 2
Patch Set 2: Verified+1 Auto-Submit+1 Commit-Queue+1

Uploaded with --ignore-hooks due to what seems like an unrelated presubmit failure:

[FAILED] chromiumos/platform/ec: presubmit_check                         
    Hook script "util/presubmit_check.sh" failed with code 1:
      +++ b/common/vboot/efs2.c
      +	CPRINTS("Reboot\n\n");
      error: CPRINTS strings should not include newline characters

Patch-set: 2
Reviewer: Gerrit User 1314845 <1314845@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1202834 <1202834@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1
Label: Verified=+1
Label: Auto-Submit=+1