Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8872067859698542112
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: board/dirinboz/board.c:1
        Falling back to three-way merge...
        Applied patch to 'board/dirinboz/board.c' with conflicts.
        U board/dirinboz/board.c

Patch-set: 2
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1409227 \u003c1409227@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}