Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2: Code-Review-1
> > >
> > > Run your CLs through the pre-submit check please.
> > 
> > I’ll gladly do that, if you tell me how.
> 
> If you have a regular developer setup as described in http://dev.chromium.org/chromium-os/developer-guide
> it will do it automatically when you do 'repo upload .' (after asking for confirmation)
> 
> If you have some hacked-up local setup, there are some advice there:
> http://dev.chromium.org/chromium-os/ec-development#TOC-Submitting-changes

Unfortunately, I do not get it to pass as the included `util/signer` seems incompatible with OpenSSL 1.1.0f-5 from Debian Sid/unstable.

```
$ make buildall -j
[…]
  LD      RW/ec.RW_B.elf
In file included from util/signer/publickey.cc:16:0:
./util/signer/common/gnubby.h:13:30: error: conflicting declaration 'typedef struct env_md_ctx_st EVP_MD_CTX'
 typedef struct env_md_ctx_st EVP_MD_CTX;
                              ^~~~~~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from util/signer/publickey.cc:10:
/usr/include/openssl/ossl_typ.h:92:30: note: previous declaration as 'typedef struct evp_md_ctx_st EVP_MD_CTX'
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                              ^~~~~~~~~~
In file included from util/signer/publickey.cc:10:0:
util/signer/publickey.cc: In member function 'size_t PublicKey::nwords()':
util/signer/publickey.cc:65:36: error: invalid use of incomplete type 'RSA {aka struct rsa_st}'
   size_t result = (BN_num_bytes(rsa->n) + 3) / 4;
                                    ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from util/signer/publickey.cc:10:
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'RSA {aka struct rsa_st}'
 typedef struct rsa_st RSA;
                ^~~~~~
In file included from util/signer/publickey.cc:10:0:
[…]
```

So, I manually added the tags, and I depend on the build servers to tell me, what I have to improve.

Patch-set: 3
Reviewer: Gerrit User 1245511 <1245511@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>