Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4:
> > > 
> > > > Patch Set 4:
> > > > 
> > > > Getting "ERROR: Failed to determine chip size!" while flashing ec on Bobba with this change
> > > 
> > > Hello Ayushee,
> > > 
> > > Could you grep run and grep the result for me please?
> > > 
> > > 1. run ServoD 
> > > sudo servod -b octopus_npcx --debug
> > > 
> > > 2. Dut-control value checking
> > > dut-control ec_board ec_chip
> > > 
> > > 3. flash_ec
> > > flash_ec --board=bobba --image=${IMG} --verbose
> > > 
> > > Thankyou!
> > 
> > Also I'd like to ask you to try battery cutoff before you start another test attempt.
> 
> Do you want me to send the output for opening the servo as well?
> 
> 2. dut-control ec_board ec_chip
> Output:
> ec_board:bobba
> ec_chip:npcx_spi
> 
> 3. (cherry-picked your code and build the image using: make BOARD=bobba -j)
> flash_ec --board=bobba --image=build/bobba/ec.bin --verbose:
> Output:
> INFO: Using servo_v2.
> INFO: Using ec image : build/bobba/ec.bin
> INFO: Flashing chip npcx_spi.
> dut-control --port=9999 cold_reset:on
> dut-control --port=9999 spi1_vref:pp3300 spi1_buf_en:on
> dut-control --port=9999 spi1_buf_on_flex_en:on
> INFO: Running flashrom:
>  sudo /usr/sbin/flashrom -p ft2232_spi:type=servo-v2,port=B,serial=000000-00071 --get-size
> ERROR: Failed to determine chip size!
> INFO: Restoring servo settings...
> dut-control --port=9999 cold_reset:off
> dut-control --port=9999 jtag_buf_en:on
> dut-control --port=9999 jtag_buf_on_flex_en:on
> dut-control --port=9999 spi1_vref:off
> dut-control --port=9999 cold_reset:on
> dut-control --port=9999 cold_reset:off

Thank you Ayushee,

Looks like you need to update hdctools. 
Newer hdctools will tell you ec_chip is npcx_int_spi.

Please do 'sudo emerge hdctools' and rerun.

Let me know how far you go.

Patch-set: 4