DO NOT SUBMIT: Temporarily disable warnings
include/ec_commands.h:5923:2:
error: field  within 'struct ec_response_pd_chip_info' is less aligned
than 'union ec_response_pd_chip_info::(anonymous at
include/ec_commands.h:5923:2)' and is usually due to 'struct
ec_response_pd_chip_info' being packed, which can lead to unaligned
accesses [-Werror,-Wunaligned-access]
        union {
        ^

BRANCH=none
BUG=b:172020503
TEST=none

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I73372da27b25b5d6743f4556b0a445abcab6c565