Update patch set 2
Patch Set 2: Verified-1

Broke CQ in combination with CL:769152.

chromeos-ec-0.0.1-r4380: In file included from board/nami/usb_pd_policy.c:9:0:
chromeos-ec-0.0.1-r4380: include/charge_manager.h:105:2: error: #error "DEDICATED_CHARGE_PORT must be defined"
chromeos-ec-0.0.1-r4380:  #error "DEDICATED_CHARGE_PORT must be defined"
chromeos-ec-0.0.1-r4380:   ^

Patch-set: 2
Reviewer: Gerrit User 1129199 <1129199@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1