zephyr: ioex: Fix compile error when cros ioex drivers enabled
This fix Compilation error: implicit declaration of function
'convert_from_zephyr_flags' when the following Kconfig options are set:
    CONFIG_PLATFORM_EC_IOEX=y
    CONFIG_PLATFORM_EC_IOEX_CROS_DRV=y

BUG=none
BRANCH=none
TEST=Zephyr Build Succssfull

Signed-off-by: Rajesh Kumar <rajesh3.kumar@intel.com>
Change-Id: I87a0deec1f2a2cac429568af17308f7c9ff95c4f