assert.h: Remove unnecessary extern
Functions in C are extern by default; it's not necessary in a header
file. The extern combined with noreturn causes a compiler error when
building with C++:

./builtin/assert.h:33:8: error: an attribute list cannot appear here
extern noreturn void panic_assert_fail(const char *msg, const char *func,
       ^~~~~~~~

BRANCH=none
BUG=b:234181908
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I7a2a86e57569bc90bb1ab93d5703217eabc042a4