Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8875586582301123328
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: driver/ppc/syv682x.c:1
        Falling back to three-way merge...
        Applied patch to 'driver/ppc/syv682x.c' with conflicts.
        U driver/ppc/syv682x.c

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1347775 \u003c1347775@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}