Update patch set 7
Patch Set 7: Verified-1

It seems that this CL breaks CQ:
https://ci.chromium.org/p/chromeos/builders/general/CommitQueue/b8915980963500432496
https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8915978436964297840/+/steps/UnitTest/0/stdout

chromeos-ec-0.0.1-r5482: [01m[Kbaseboard/zork/baseboard.c:92:4:[m[K [01;31m[Kerror: [m[K'[01m[Kconst struct tcpc_config_t[m[K' has no member named '[01m[Kpol[m[K'
chromeos-ec-0.0.1-r5482:    .[01;31m[Kpol[m[K = TCPC_ALERT_ACTIVE_LOW,
chromeos-ec-0.0.1-r5482:     [01;31m[K^~~[m[K

I think the error might be caused by this CL or https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1551582.

Could you double check?

Patch-set: 7
Reviewer: Gerrit User 1132275 <1132275@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1