tree: Use bitwise operator instead of logical operator
When building with clang, it warns:

board/lalala/board.c:819:28: error: use of logical '&&' with constant operand
[-Werror,-Wconstant-logical-operand]
                if (adc_key_state_change && ADC_VOL_DOWN_MASK)
                                         ^  ~~~~~~~~~~~~~~~~~
board/lalala/board.c:819:28: note: use '&' for a bitwise operation
                if (adc_key_state_change && ADC_VOL_DOWN_MASK)
                                         ^~
                                         &
board/lalala/board.c:819:28: note: remove constant to silence this warning
                if (adc_key_state_change && ADC_VOL_DOWN_MASK)
                                        ~^~~~~~~~~~~~~~~~~~~~

The code appears to have been copied to several boards, which were found
with:

git grep --name-only 'adc_key_state_change &&'

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=lalala

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I2c473f27f2ea805c94aab0276049acf8282b6092