Update patch set 10
Patch Set 10: Verified+1 Commit-Queue+2

Failed for /build/flapjack/tmp/portage/chromeos-base/chromeos-ec-0.0.1-r5470/work/chromeos-ec-0.0.1/platform/ec/common/charge_state_v2.c:1368: undefined reference to `battery_cutoff' but battery_cutoff is defined and it builds successfully for flapjack.

Rebased. Try again.

Patch-set: 10
Reviewer: Gerrit User 1106949 <1106949@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2
Label: Verified=+1